USE PROYECTO_WYK;

CALL CONSULTAR_CARGO();
CALL CONSULTAR_USUARIO();
CALL CONSULTAR_EMPLEADO();
CALL CONSULTAR_CLIENTE();
CALL CONSULTAR_PRODUCTO();
CALL CONSULTAR_VENTA();
CALL CONSULTAR_DETALLE_VENTA();
CALL CONSULTAR_AJUSTE_INVENTARIO();
CALL CONSULTAR_PROVEEDOR();
CALL CONSULTAR_MATERIA_PRIMA();
CALL CONSULTAR_FACTURA_COMPRA();
CALL CONSULTAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA();
CALL CONSULTAR_DETALLE_COMPRA_PRODUCTO();
CALL CONSULTAR_PRODUCCION();