USE PROYECTO_WYK;

START TRANSACTION;

-- 👮‍CALL CARGO👮‍
CALL INSERTAR_CARGO('TesterCargo', 1);
CALL ELIMINAR_CARGO(LAST_INSERT_ID());

/* 🤴CALL USUARIO👸*/
CALL INSERTAR_USUARIO('usuario.test', 'password_test', NOW(), NOW(), 'CLIENTE', 1);
CALL ELIMINAR_USUARIO(LAST_INSERT_ID());

-- 👩‍🍳CALL EMPLEADO👨‍🍳
CALL INSERTAR_EMPLEADO(999999001, 'Empleado Test', 'O+', 3000000001, 'empleado.test@wyk.com', 1, 1, 1);
CALL ELIMINAR_EMPLEADO(LAST_INSERT_ID());

-- 👦CALL CLIENTE👦
CALL INSERTAR_CLIENTE(999999002, 'CC', 'Cliente Test', 3000000002, 'cliente.test@email.com', 1, 1, 1);
CALL ELIMINAR_CLIENTE(LAST_INSERT_ID());

-- 🍰CALL PEDIDO🍰
CALL INSERTAR_PEDIDO(NOW(), 1, 1, 1, 'PENDIENTE');
CALL ELIMINAR_PEDIDO(LAST_INSERT_ID());

-- 🥐CALL PRODUCTO🥐
CALL INSERTAR_PRODUCTO(779999, 'Producto Test', 1000, 10, '2026-01-01', 'PRUEBA', 'Producto de prueba', 'Wyk Test', 1, 1);
CALL ELIMINAR_PRODUCTO(LAST_INSERT_ID());

-- 🚲CALL DETALLE PEDIDO🚲
CALL INSERTAR_DETALLE_PEDIDO(5, 'Detalle pedido de prueba', 1, 770001, 1);
CALL ELIMINAR_DETALLE_PEDIDO(LAST_INSERT_ID());

-- 📄CALL FACTURA VENTA📄
CALL INSERTAR_FACTURA_VENTA(5000, NOW(), 'Factura de prueba', 1, 1, 1, 'PAGADA');
CALL ELIMINAR_FACTURA_VENTA(LAST_INSERT_ID());

-- 🔖CALL DETALLE_VENTA_PRODUCTO🔖
CALL INSERTAR_DETALLE_VENTA_PRODUCTO(5, 1, 5000, 1, 770001, 1);
CALL ELIMINAR_DETALLE_VENTA_PRODUCTO(LAST_INSERT_ID());

-- 👩‍💼CALL PROVEEDOR👨‍💼
CALL INSERTAR_PROVEEDOR(899999001, 'Proveedor Test', 6015551111, 'proveedor.test@email.com', 1, 1);
CALL ELIMINAR_PROVEEDOR(LAST_INSERT_ID());

-- 🥣CALL MATERIA PRIMA🥣
CALL INSERTAR_MATERIA_PRIMA('Materia Prima Test', '2026-02-02', 'Kilogramos', 10, 'MarcaTest', 'Caja 1kg', 'Materia prima de prueba', 1, 1);
CALL ELIMINAR_MATERIA_PRIMA(LAST_INSERT_ID());

-- 📜CALL FACTURA COMPRA📜
CALL INSERTAR_FACTURA_COMPRA(25000, NOW(), 'Factura compra test', 1, 1, 'PENDIENTE');
CALL ELIMINAR_FACTURA_COMPRA(LAST_INSERT_ID());

-- 📰CALL DETALLE_FACTURA_COMPRA_MATERIA_PRIMA📰
CALL INSERTAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA(5, 5, 10000, 1, 1, 1);
CALL ELIMINAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA(LAST_INSERT_ID());

-- 🍮CALL DETALLE_COMPRA_PRODUCTO🍮
CALL INSERTAR_DETALLE_COMPRA_PRODUCTO(5, 5, 15000, 1, 770001, 1);
CALL ELIMINAR_DETALLE_COMPRA_PRODUCTO(LAST_INSERT_ID());

-- 🍲CALL PRODUCCION🍲
CALL INSERTAR_PRODUCCION('Producción Test', 5, 'Prueba de producción', 2, 1, 770001, 1, 1);
CALL ELIMINAR_PRODUCCION(LAST_INSERT_ID());

COMMIT;
SELECT 'Todos los CALL ejecutados correctamente. COMMIT realizado.' AS Mensaje;

/*ROLLBACK; ejecutar en caso de error.*/