USE PROYECTO_WYK;

DELIMITER $
-- ----------------------------------------------------------
-- 👑 TRIGGER INSERTAR ROL
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_ROL
AFTER INSERT ON ROL
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_ROL (ACCION_INSERT_ROL,FECHA_EJECUTO_INSERT_ROL)
    VALUES ('SE INSERTO CORRECTAMENTE EN ROL', NOW());
END $

-- ----------------------------------------------------------
-- 👤 TRIGGER INSERTAR USUARIO
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_USUARIO
AFTER INSERT ON USUARIO
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_USUARIO (ACCION_INSERT_USUARIO,FECHA_EJECUTO_INSERT_USUARIO)
    VALUES ('SE INSERTO CORRECTAMENTE EN USUARIO', NOW());
END $

-- ----------------------------------------------------------
-- 📋 TRIGGER INSERTAR TAREA
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_TAREA
AFTER INSERT ON TAREA
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_TAREA (ACCION_INSERT_TAREA,FECHA_EJECUTO_INSERT_TAREA)
    VALUES ('SE INSERTO CORRECTAMENTE EN TAREA', NOW());
END $

-- ----------------------------------------------------------
-- 🍞 TRIGGER INSERTAR PRODUCTO
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_PRODUCTO
AFTER INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_PRODUCTO (ACCION_INSERT_PRODUCTO,FECHA_EJECUTO_INSERT_PRODUCTO)
    VALUES ('SE INSERTO CORRECTAMENTE EN PRODUCTO', NOW());
END $

-- ----------------------------------------------------------
-- 🛒 TRIGGER INSERTAR VENTA
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_VENTA
AFTER INSERT ON VENTA
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_VENTA (ACCION_INSERT_VENTA,FECHA_EJECUTO_INSERT_VENTA)
    VALUES ('SE INSERTO CORRECTAMENTE EN VENTA', NOW());
END $

-- ----------------------------------------------------------
-- 📦 TRIGGER INSERTAR DETALLE_VENTA
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_DETALLE_VENTA
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_DETALLE_VENTA (ACCION_INSERT_DETALLE_VENTA,FECHA_EJECUTO_INSERT_DETALLE_VENTA)
    VALUES ('SE INSERTO CORRECTAMENTE EN DETALLE_VENTA', NOW());
END $

-- ----------------------------------------------------------
-- 📉 TRIGGER INSERTAR AJUSTE_INVENTARIO
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_AJUSTE_INVENTARIO
AFTER INSERT ON AJUSTE_INVENTARIO
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_AJUSTE_INVENTARIO (ACCION_INSERT_AJUSTE,FECHA_EJECUTO_INSERT_AJUSTE)
    VALUES ('SE INSERTO CORRECTAMENTE EN AJUSTE_INVENTARIO', NOW());
END $

-- ----------------------------------------------------------
-- 🌾 TRIGGER INSERTAR MATERIA_PRIMA
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_MATERIA_PRIMA
AFTER INSERT ON MATERIA_PRIMA
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_MATERIA_PRIMA (ACCION_INSERT_MP,FECHA_EJECUTO_INSERT_MP)
    VALUES ('SE INSERTO CORRECTAMENTE EN MATERIA_PRIMA', NOW());
END $
-- ----------------------------------------------------------
-- 🧾 TRIGGER INSERTAR COMPRA
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_COMPRA
AFTER INSERT ON COMPRA
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_COMPRA (ACCION_INSERT_COMPRA,FECHA_EJECUTO_INSERT_COMPRA)
    VALUES ('SE INSERTO CORRECTAMENTE EN COMPRA', NOW());
END $

-- ----------------------------------------------------------
-- 📑 TRIGGER INSERTAR DETALLE_COMPRA_MATERIA_PRIMA
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_DET_COMPRA_MP
AFTER INSERT ON DETALLE_COMPRA_MATERIA_PRIMA
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_DET_COMPRA_MP (ACCION_INSERT_DET_COMPRA_MP,FECHA_EJECUTO_INSERT_DET_COMPRA_MP)
    VALUES ('SE INSERTO CORRECTAMENTE EN DETALLE_COMPRA_MATERIA_PRIMA', NOW());
END $

-- ----------------------------------------------------------
-- 🧺 TRIGGER INSERTAR DETALLE_COMPRA_PRODUCTO
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_DET_COMPRA_PROD
AFTER INSERT ON DETALLE_COMPRA_PRODUCTO
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_DET_COMPRA_PROD (ACCION_INSERT_DET_COMPRA_PROD,FECHA_EJECUTO_INSERT_DET_COMPRA_PROD)
    VALUES ('SE INSERTO CORRECTAMENTE EN DETALLE_COMPRA_PRODUCTO', NOW());
END $

-- ----------------------------------------------------------
-- 📚 TRIGGER INSERTAR RECETA
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_RECETA
AFTER INSERT ON RECETA
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_RECETA (ACCION_INSERT_RECETA,FECHA_EJECUTO_INSERT_RECETA)
    VALUES ('SE INSERTO CORRECTAMENTE EN RECETA', NOW());
END $

-- ----------------------------------------------------------
-- 🏭 TRIGGER INSERTAR PRODUCCION
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_PRODUCCION
AFTER INSERT ON PRODUCCION
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_PRODUCCION (ACCION_INSERT_PRODUCCION,FECHA_EJECUTO_INSERT_PRODUCCION)
    VALUES ('SE INSERTO CORRECTAMENTE EN PRODUCCION', NOW());
END $

-- ----------------------------------------------------------
-- 📝 TRIGGER INSERTAR DETALLE_PRODUCCION
-- ----------------------------------------------------------
CREATE TRIGGER TRIGGER_INSERTAR_DET_PRODUCCION
AFTER INSERT ON DETALLE_PRODUCCION
FOR EACH ROW
BEGIN
    INSERT INTO T_INSERTAR_DET_PRODUCCION (ACCION_INSERT_DET_PRODUCCION,FECHA_EJECUTO_INSERT_DET_PRODUCCION)
    VALUES ('SE INSERTO CORRECTAMENTE EN DETALLE_PRODUCCION', NOW());
END $
