USE PROYECTO_WYK;

DELIMITER $

-- ============================
-- TRIGGERS DE AUDITORÍA UPDATE
-- ============================

CREATE TRIGGER TRIGGER_ACTUALIZAR_ROL
AFTER UPDATE ON ROL
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_ROL
    (T_A_ID_ROL,T_A_ROL,T_A_CLASIFICACION,T_A_ESTADO_ROL,FECHA_ACTUALIZACION_ROL)
    VALUES (OLD.ID_ROL,OLD.ROL,OLD.CLASIFICACION,OLD.ESTADO_ROL,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_USUARIO
AFTER UPDATE ON USUARIO
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_USUARIO
    (T_A_ID_USUARIO,T_A_NUM_DOC,T_A_NOMBRE,T_A_PASSWORD_USUARIO,T_A_TEL_USUARIO,T_A_EMAIL_USUARIO,
     T_A_FECHA_REGISTRO,T_A_ROL_FK_USUARIO,T_A_ESTADO_USUARIO,FECHA_ACTUALIZACION_USUARIO)
    VALUES (OLD.ID_USUARIO,OLD.NUM_DOC,OLD.NOMBRE,OLD.PASSWORD_USUARIO,OLD.TEL_USUARIO,OLD.EMAIL_USUARIO,
     OLD.FECHA_REGISTRO,OLD.ROL_FK_USUARIO,OLD.ESTADO_USUARIO,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_TAREA
AFTER UPDATE ON TAREA
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_TAREA
    (T_A_ID_TAREA,T_A_TAREA,T_A_CATEGORIA,T_A_DESCRIPCION,T_A_TIEMPO_ESTIMADO_HORAS,
     T_A_PRIORIDAD,T_A_ESTADO_TAREA,T_A_USUARIO_ASIGNADO_FK,T_A_USUARIO_CREADOR_FK,
     FECHA_ACTUALIZACION_TAREA)
    VALUES (OLD.ID_TAREA,OLD.TAREA,OLD.CATEGORIA,OLD.DESCRIPCION,OLD.TIEMPO_ESTIMADO_HORAS,
     OLD.PRIORIDAD,OLD.ESTADO_TAREA,OLD.USUARIO_ASIGNADO_FK,OLD.USUARIO_CREADOR_FK,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_PRODUCTO
AFTER UPDATE ON PRODUCTO
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_PRODUCTO
    (T_A_ID_PRODUCTO,T_A_NOMBRE_PRODUCTO,T_A_VALOR_UNITARIO_PRODUCTO,T_A_CANT_EXIST_PRODUCTO,
     T_A_FECHA_VENCIMIENTO_PRODUCTO,T_A_TIPO_PRODUCTO,T_A_ID_USUARIO_FK_PRODUCTO,T_A_ESTADO_PRODUCTO,
     FECHA_ACTUALIZACION_PRODUCTO)
    VALUES (OLD.ID_PRODUCTO,OLD.NOMBRE_PRODUCTO,OLD.VALOR_UNITARIO_PRODUCTO,OLD.CANT_EXIST_PRODUCTO,
     OLD.FECHA_VENCIMIENTO_PRODUCTO,OLD.TIPO_PRODUCTO,OLD.ID_USUARIO_FK_PRODUCTO,OLD.ESTADO_PRODUCTO,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_VENTA
AFTER UPDATE ON VENTA
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_VENTA
    (T_A_ID_VENTA,T_A_FECHA_HORA_VENTA,T_A_TOTAL_VENTA,T_A_NUMERO_MESA,T_A_DESCRIPCION,
     T_A_ID_USUARIO_FK_VENTA,T_A_ESTADO_PEDIDO,T_A_ESTADO_PAGO,FECHA_ACTUALIZACION_VENTA)
    VALUES (OLD.ID_VENTA,OLD.FECHA_HORA_VENTA,OLD.TOTAL_VENTA,OLD.NUMERO_MESA,OLD.DESCRIPCION,
     OLD.ID_USUARIO_FK_VENTA,OLD.ESTADO_PEDIDO,OLD.ESTADO_PAGO,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_DETALLE_VENTA
AFTER UPDATE ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_DETALLE_VENTA
    (T_A_ID_DETALLE_VENTA,T_A_CANTIDAD,T_A_SUB_TOTAL,T_A_ID_VENTA_FK_DET_VENTA,
     T_A_ID_PRODUCTO_FK_DET_VENTA,FECHA_ACTUALIZACION_DETALLE_VENTA)
    VALUES (OLD.ID_DETALLE_VENTA,OLD.CANTIDAD,OLD.SUB_TOTAL,OLD.ID_VENTA_FK_DET_VENTA,
     OLD.ID_PRODUCTO_FK_DET_VENTA,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_AJUSTE_INVENTARIO
AFTER UPDATE ON AJUSTE_INVENTARIO
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_AJUSTE_INVENTARIO
    (T_A_ID_AJUSTE,T_A_FECHA_AJUSTE,T_A_TIPO_AJUSTE,T_A_CANTIDAD_AJUSTADA,T_A_DESCRIPCION,
     T_A_ID_PROD_FK_AJUSTE_INVENTARIO,T_A_ID_USUARIO_FK_AJUSTE_INVENTARIO,FECHA_ACTUALIZACION_AJUSTE)
    VALUES (OLD.ID_AJUSTE,OLD.FECHA_AJUSTE,OLD.TIPO_AJUSTE,OLD.CANTIDAD_AJUSTADA,OLD.DESCRIPCION,
     OLD.ID_PROD_FK_AJUSTE_INVENTARIO,OLD.ID_USUARIO_FK_AJUSTE_INVENTARIO,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_MATERIA_PRIMA
AFTER UPDATE ON MATERIA_PRIMA
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_MATERIA_PRIMA
    (T_A_ID_MATERIA_PRIMA,T_A_NOMBRE_MATERIA_PRIMA,T_A_VALOR_UNITARIO_MAT_PRIMA,T_A_FECHA_VENCIMIENTO_MATERIA_PRIMA,
     T_A_CANTIDAD_EXIST_MATERIA_PRIMA,T_A_PRESENTACION_MATERIA_PRIMA,T_A_DESCRIPCION_MATERIA_PRIMA,
     T_A_ID_USUARIO_FK_MATERIA_PRIMA,T_A_ESTADO_MATERIA_PRIMA,FECHA_ACTUALIZACION_MATERIA_PRIMA)
    VALUES (OLD.ID_MATERIA_PRIMA,OLD.NOMBRE_MATERIA_PRIMA,OLD.VALOR_UNITARIO_MAT_PRIMA,OLD.FECHA_VENCIMIENTO_MATERIA_PRIMA,
     OLD.CANTIDAD_EXIST_MATERIA_PRIMA,OLD.PRESENTACION_MATERIA_PRIMA,OLD.DESCRIPCION_MATERIA_PRIMA,
     OLD.ID_USUARIO_FK_MATERIA_PRIMA,OLD.ESTADO_MATERIA_PRIMA,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_COMPRA
AFTER UPDATE ON COMPRA
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_COMPRA
    (T_A_ID_COMPRA,T_A_FECHA_HORA_COMPRA,T_A_TIPO,T_A_TOTAL_COMPRA,T_A_NOMBRE_PROVEEDOR,T_A_MARCA,
     T_A_TEL_PROVEEDOR,T_A_EMAIL_PROVEEDOR,T_A_DESCRIPCION_COMPRA,T_A_ID_USUARIO_FK_COMPRA,
     T_A_ESTADO_FACTURA_COMPRA,FECHA_ACTUALIZACION_COMPRA)
    VALUES (OLD.ID_COMPRA,OLD.FECHA_HORA_COMPRA,OLD.TIPO,OLD.TOTAL_COMPRA,OLD.NOMBRE_PROVEEDOR,OLD.MARCA,
     OLD.TEL_PROVEEDOR,OLD.EMAIL_PROVEEDOR,OLD.DESCRIPCION_COMPRA,OLD.ID_USUARIO_FK_COMPRA,
     OLD.ESTADO_FACTURA_COMPRA,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_DETALLE_COMPRA_MP
AFTER UPDATE ON DETALLE_COMPRA_MATERIA_PRIMA
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_DETALLE_COMPRA_MP
    (T_A_ID_DET_COMPRA_MAT_PRIM,T_A_CANTIDAD_MAT_PRIMA_COMPRADA,T_A_SUB_TOTAL_MAT_PRIMA_COMPRADA,
     T_A_ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA,T_A_ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA,
     T_A_ESTADO_DET_COMPRA_MAT_PRIMA,FECHA_ACTUALIZACION_DETALLE_COMPRA_MP)
    VALUES (OLD.ID_DET_COMPRA_MAT_PRIM,OLD.CANTIDAD_MAT_PRIMA_COMPRADA,OLD.SUB_TOTAL_MAT_PRIMA_COMPRADA,
     OLD.ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA,OLD.ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA,
     OLD.ESTADO_DET_COMPRA_MAT_PRIMA,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_DETALLE_COMPRA_PROD
AFTER UPDATE ON DETALLE_COMPRA_PRODUCTO
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_DETALLE_COMPRA_PROD
    (T_A_ID_DET_COMPRA_PROD,T_A_CANTIDAD_PROD_COMPRADO,T_A_SUB_TOTAL_PROD_COMPRADO,
     T_A_ID_COMPRA_FK_DET_COMPRA_PROD,T_A_ID_PROD_FK_DET_COMPRA_PROD,T_A_ESTADO_DET_COMPRA_PROD,
     FECHA_ACTUALIZACION_DETALLE_COMPRA_PROD)
    VALUES (OLD.ID_DET_COMPRA_PROD,OLD.CANTIDAD_PROD_COMPRADO,OLD.SUB_TOTAL_PROD_COMPRADO,
     OLD.ID_COMPRA_FK_DET_COMPRA_PROD,OLD.ID_PROD_FK_DET_COMPRA_PROD,OLD.ESTADO_DET_COMPRA_PROD,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_PRODUCCION
AFTER UPDATE ON PRODUCCION
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_PRODUCCION
    (T_A_ID_PRODUCCION,T_A_NOMBRE_PRODUCCION,T_A_CANT_PRODUCCION,T_A_DESCRIPCION_PRODUCCION,
     T_A_ID_PRODUCTO_FK_PRODUCCION,T_A_ID_USUARIO_FK_PRODUCCION,T_A_ESTADO_PRODUCCION,
     FECHA_ACTUALIZACION_PRODUCCION)
    VALUES (OLD.ID_PRODUCCION,OLD.NOMBRE_PRODUCCION,OLD.CANT_PRODUCCION,OLD.DESCRIPCION_PRODUCCION,
     OLD.ID_PRODUCTO_FK_PRODUCCION,OLD.ID_USUARIO_FK_PRODUCCION,OLD.ESTADO_PRODUCCION,NOW());
END $

CREATE TRIGGER TRIGGER_ACTUALIZAR_DETALLE_PRODUCCION
AFTER UPDATE ON DETALLE_PRODUCCION
FOR EACH ROW
BEGIN
    INSERT INTO ACCION_ACTUALIZAR_DETALLE_PRODUCCION
    (T_A_ID_DETALLE_PRODUCCION,T_A_ID_PRODUCCION,T_A_ID_MATERIA_PRIMA,T_A_CANTIDAD_REQUERIDA,
     T_A_CANTIDAD_USADA,FECHA_ACTUALIZACION_DETALLE_PRODUCCION)
    VALUES (OLD.ID_DETALLE_PRODUCCION,OLD.ID_PRODUCCION,OLD.ID_MATERIA_PRIMA,OLD.CANTIDAD_REQUERIDA,
     OLD.CANTIDAD_USADA,NOW());
END $


