DELIMITER $$

CREATE TRIGGER TR_RESTAR_STOCK_DESPUES_VENTA
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    UPDATE PRODUCTO
    SET CANT_EXIST_PRODUCTO = CANT_EXIST_PRODUCTO - NEW.CANTIDAD
    WHERE ID_PRODUCTO = NEW.ID_PRODUCTO_FK_DET_VENTA;
END$$

DELIMITER $$
CREATE TRIGGER TR_SUMAR_STOCK_MATERIA_PRIMA
AFTER INSERT ON DETALLE_COMPRA_MATERIA_PRIMA
FOR EACH ROW
BEGIN
    UPDATE MATERIA_PRIMA
    SET CANTIDAD_EXIST_MATERIA_PRIMA = CANTIDAD_EXIST_MATERIA_PRIMA + NEW.CANTIDAD_MAT_PRIMA_COMPRADA
    WHERE ID_MATERIA_PRIMA = NEW.ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA;
END$$

DELIMITER $$
CREATE TRIGGER TR_SUMAR_STOCK_PRODUCTO
AFTER INSERT ON DETALLE_COMPRA_PRODUCTO
FOR EACH ROW
BEGIN
    UPDATE PRODUCTO
    SET CANT_EXIST_PRODUCTO = CANT_EXIST_PRODUCTO + NEW.CANTIDAD_PROD_COMPRADO
    WHERE ID_PRODUCTO = NEW.ID_PROD_FK_DET_COMPRA_PROD;
END$$


CREATE TRIGGER TR_RESTAR_MAT_PRIMA_PRODUC
AFTER INSERT ON DETALLE_PRODUCCION
FOR EACH ROW
BEGIN
    UPDATE MATERIA_PRIMA
    SET CANTIDAD_EXIST_MATERIA_PRIMA = CANTIDAD_EXIST_MATERIA_PRIMA - NEW.CANTIDAD_REQUERIDA
    WHERE ID_MATERIA_PRIMA = NEW.ID_MATERIA_PRIMA_FK_DET_PRODUC;
END;


CREATE TRIGGER TR_SUMAR_PROD_PRODUC_ESTADO_FINISH
AFTER UPDATE ON PRODUCCION
FOR EACH ROW
BEGIN
    IF NEW.ESTADO_PRODUCCION = 'FINALIZADA' AND OLD.ESTADO_PRODUCCION <> 'FINALIZADA' THEN
        UPDATE PRODUCTO
        SET CANT_EXIST_PRODUCTO = CANT_EXIST_PRODUCTO + NEW.CANT_PRODUCCION
        WHERE ID_PRODUCTO = NEW.ID_PRODUCTO_FK_PRODUCCION;
    END IF;
END;