USE PROYECTO_WYK;

-- ============================================================
-- 1. VISTAS BÁSICAS
-- ============================================================

CREATE OR REPLACE VIEW VW_ROLES AS
SELECT ID_ROL, ROL, ESTADO_ROL
FROM ROL
WHERE ESTADO_ROL = TRUE;

CREATE OR REPLACE VIEW VW_USUARIOS AS
SELECT ID_USUARIO, NUM_DOC, NOMBRE, TEL_USUARIO, EMAIL_USUARIO, ID_ROL
FROM USUARIO;

CREATE OR REPLACE VIEW VW_PRODUCTOS AS
SELECT ID_PRODUCTO, NOMBRE_PRODUCTO, STOCK_PRODUCTO, PRECIO_PRODUCTO, ESTADO_PRODUCTO
FROM PRODUCTO
WHERE ESTADO_PRODUCTO = TRUE;

CREATE OR REPLACE VIEW VW_MATERIAS_PRIMAS AS
SELECT ID_MATERIA, NOMBRE_MATERIA, STOCK_MATERIA, COSTO_MATERIA, ESTADO_MATERIA
FROM MATERIA_PRIMA
WHERE ESTADO_MATERIA = TRUE;

CREATE OR REPLACE VIEW VW_EMPLEADOS AS
SELECT E.ID_EMPLEADO, E.NOMBRE_EMPLEADO, C.NOMBRE_CARGO, E.ESTADO_EMPLEADO
FROM EMPLEADO E
JOIN CARGO C ON E.ID_CARGO = C.ID_CARGO;

CREATE OR REPLACE VIEW VW_TAREAS AS
SELECT ID_TAREA, DESCRIPCION, ESTADO_TAREA, ID_EMPLEADO
FROM TAREA;

CREATE OR REPLACE VIEW VW_VENTAS AS
SELECT ID_FACTURA_VENTA, FECHA_FACTURA_VENTA, ESTADO_FACTURA_VENTA, ID_EMPLEADO
FROM FACTURA_VENTA;

CREATE OR REPLACE VIEW VW_COMPRAS AS
SELECT ID_FACTURA_COMPRA, FECHA_FACTURA_COMPRA, ESTADO_FACTURA_COMPRA, ID_EMPLEADO
FROM FACTURA_COMPRA;

-- ============================================================
-- 2. VISTAS MULTITABLA
-- ============================================================

CREATE OR REPLACE VIEW VW_USUARIOS_ROL AS
SELECT U.ID_USUARIO, U.NOMBRE, U.EMAIL_USUARIO, R.ROL, R.ESTADO_ROL
FROM USUARIO U
JOIN ROL R ON U.ID_ROL = R.ID_ROL;

CREATE OR REPLACE VIEW VW_VENTAS_DETALLE_EMPLEADO AS
SELECT FV.ID_FACTURA_VENTA, FV.FECHA_FACTURA_VENTA, 
       E.NOMBRE_EMPLEADO,
       P.NOMBRE_PRODUCTO, DV.CANTIDAD, DV.PRECIO_UNITARIO, 
       (DV.CANTIDAD * DV.PRECIO_UNITARIO) AS SUBTOTAL
FROM DETALLE_FACTURA_VENTA DV
JOIN FACTURA_VENTA FV ON DV.ID_FACTURA_VENTA = FV.ID_FACTURA_VENTA
JOIN PRODUCTO P ON DV.ID_PRODUCTO = P.ID_PRODUCTO
JOIN EMPLEADO E ON FV.ID_EMPLEADO = E.ID_EMPLEADO;

CREATE OR REPLACE VIEW VW_COMPRAS_DETALLE AS
SELECT FC.ID_FACTURA_COMPRA, FC.FECHA_FACTURA_COMPRA,
       MP.NOMBRE_MATERIA, DC.CANTIDAD, DC.COSTO_UNITARIO,
       (DC.CANTIDAD * DC.COSTO_UNITARIO) AS TOTAL_COMPRA,
       E.NOMBRE_EMPLEADO
FROM DETALLE_FACTURA_COMPRA DC
JOIN FACTURA_COMPRA FC ON DC.ID_FACTURA_COMPRA = FC.ID_FACTURA_COMPRA
JOIN MATERIA_PRIMA MP ON DC.ID_MATERIA = MP.ID_MATERIA
JOIN EMPLEADO E ON FC.ID_EMPLEADO = E.ID_EMPLEADO;

CREATE OR REPLACE VIEW VW_PRODUCCION_DETALLE AS
SELECT PR.ID_PRODUCCION, PR.FECHA_PRODUCCION,
       P.NOMBRE_PRODUCTO, MP.NOMBRE_MATERIA,
       DP.CANTIDAD_MATERIA, DP.CANTIDAD_PRODUCTO
FROM PRODUCCION PR
JOIN DETALLE_PRODUCCION DP ON PR.ID_PRODUCCION = DP.ID_PRODUCCION
JOIN PRODUCTO P ON DP.ID_PRODUCTO = P.ID_PRODUCTO
JOIN MATERIA_PRIMA MP ON DP.ID_MATERIA = MP.ID_MATERIA;

CREATE OR REPLACE VIEW VW_INVENTARIO_GENERAL AS
SELECT 'PRODUCTO' AS TIPO, ID_PRODUCTO AS ID, NOMBRE_PRODUCTO AS NOMBRE, STOCK_PRODUCTO AS STOCK
FROM PRODUCTO
UNION
SELECT 'MATERIA_PRIMA' AS TIPO, ID_MATERIA, NOMBRE_MATERIA, STOCK_MATERIA
FROM MATERIA_PRIMA;

CREATE OR REPLACE VIEW VW_TAREAS_EMPLEADO AS
SELECT T.ID_TAREA, T.DESCRIPCION, T.ESTADO_TAREA, 
       E.NOMBRE_EMPLEADO, C.NOMBRE_CARGO
FROM TAREA T
JOIN EMPLEADO E ON T.ID_EMPLEADO = E.ID_EMPLEADO
JOIN CARGO C ON E.ID_CARGO = C.ID_CARGO;

-- ============================================================
-- 3. VISTAS RESUMEN / ANALÍTICAS
-- ============================================================

CREATE OR REPLACE VIEW VW_VENTAS_DIARIAS AS
SELECT DATE(FECHA_FACTURA_VENTA) AS FECHA, SUM(DV.CANTIDAD * DV.PRECIO_UNITARIO) AS TOTAL_VENTA
FROM DETALLE_FACTURA_VENTA DV
JOIN FACTURA_VENTA FV ON DV.ID_FACTURA_VENTA = FV.ID_FACTURA_VENTA
GROUP BY DATE(FECHA_FACTURA_VENTA);

CREATE OR REPLACE VIEW VW_TOP_PRODUCTOS AS
SELECT P.NOMBRE_PRODUCTO, SUM(DV.CANTIDAD) AS TOTAL_VENDIDO
FROM DETALLE_FACTURA_VENTA DV
JOIN PRODUCTO P ON DV.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY P.NOMBRE_PRODUCTO
ORDER BY TOTAL_VENDIDO DESC;

CREATE OR REPLACE VIEW VW_COMPRAS_MATERIA_PRIMA AS
SELECT MP.NOMBRE_MATERIA, SUM(DC.CANTIDAD * DC.COSTO_UNITARIO) AS TOTAL_COMPRADO
FROM DETALLE_FACTURA_COMPRA DC
JOIN MATERIA_PRIMA MP ON DC.ID_MATERIA = MP.ID_MATERIA
GROUP BY MP.NOMBRE_MATERIA;

CREATE OR REPLACE VIEW VW_TAREAS_PENDIENTES AS
SELECT E.NOMBRE_EMPLEADO, COUNT(*) AS TOTAL_PENDIENTES
FROM TAREA T
JOIN EMPLEADO E ON T.ID_EMPLEADO = E.ID_EMPLEADO
WHERE T.ESTADO_TAREA = 'PENDIENTE'
GROUP BY E.NOMBRE_EMPLEADO;

-- ============================================================
-- 1. VERIFICAR VISTAS BÁSICAS
-- ============================================================
SELECT * FROM VW_ROLES;
SELECT * FROM VW_USUARIOS;
SELECT * FROM VW_PRODUCTOS;
SELECT * FROM VW_MATERIAS_PRIMAS;
SELECT * FROM VW_EMPLEADOS;
SELECT * FROM VW_TAREAS;
SELECT * FROM VW_VENTAS;
SELECT * FROM VW_COMPRAS;

-- ============================================================
-- 2. VERIFICAR VISTAS MULTITABLA
-- ============================================================
SELECT * FROM VW_USUARIOS_ROL;
SELECT * FROM VW_VENTAS_DETALLE_EMPLEADO;
SELECT * FROM VW_COMPRAS_DETALLE;
SELECT * FROM VW_PRODUCCION_DETALLE;
SELECT * FROM VW_INVENTARIO_GENERAL;
SELECT * FROM VW_TAREAS_EMPLEADO;

-- ============================================================
-- 3. VERIFICAR VISTAS RESUMEN / ANALÍTICAS
-- ============================================================
SELECT * FROM VW_VENTAS_DIARIAS;
SELECT * FROM VW_TOP_PRODUCTOS;
SELECT * FROM VW_COMPRAS_MATERIA_PRIMA;
SELECT * FROM VW_TAREAS_PENDIENTES;

-- ============================================================
-- 4. PRUEBAS ADICIONALES (ya predefinidas en tu script)
-- ============================================================

-- Top 5 productos más vendidos
SELECT * FROM VW_TOP_PRODUCTOS LIMIT 5;

-- Ventas diarias (últimos 7 días)
SELECT * FROM VW_VENTAS_DIARIAS WHERE FECHA >= DATE_SUB(CURDATE(), INTERVAL 7 DAY);

-- Tareas pendientes por empleado
SELECT * FROM VW_TAREAS_PENDIENTES;

-- Inventario general
SELECT * FROM VW_INVENTARIO_GENERAL;


