USE PROYECTO_WYK;

-- ============================================================
-- 1. VISTAS BÁSICAS
-- ============================================================

CREATE OR REPLACE VIEW VW_ROLES AS
SELECT ID_ROL, ROL, CLASIFICACION, ESTADO_ROL
FROM ROL
WHERE ESTADO_ROL = TRUE;

CREATE OR REPLACE VIEW VW_USUARIOS AS
SELECT ID_USUARIO, NUM_DOC, NOMBRE, TEL_USUARIO, EMAIL_USUARIO, ROL_FK_USUARIO, ESTADO_USUARIO
FROM USUARIO;

CREATE OR REPLACE VIEW VW_PRODUCTOS AS
SELECT ID_PRODUCTO, NOMBRE_PRODUCTO, 
       CANT_EXIST_PRODUCTO AS STOCK_PRODUCTO, 
       VALOR_UNITARIO_PRODUCTO AS PRECIO_PRODUCTO, 
       ESTADO_PRODUCTO
FROM PRODUCTO
WHERE ESTADO_PRODUCTO = TRUE;

CREATE OR REPLACE VIEW VW_MATERIAS_PRIMAS AS
SELECT ID_MATERIA_PRIMA, NOMBRE_MATERIA_PRIMA, 
       CANTIDAD_EXIST_MATERIA_PRIMA AS STOCK_MATERIA, 
       VALOR_UNITARIO_MAT_PRIMA AS COSTO_MATERIA, 
       ESTADO_MATERIA_PRIMA
FROM MATERIA_PRIMA
WHERE ESTADO_MATERIA_PRIMA = TRUE;

CREATE OR REPLACE VIEW VW_TAREAS AS
SELECT ID_TAREA, TAREA, CATEGORIA, DESCRIPCION, ESTADO_TAREA, 
       USUARIO_ASIGNADO_FK AS ID_USUARIO_ASIGNADO, 
       USUARIO_CREADOR_FK AS ID_USUARIO_CREADOR
FROM TAREA;

CREATE OR REPLACE VIEW VW_VENTAS AS
SELECT ID_VENTA, FECHA_HORA_VENTA, TOTAL_VENTA, ESTADO_PEDIDO, ESTADO_PAGO, ID_USUARIO_FK_VENTA
FROM VENTA;

CREATE OR REPLACE VIEW VW_COMPRAS AS
SELECT ID_COMPRA, FECHA_HORA_COMPRA, TOTAL_COMPRA, NOMBRE_PROVEEDOR, ESTADO_FACTURA_COMPRA, ID_USUARIO_FK_COMPRA
FROM COMPRA;

-- ============================================================
-- 2. VISTAS MULTITABLA
-- ============================================================

CREATE OR REPLACE VIEW VW_USUARIOS_ROL AS
SELECT U.ID_USUARIO, U.NOMBRE, U.EMAIL_USUARIO, R.ROL, R.CLASIFICACION, R.ESTADO_ROL
FROM USUARIO U
JOIN ROL R ON U.ROL_FK_USUARIO = R.ID_ROL;

CREATE OR REPLACE VIEW VW_VENTAS_DETALLE_USUARIO AS
SELECT V.ID_VENTA, V.FECHA_HORA_VENTA, U.NOMBRE AS USUARIO, 
       P.NOMBRE_PRODUCTO, DV.CANTIDAD, P.VALOR_UNITARIO_PRODUCTO, 
       (DV.CANTIDAD * P.VALOR_UNITARIO_PRODUCTO) AS SUBTOTAL
FROM DETALLE_VENTA DV
JOIN VENTA V ON DV.ID_VENTA_FK_DET_VENTA = V.ID_VENTA
JOIN PRODUCTO P ON DV.ID_PRODUCTO_FK_DET_VENTA = P.ID_PRODUCTO
JOIN USUARIO U ON V.ID_USUARIO_FK_VENTA = U.ID_USUARIO;

CREATE OR REPLACE VIEW VW_COMPRAS_DETALLE AS
SELECT C.ID_COMPRA, C.FECHA_HORA_COMPRA, C.NOMBRE_PROVEEDOR, 
       'MATERIA_PRIMA' AS TIPO, MP.NOMBRE_MATERIA_PRIMA, DCM.CANTIDAD_MAT_PRIMA_COMPRADA AS CANTIDAD, DCM.SUB_TOTAL_MAT_PRIMA_COMPRADA AS SUBTOTAL
FROM DETALLE_COMPRA_MATERIA_PRIMA DCM
JOIN COMPRA C ON DCM.ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA = C.ID_COMPRA
JOIN MATERIA_PRIMA MP ON DCM.ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA = MP.ID_MATERIA_PRIMA
UNION
SELECT C.ID_COMPRA, C.FECHA_HORA_COMPRA, C.NOMBRE_PROVEEDOR,
       'PRODUCTO' AS TIPO, P.NOMBRE_PRODUCTO, DCP.CANTIDAD_PROD_COMPRADO AS CANTIDAD, DCP.SUB_TOTAL_PROD_COMPRADO AS SUBTOTAL
FROM DETALLE_COMPRA_PRODUCTO DCP
JOIN COMPRA C ON DCP.ID_COMPRA_FK_DET_COMPRA_PROD = C.ID_COMPRA
JOIN PRODUCTO P ON DCP.ID_PROD_FK_DET_COMPRA_PROD = P.ID_PRODUCTO;

CREATE OR REPLACE VIEW VW_PRODUCCION_DETALLE AS
SELECT PR.ID_PRODUCCION, PR.NOMBRE_PRODUCCION, PR.CANT_PRODUCCION, 
       P.NOMBRE_PRODUCTO, MP.NOMBRE_MATERIA_PRIMA, DP.CANTIDAD_REQUERIDA
FROM PRODUCCION PR
JOIN DETALLE_PRODUCCION DP ON PR.ID_PRODUCCION = DP.ID_PRODUCCION_FK_DET_PRODUC
JOIN PRODUCTO P ON PR.ID_PRODUCTO_FK_PRODUCCION = P.ID_PRODUCTO
JOIN MATERIA_PRIMA MP ON DP.ID_MATERIA_PRIMA_FK_DET_PRODUC = MP.ID_MATERIA_PRIMA;

CREATE OR REPLACE VIEW VW_INVENTARIO_GENERAL AS
SELECT 'PRODUCTO' AS TIPO, ID_PRODUCTO AS ID, NOMBRE_PRODUCTO AS NOMBRE, CANT_EXIST_PRODUCTO AS STOCK
FROM PRODUCTO
UNION
SELECT 'MATERIA_PRIMA' AS TIPO, ID_MATERIA_PRIMA, NOMBRE_MATERIA_PRIMA, CANTIDAD_EXIST_MATERIA_PRIMA
FROM MATERIA_PRIMA;

-- ============================================================
-- 3. VISTAS RESUMEN / ANALÍTICAS
-- ============================================================

CREATE OR REPLACE VIEW VW_VENTAS_DIARIAS AS
SELECT DATE(V.FECHA_HORA_VENTA) AS FECHA, SUM(DV.CANTIDAD * P.VALOR_UNITARIO_PRODUCTO) AS TOTAL_VENTA
FROM DETALLE_VENTA DV
JOIN VENTA V ON DV.ID_VENTA_FK_DET_VENTA = V.ID_VENTA
JOIN PRODUCTO P ON DV.ID_PRODUCTO_FK_DET_VENTA = P.ID_PRODUCTO
GROUP BY DATE(V.FECHA_HORA_VENTA);

CREATE OR REPLACE VIEW VW_TOP_PRODUCTOS AS
SELECT P.NOMBRE_PRODUCTO, SUM(DV.CANTIDAD) AS TOTAL_VENDIDO
FROM DETALLE_VENTA DV
JOIN PRODUCTO P ON DV.ID_PRODUCTO_FK_DET_VENTA = P.ID_PRODUCTO
GROUP BY P.NOMBRE_PRODUCTO
ORDER BY TOTAL_VENDIDO DESC;

CREATE OR REPLACE VIEW VW_COMPRAS_MATERIA_PRIMA AS
SELECT MP.NOMBRE_MATERIA_PRIMA, SUM(DCM.SUB_TOTAL_MAT_PRIMA_COMPRADA) AS TOTAL_COMPRADO
FROM DETALLE_COMPRA_MATERIA_PRIMA DCM
JOIN MATERIA_PRIMA MP ON DCM.ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA = MP.ID_MATERIA_PRIMA
GROUP BY MP.NOMBRE_MATERIA_PRIMA;

CREATE OR REPLACE VIEW VW_TAREAS_PENDIENTES AS
SELECT U.NOMBRE AS USUARIO, COUNT(*) AS TOTAL_PENDIENTES
FROM TAREA T
JOIN USUARIO U ON T.USUARIO_ASIGNADO_FK = U.ID_USUARIO
WHERE T.ESTADO_TAREA = 'PENDIENTE'
GROUP BY U.NOMBRE;

-- ============================================================
-- 1. VERIFICAR VISTAS BÁSICAS
-- ============================================================
SELECT * FROM VW_ROLES;
SELECT * FROM VW_USUARIOS;
SELECT * FROM VW_PRODUCTOS;
SELECT * FROM VW_MATERIAS_PRIMAS;
SELECT * FROM VW_TAREAS;
SELECT * FROM VW_VENTAS;
SELECT * FROM VW_COMPRAS;

-- ============================================================
-- 2. VERIFICAR VISTAS MULTITABLA
-- ============================================================
SELECT * FROM VW_USUARIOS_ROL;
SELECT * FROM VW_VENTAS_DETALLE_USUARIO;
SELECT * FROM VW_COMPRAS_DETALLE;
SELECT * FROM VW_PRODUCCION_DETALLE;
SELECT * FROM VW_INVENTARIO_GENERAL;

-- ============================================================
-- 3. VERIFICAR VISTAS RESUMEN / ANALÍTICAS
-- ============================================================
SELECT * FROM VW_VENTAS_DIARIAS;
SELECT * FROM VW_TOP_PRODUCTOS;
SELECT * FROM VW_COMPRAS_MATERIA_PRIMA;
SELECT * FROM VW_TAREAS_PENDIENTES;

-- ============================================================
-- 4. PRUEBAS ADICIONALES
-- ============================================================

-- Top 5 productos más vendidos
SELECT * FROM VW_TOP_PRODUCTOS LIMIT 5;

-- Ventas diarias (últimos 7 días)
SELECT * FROM VW_VENTAS_DIARIAS 
WHERE FECHA >= DATE_SUB(CURDATE(), INTERVAL 7 DAY);

-- Tareas pendientes por usuario
SELECT * FROM VW_TAREAS_PENDIENTES;

-- Inventario general
SELECT * FROM VW_INVENTARIO_GENERAL;


