CREATE DATABASE PROYECTO_WYK;
USE PROYECTO_WYK;

CREATE TABLE ROL
(
    ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
    ROL VARCHAR(50) NOT NULL,
    CLASIFICACION ENUM('EMPLEADO','ADMINISTRADOR') NOT NULL,
    ESTADO_ROL BOOLEAN NOT NULL
);

CREATE TABLE USUARIO 
(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NUM_DOC BIGINT UNIQUE NOT NULL,
    NOMBRE VARCHAR (50) NOT NULL,
    PASSWORD_USUARIO VARCHAR (150) NOT NULL,
    TEL_USUARIO BIGINT NOT NULL,
    EMAIL_USUARIO VARCHAR(50) UNIQUE NOT NULL,
    FECHA_REGISTRO DATETIME NOT NULL,
    ROL_FK_USUARIO INT NOT NULL,
    CONSTRAINT ROL_FK_USUARIO FOREIGN KEY (ROL_FK_USUARIO) REFERENCES ROL (ID_ROL),
    ESTADO_USUARIO BOOLEAN NOT NULL
);

CREATE TABLE TAREA
(
	ID_TAREA  INT PRIMARY KEY AUTO_INCREMENT,
    TAREA VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(80) NOT NULL,
    DESCRIPCION VARCHAR(250) NULL,
    TIEMPO_ESTIMADO_HORAS FLOAT NOT NULL,
    PRIORIDAD ENUM( 'BAJA', 'MEDIA', 'ALTA'),
    ESTADO_TAREA ENUM('PENDIENTE', 'COMPLETADA', 'CANCELADA'),
    USUARIO_ASIGNADO_FK INT NOT NULL,
    CONSTRAINT USUARIO_ASIGNADO_FK FOREIGN KEY(USUARIO_ASIGNADO_FK) REFERENCES USUARIO (ID_USUARIO),
    USUARIO_CREADOR_FK INT NOT NULL,
    CONSTRAINT USUARIO_CREADOR_FK FOREIGN KEY(USUARIO_CREADOR_FK) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PRODUCTO
(
	ID_PRODUCTO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(50) UNIQUE NOT NULL,
	VALOR_UNITARIO_PRODUCTO BIGINT NOT NULL,
	CANT_EXIST_PRODUCTO BIGINT NOT NULL,
	FECHA_VENCIMIENTO_PRODUCTO DATE NOT NULL,
	TIPO_PRODUCTO ENUM('PANADERIA', 'PASTELERIA', 'ASEO') NOT NULL,
	ID_USUARIO_FK_PRODUCTO INT NOT NULL,
	CONSTRAINT ID_USUARIO_FK_PRODUCTO FOREIGN KEY (ID_USUARIO_FK_PRODUCTO) REFERENCES USUARIO (ID_USUARIO),
	ESTADO_PRODUCTO BOOLEAN NOT NULL
);

CREATE TABLE VENTA (
    ID_VENTA BIGINT PRIMARY KEY AUTO_INCREMENT,
    FECHA_HORA_VENTA DATETIME NOT NULL,
    TOTAL_VENTA BIGINT NOT NULL,
    NUMERO_MESA INT NULL,
    DESCRIPCION VARCHAR(200) NULL,
	ID_USUARIO_FK_VENTA INT NOT NULL,
    CONSTRAINT ID_USUARIO_FK_VENTA FOREIGN KEY (ID_USUARIO_FK_VENTA) REFERENCES USUARIO (ID_USUARIO),
    ESTADO_PEDIDO ENUM('PENDIENTE', 'PREPARANDO', 'ENTREGADO', 'CANCELADO') NOT NULL,
    ESTADO_PAGO ENUM('PENDIENTE', 'PAGADA', 'CANCELADA') NOT NULL
);

CREATE TABLE DETALLE_VENTA (
    ID_DETALLE_VENTA INT PRIMARY KEY AUTO_INCREMENT,
    CANTIDAD BIGINT NOT NULL,
    SUB_TOTAL BIGINT NOT NULL,
    ID_VENTA_FK_DET_VENTA BIGINT NOT NULL,
    CONSTRAINT ID_VENTA_FK_DET_VENTA FOREIGN KEY (ID_VENTA_FK_DET_VENTA) REFERENCES VENTA (ID_VENTA),
    ID_PRODUCTO_FK_DET_VENTA BIGINT NOT NULL,
    CONSTRAINT ID_PRODUCTO_FK_DET_VENTA FOREIGN KEY (ID_PRODUCTO_FK_DET_VENTA) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE AJUSTE_INVENTARIO (
    ID_AJUSTE INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_AJUSTE DATETIME NOT NULL,
    TIPO_AJUSTE ENUM('DAÑADO', 'ROBO', 'PERDIDA', 'CADUCADO', 'MUESTRA') NOT NULL,
    CANTIDAD_AJUSTADA INT NOT NULL,
    DESCRIPCION VARCHAR(200) NULL,
    ID_PROD_FK_AJUSTE_INVENTARIO BIGINT NOT NULL,
    CONSTRAINT ID_PROD_FK_AJUSTE_INVENTARIO FOREIGN KEY (ID_PROD_FK_AJUSTE_INVENTARIO) REFERENCES PRODUCTO (ID_PRODUCTO),
    ID_USUARIO_FK_AJUSTE_INVENTARIO INT NOT NULL,
	CONSTRAINT ID_USUARIO_FK_AJUSTE_INVENTARIO FOREIGN KEY (ID_USUARIO_FK_AJUSTE_INVENTARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE MATERIA_PRIMA
(
	ID_MATERIA_PRIMA BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_MATERIA_PRIMA VARCHAR (50) NOT NULL,
    VALOR_UNITARIO_MAT_PRIMA BIGINT NOT NULL,
	FECHA_VENCIMIENTO_MATERIA_PRIMA DATE NOT NULL,
	CANTIDAD_EXIST_MATERIA_PRIMA BIGINT NOT NULL,
	PRESENTACION_MATERIA_PRIMA VARCHAR (50) NOT NULL,
	DESCRIPCION_MATERIA_PRIMA VARCHAR(200) NOT NULL,
	ID_USUARIO_FK_MATERIA_PRIMA INT NOT NULL,
	CONSTRAINT ID_USUARIO_FK_MATERIA_PRIMA FOREIGN KEY (ID_USUARIO_FK_MATERIA_PRIMA) REFERENCES USUARIO (ID_USUARIO),
	ESTADO_MATERIA_PRIMA BOOLEAN NOT NULL
);

CREATE TABLE COMPRA
(
	ID_COMPRA BIGINT PRIMARY KEY AUTO_INCREMENT,
	FECHA_HORA_COMPRA DATETIME NOT NULL,
    TIPO ENUM('MATERIA PRIMA', 'PRODUCTO TERMINADO'),
	TOTAL_COMPRA BIGINT NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(50) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    TEL_PROVEEDOR BIGINT UNIQUE NOT NULL,
	EMAIL_PROVEEDOR VARCHAR(50) UNIQUE NOT NULL,
	DESCRIPCION_COMPRA VARCHAR(200) NULL,
	ID_USUARIO_FK_COMPRA INT NOT NULL,
	CONSTRAINT ID_USUARIO_FK_COMPRA FOREIGN KEY (ID_USUARIO_FK_COMPRA) REFERENCES USUARIO (ID_USUARIO),
	ESTADO_FACTURA_COMPRA ENUM('PENDIENTE', 'PAGADA', 'CANCELADA') NOT NULL
);

CREATE TABLE DETALLE_COMPRA_MATERIA_PRIMA
(
	ID_DET_COMPRA_MAT_PRIM INT PRIMARY KEY AUTO_INCREMENT,
	CANTIDAD_MAT_PRIMA_COMPRADA BIGINT NOT NULL,
	SUB_TOTAL_MAT_PRIMA_COMPRADA BIGINT NOT NULL,
	ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA BIGINT NOT NULL,
	CONSTRAINT ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA FOREIGN KEY (ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA) REFERENCES COMPRA (ID_COMPRA),
	ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA BIGINT NOT NULL,
	CONSTRAINT ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA FOREIGN KEY (ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA),
	ESTADO_DET_COMPRA_MAT_PRIMA BOOLEAN NOT NULL
);

CREATE TABLE DETALLE_COMPRA_PRODUCTO
(
	ID_DET_COMPRA_PROD INT PRIMARY KEY AUTO_INCREMENT,
	CANTIDAD_PROD_COMPRADO BIGINT NOT NULL,
	SUB_TOTAL_PROD_COMPRADO BIGINT NOT NULL,
	ID_COMPRA_FK_DET_COMPRA_PROD BIGINT NOT NULL,
	CONSTRAINT ID_COMPRA_FK_DET_COMPRA_PROD FOREIGN KEY (ID_COMPRA_FK_DET_COMPRA_PROD) REFERENCES COMPRA (ID_COMPRA),
	ID_PROD_FK_DET_COMPRA_PROD BIGINT NOT NULL,
	CONSTRAINT ID_PROD_FK_DET_COMPRA_PROD FOREIGN KEY (ID_PROD_FK_DET_COMPRA_PROD) REFERENCES PRODUCTO (ID_PRODUCTO),
	ESTADO_DET_COMPRA_PROD BOOLEAN NOT NULL
);

CREATE TABLE PRODUCCION
(
	ID_PRODUCCION BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_PRODUCCION VARCHAR (50) NOT NULL,
	CANT_PRODUCCION BIGINT NOT NULL,
	DESCRIPCION_PRODUCCION VARCHAR(200) NOT NULL,
	ID_PRODUCTO_FK_PRODUCCION BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_PRODUCCION FOREIGN KEY (ID_PRODUCTO_FK_PRODUCCION) REFERENCES PRODUCTO (ID_PRODUCTO),
	ID_USUARIO_FK_PRODUCCION INT NOT NULL,
	CONSTRAINT ID_USUARIO_FK_PRODUCCION FOREIGN KEY (ID_USUARIO_FK_PRODUCCION) REFERENCES USUARIO (ID_USUARIO),
	ESTADO_PRODUCCION BOOLEAN NOT NULL
);

CREATE TABLE DETALLE_PRODUCCION
(
    ID_DETALLE_PRODUCCION BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCCION BIGINT NOT NULL,
    ID_MATERIA_PRIMA BIGINT NOT NULL,
    CANTIDAD_REQUERIDA DECIMAL(10,2) NOT NULL,
    CANTIDAD_USADA DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_DET_PROD_PRODUCCION FOREIGN KEY (ID_PRODUCCION) REFERENCES PRODUCCION(ID_PRODUCCION),
    CONSTRAINT FK_DET_PROD_MATERIA FOREIGN KEY (ID_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA(ID_MATERIA_PRIMA)
);
