USE PROYECTO_WYK;

														/*TRIGGERS DE INSERTAR*/
    
                                                        /*👮‍TRIGGER INSERTAR CARGO👮‍*/ 
                                                        
CREATE TABLE T_INSERTAR_CARGO
(ID_INSERT_CARGO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ACCION_INSERT_CARGO VARCHAR (200) NOT NULL,
FECHA_EJECUTO_INSERT_CARGO DATETIME NOT NULL);

DELIMITER $
CREATE TRIGGER TRIGGER_INSERTAR_CARGO
AFTER INSERT ON CARGO
FOR EACH ROW
BEGIN
	INSERT INTO T_INSERTAR_CARGO (ACCION_INSERT_CARGO,FECHA_EJECUTO_INSERT_CARGO)
	VALUES ('SE INSERTO CORRECTAMENTE', NOW());
END $

INSERT INTO CARGO (NOMBRE_CARGO,ESTADO_CARGO)
VALUES ('DOMESTICO',1);

SELECT * FROM T_INSERTAR_CARGO;

														/*👩‍🍳TRIGGER INSERTAR EMPLEADO👨‍🍳*/

CREATE TABLE T_INSERTAR_EMPLEADO
(ID_INSERT_EMPLEADO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ACCION_INSERT_EMPLEADO VARCHAR (200) NOT NULL,
FECHA_EJECUTO_INSERT_EMPLEADO DATETIME NOT NULL);

DELIMITER $
CREATE TRIGGER TRIGGER_INSERTAR_EMPLEADO
AFTER INSERT ON EMPLEADO
FOR EACH ROW
BEGIN
	INSERT INTO T_INSERTAR_EMPLEADO (ACCION_INSERT_EMPLEADO,FECHA_EJECUTO_INSERT_EMPLEADO)
	VALUES ('SE INSERTO CORRECTAMENTE', NOW());
END $

INSERT INTO EMPLEADO (CC_ENPLEADO,NOMBRE_ENPLEADO,RH_EMPLEADO,TEL_EMPLEADO,ENAIL_EMPLEADO,ID_CARGO_FK_EMPLEADO,ESTADO_EMPLEADO)
VALUES (1006006006,'Juan Forero','O+',3015202833,'juanw@gmail.com',5,1);

SELECT * FROM T_INSERTAR_EMPLEADO;        

														/*👦TRIGGER INSERTAR CLIENTE👦*/ 
                                                        
CREATE TABLE T_INSERTAR_CLIENTE
(ID_INSERT_CLIENTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ACCION_INSERT_CLIENTE VARCHAR (200) NOT NULL,
FECHA_EJECUTO_INSERT_CLIENTE DATETIME NOT NULL);

DELIMITER $
CREATE TRIGGER TRIGGER_INSERTAR_CLIENTE
AFTER INSERT ON CLIENTE
FOR EACH ROW
BEGIN
	INSERT INTO T_INSERTAR_CLIENTE (ACCION_INSERT_CLIENTE,FECHA_EJECUTO_INSERT_CLIENTE)
	VALUES ('SE INSERTO CORRECTAMENTE', NOW());
END $

INSERT INTO CLIENTE (NUM_DOCUMENTO_CLIENTE,TIPO_DOCUMENTO_CLIENTE,NOMBRE_CLIENTE,TEL_CLIENTE,EMAIL_CLIENTE,ID_EMPLEADO_FK_CLIENTE,ESTADO_CLIENTE)
VALUES (3003003003,'TI','Andrea Florian',3132563434,'andre@gmail.com',5,1);

SELECT * FROM T_INSERTAR_CLIENTE;    

														/*🤴TRIGGER INSERTAR USUARIO👸*/  
                                                        
CREATE TABLE T_INSERTAR_USUARIO
(ID_INSERT_USUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ACCION_INSERT_USUARIO VARCHAR (200) NOT NULL,
FECHA_EJECUTO_INSERT_USUARIO DATETIME NOT NULL);

DELIMITER $
CREATE TRIGGER TRIGGER_INSERTAR_USUARIO
AFTER INSERT ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO T_INSERTAR_USUARIO (ACCION_INSERT_USUARIO,FECHA_EJECUTO_INSERT_USUARIO)
	VALUES ('SE INSERTO CORRECTAMENTE', NOW());
END $

INSERT INTO USUARIO (NOMBRE_USUARIO, CONTRASEÑA_USUARIO,FECHA_REGISTRO,FECHA_ULTIMA_SESION,ESTADO_USUARIO)
VALUES ('FOR.cajero','juan02540205', NOW(), NOW(), 1);

SELECT * FROM T_INSERTAR_USUARIO;     

														/*🤴TRIGGER INSERTAR USUARIO EMPLEADO👸*/ 
                                                        
                                                        

                                                        