USE PROYECTO_WYK;

CREATE TABLE T_ACTUALIZAR_ROL 
(
    ID_ACCION_ACTUALIZAR_ROL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_ROL INT NOT NULL,
    T_A_ROL VARCHAR(50) NOT NULL,
    T_A_CLASIFICACION ENUM('EMPLEADO','ADMINISTRADOR') NOT NULL,
    T_A_ESTADO_ROL BOOLEAN NOT NULL,
    FECHA_ACTUALIZACION_ROL DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_USUARIO 
(
    ID_ACCION_ACTUALIZAR_USUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_USUARIO INT NOT NULL,
    T_A_NUM_DOC BIGINT NOT NULL,
    T_A_NOMBRE VARCHAR(50) NOT NULL,
    T_A_PASSWORD_USUARIO VARCHAR(150) NOT NULL,
    T_A_TEL_USUARIO BIGINT NOT NULL,
    T_A_EMAIL_USUARIO VARCHAR(50) NOT NULL,
    T_A_FECHA_REGISTRO DATETIME NOT NULL,
    T_A_ROL_FK_USUARIO INT NOT NULL,
    T_A_ESTADO_USUARIO BOOLEAN NOT NULL,
    FECHA_ACTUALIZACION_USUARIO DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_TAREA 
(
    ID_ACCION_ACTUALIZAR_TAREA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_TAREA INT NOT NULL,
    T_A_TAREA VARCHAR(100) NOT NULL,
    T_A_CATEGORIA VARCHAR(80) NOT NULL,
    T_A_DESCRIPCION VARCHAR(250),
    T_A_TIEMPO_ESTIMADO_HORAS FLOAT NOT NULL,
    T_A_PRIORIDAD ENUM('BAJA','MEDIA','ALTA'),
    T_A_ESTADO_TAREA ENUM('PENDIENTE','COMPLETADA','CANCELADA'),
    T_A_USUARIO_ASIGNADO_FK INT NOT NULL,
    T_A_USUARIO_CREADOR_FK INT NOT NULL,
    FECHA_ACTUALIZACION_TAREA DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_PRODUCTO 
(
    ID_ACCION_ACTUALIZAR_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_PRODUCTO BIGINT NOT NULL,
    T_A_NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    T_A_VALOR_UNITARIO_PRODUCTO BIGINT NOT NULL,
    T_A_CANT_EXIST_PRODUCTO BIGINT NOT NULL,
    T_A_FECHA_VENCIMIENTO_PRODUCTO DATE NOT NULL,
    T_A_TIPO_PRODUCTO ENUM('PANADERIA','PASTELERIA','ASEO') NOT NULL,
    T_A_ID_USUARIO_FK_PRODUCTO INT NOT NULL,
    T_A_ESTADO_PRODUCTO BOOLEAN NOT NULL,
    FECHA_ACTUALIZACION_PRODUCTO DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_VENTA 
(
    ID_ACCION_ACTUALIZAR_VENTA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_VENTA BIGINT NOT NULL,
    T_A_FECHA_HORA_VENTA DATETIME NOT NULL,
    T_A_TOTAL_VENTA BIGINT NOT NULL,
    T_A_NUMERO_MESA INT,
    T_A_DESCRIPCION VARCHAR(200),
    T_A_ID_USUARIO_FK_VENTA INT NOT NULL,
    T_A_ESTADO_PEDIDO ENUM('PENDIENTE','PREPARANDO','ENTREGADO','CANCELADO') NOT NULL,
    T_A_ESTADO_PAGO ENUM('PENDIENTE','PAGADA','CANCELADA') NOT NULL,
    FECHA_ACTUALIZACION_VENTA DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_DETALLE_VENTA 
(
    ID_ACCION_ACTUALIZAR_DETALLE_VENTA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_DETALLE_VENTA INT NOT NULL,
    T_A_CANTIDAD BIGINT NOT NULL,
    T_A_SUB_TOTAL BIGINT NOT NULL,
    T_A_ID_VENTA_FK_DET_VENTA BIGINT NOT NULL,
    T_A_ID_PRODUCTO_FK_DET_VENTA BIGINT NOT NULL,
    FECHA_ACTUALIZACION_DETALLE_VENTA DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_AJUSTE_INVENTARIO 
(
    ID_ACCION_ACTUALIZAR_AJUSTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_AJUSTE INT NOT NULL,
    T_A_FECHA_AJUSTE DATETIME NOT NULL,
    T_A_TIPO_AJUSTE ENUM('DAÑADO','ROBO','PERDIDA','CADUCADO','MUESTRA') NOT NULL,
    T_A_CANTIDAD_AJUSTADA INT NOT NULL,
    T_A_DESCRIPCION VARCHAR(200),
    T_A_ID_PROD_FK_AJUSTE_INVENTARIO BIGINT NOT NULL,
    T_A_ID_USUARIO_FK_AJUSTE_INVENTARIO INT NOT NULL,
    FECHA_ACTUALIZACION_AJUSTE DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_MATERIA_PRIMA 
(
    ID_ACCION_ACTUALIZAR_MATERIA_PRIMA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_MATERIA_PRIMA BIGINT NOT NULL,
    T_A_NOMBRE_MATERIA_PRIMA VARCHAR(50) NOT NULL,
    T_A_VALOR_UNITARIO_MAT_PRIMA BIGINT NOT NULL,
    T_A_FECHA_VENCIMIENTO_MATERIA_PRIMA DATE NOT NULL,
    T_A_CANTIDAD_EXIST_MATERIA_PRIMA BIGINT NOT NULL,
    T_A_PRESENTACION_MATERIA_PRIMA VARCHAR(50) NOT NULL,
    T_A_DESCRIPCION_MATERIA_PRIMA VARCHAR(200) NOT NULL,
    T_A_ID_USUARIO_FK_MATERIA_PRIMA INT NOT NULL,
    T_A_ESTADO_MATERIA_PRIMA BOOLEAN NOT NULL,
    FECHA_ACTUALIZACION_MATERIA_PRIMA DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_COMPRA 
(
    ID_ACCION_ACTUALIZAR_COMPRA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_COMPRA BIGINT NOT NULL,
    T_A_FECHA_HORA_COMPRA DATETIME NOT NULL,
    T_A_TIPO ENUM('MATERIA PRIMA','PRODUCTO TERMINADO'),
    T_A_TOTAL_COMPRA BIGINT NOT NULL,
    T_A_NOMBRE_PROVEEDOR VARCHAR(50) NOT NULL,
    T_A_MARCA VARCHAR(50) NOT NULL,
    T_A_TEL_PROVEEDOR BIGINT NOT NULL,
    T_A_EMAIL_PROVEEDOR VARCHAR(50) NOT NULL,
    T_A_DESCRIPCION_COMPRA VARCHAR(200),
    T_A_ID_USUARIO_FK_COMPRA INT NOT NULL,
    T_A_ESTADO_FACTURA_COMPRA ENUM('PENDIENTE','PAGADA','CANCELADA') NOT NULL,
    FECHA_ACTUALIZACION_COMPRA DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_DET_COMPRA_MP 
(
    ID_ACCION_ACTUALIZAR_DETALLE_COMPRA_MP INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_DET_COMPRA_MAT_PRIM INT NOT NULL,
    T_A_CANTIDAD_MAT_PRIMA_COMPRADA BIGINT NOT NULL,
    T_A_SUB_TOTAL_MAT_PRIMA_COMPRADA BIGINT NOT NULL,
    T_A_ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA BIGINT NOT NULL,
    T_A_ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA BIGINT NOT NULL,
    T_A_ESTADO_DET_COMPRA_MAT_PRIMA BOOLEAN NOT NULL,
    FECHA_ACTUALIZACION_DETALLE_COMPRA_MP DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_DET_COMPRA_PROD 
(
    ID_ACCION_ACTUALIZAR_DETALLE_COMPRA_PROD INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_DET_COMPRA_PROD INT NOT NULL,
    T_A_CANTIDAD_PROD_COMPRADO BIGINT NOT NULL,
    T_A_SUB_TOTAL_PROD_COMPRADO BIGINT NOT NULL,
    T_A_ID_COMPRA_FK_DET_COMPRA_PROD BIGINT NOT NULL,
    T_A_ID_PROD_FK_DET_COMPRA_PROD BIGINT NOT NULL,
    T_A_ESTADO_DET_COMPRA_PROD BOOLEAN NOT NULL,
    FECHA_ACTUALIZACION_DETALLE_COMPRA_PROD DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_PRODUCCION 
(
    ID_ACCION_ACTUALIZAR_PRODUCCION INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_PRODUCCION BIGINT NOT NULL,
    T_A_NOMBRE_PRODUCCION VARCHAR(50) NOT NULL,
    T_A_CANT_PRODUCCION BIGINT NOT NULL,
    T_A_DESCRIPCION_PRODUCCION VARCHAR(200) NOT NULL,
    T_A_ID_PRODUCTO_FK_PRODUCCION BIGINT NOT NULL,
    T_A_ID_USUARIO_FK_PRODUCCION INT NOT NULL,
    T_A_ESTADO_PRODUCCION ENUM('PENDIENTE','EN_PROCESO','FINALIZADA','CANCELADA') NOT NULL,
    FECHA_ACTUALIZACION_PRODUCCION DATETIME NOT NULL
);

CREATE TABLE T_ACTUALIZAR_DET_PRODUCCION 
(
    ID_ACCION_ACTUALIZAR_DETALLE_PRODUCCION BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    T_A_ID_DETALLE_PRODUCCION BIGINT NOT NULL,
    T_A_ID_PRODUCCION_FK_DET_PRODUC BIGINT NOT NULL,
    T_A_ID_MATERIA_PRIMA_FK_DET_PRODUC BIGINT NOT NULL,
    T_A_CANTIDAD_REQUERIDA DECIMAL(10,2) NOT NULL,
    FECHA_ACTUALIZACION_DETALLE_PRODUCCION DATETIME NOT NULL
);
