USE PROYECTO_WYK;

CREATE TABLE T_INSERTAR_ROL
(
    ID_INSERT_ROL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_ROL VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_ROL DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_USUARIO
(
    ID_INSERT_USUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_USUARIO VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_USUARIO DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_TAREA
(
    ID_INSERT_TAREA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_TAREA VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_TAREA DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_PRODUCTO
(
    ID_INSERT_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_PRODUCTO VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_PRODUCTO DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_VENTA
(
    ID_INSERT_VENTA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_VENTA VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_VENTA DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_DETALLE_VENTA
(
    ID_INSERT_DETALLE_VENTA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_DETALLE_VENTA VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_DETALLE_VENTA DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_AJUSTE_INVENTARIO
(
    ID_INSERT_AJUSTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_AJUSTE VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_AJUSTE DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_MATERIA_PRIMA
(
    ID_INSERT_MP INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_MP VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_MP DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_COMPRA
(
    ID_INSERT_COMPRA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_COMPRA VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_COMPRA DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_DET_COMPRA_MP
(
    ID_INSERT_DET_COMPRA_MP INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_DET_COMPRA_MP VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_DET_COMPRA_MP DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_DET_COMPRA_PROD
(
    ID_INSERT_DET_COMPRA_PROD INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_DET_COMPRA_PROD VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_DET_COMPRA_PROD DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_PRODUCCION
(
    ID_INSERT_PRODUCCION INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_PRODUCCION VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_PRODUCCION DATETIME NOT NULL
);

CREATE TABLE T_INSERTAR_DET_PRODUCCION
(
    ID_INSERT_DET_PRODUCCION INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACCION_INSERT_DET_PRODUCCION VARCHAR (200) NOT NULL,
    FECHA_EJECUTO_INSERT_DET_PRODUCCION DATETIME NOT NULL
);