USE PROYECTO_WYK;

 CREATE TABLE ACCION_ACTUALIZAR_ROL
(ID_ACCION_ACTUALIZAR_ROL INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
T_A_ID_ROL INT NOT NULL, 
T_A_ROL VARCHAR (50) NOT NULL,
T_A_CLASIFICACION ENUM('EMPLEADO','ADMINISTRADOR') NOT NULL,
T_A_ESTADO_ROL BOOLEAN NOT NULL,
FECHA_ACTUALIZACION_ROL DATETIME NOT NULL);

DELIMITER $
CREATE TRIGGER TRIGGER_ACTUALIZAR_ROL
AFTER UPDATE ON ROL
FOR EACH ROW 
BEGIN 
	INSERT INTO ACCION_ACTUALIZAR_ROL (T_A_ID_ROL,T_A_ROL,T_A_CLASIFICACION,T_A_ESTADO_ROL,FECHA_ACTUALIZACION_ROL)
    VALUES (OLD.ID_ROL, OLD.ROL,OLD.CLASIFICACION,OLD.ESTADO_ROL, NOW());
END $

UPDATE ROL SET ROL='Administrador General',CLASIFICACION='ADMINISTRADOR',ESTADO_ROL=0 WHERE ID_ROL='1';

SELECT*FROM ROL;

SELECT*FROM ACCION_ACTUALIZAR_ROL;