USE PROYECTO_WYK;

														   /*PROCEDIMIENTOS DE ACTUALIZAR*/
                                                        
														/*👮‍PROCEDIMIENTO ACTUALIZAR CARGO👮‍
_____________________________________________________________________________________________________________________________________________________*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CARGO
(IN P_A_ID_CARGO INT,
IN P_A_NOMBRE_CARGO VARCHAR(50),
IN P_A_ESTADO_CARGO BOOLEAN)
BEGIN
UPDATE CARGO
SET NOMBRE_CARGO=P_A_NOMBRE_CARGO,ESTADO_CARGO=P_A_ESTADO_CARGO
WHERE ID_CARGO=P_A_ID_CARGO;
END $

CALL ACTUALIZAR_CARGO(5,'Pastelero',0);

SELECT*FROM CARGO;

														/*🤴PROCEDIMIENTO ACTUALIZAR USUARIO👸
_____________________________________________________________________________________________________________________________________________________*/  
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_USUARIO
(
IN P_A_ID_USUARIO INT,
IN P_A_NOMBRE_USUARIO VARCHAR(50),
IN P_A_PASSWORD_USUARIO VARCHAR(150),
IN P_A_FECHA_REGISTRO DATETIME,
IN P_A_FECHA_ULTIMA_SESION DATETIME,
IN P_A_ROL ENUM('EMPLEADO','ADMINISTRADOR','CLIENTE'),
IN P_A_ESTADO_USUARIO BOOLEAN
)
BEGIN
UPDATE USUARIO
SET NOMBRE_USUARIO=P_A_NOMBRE_USUARIO,PASSWORD_USUARIO=P_A_PASSWORD_USUARIO,FECHA_REGISTRO=P_A_FECHA_REGISTRO,
FECHA_ULTIMA_SESION=P_A_FECHA_ULTIMA_SESION,ROL=P_A_ROL,ESTADO_USUARIO=P_A_ESTADO_USUARIO
WHERE ID_USUARIO=P_A_ID_USUARIO;
END $     

/*Usuario Empleado*/
CALL ACTUALIZAR_USUARIO (9,'sebas.cajero', '$2y$10$J4yHz0w4Sr9y6gnW8gwJmeYI0k680onW.uDkT/gNlmiQayjlPMQOm', NOW(), NOW(),'EMPLEADO', 0);
/*Usuario Cliente*/
CALL ACTUALIZAR_USUARIO (10,'andre.cliente', '$2y$10$5iFPC0X7qx3l7JV0013foOIFMnlmqdNI7mcVyt.Nl2rQl1IHK1doK', NOW(), NOW(),'CLIENTE', 0);

/*CONTRASEÑAS HORIGINALES*/
/*
EMPLEADO
sebas.cajero (juan040205)
CLIENTE
andre.cliente (Andre1234)
*/

SELECT*FROM USUARIO;



														/*👩‍🍳PROCEDIMIENTO ACTUALIZAR EMPLEADO👨‍🍳
_____________________________________________________________________________________________________________________________________________________*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_EMPLEADO
(
IN P_A_ID_EMPLEADO INT,
IN P_A_CC_EMPLEADO BIGINT,
IN P_A_NOMBRE_EMPLEADO VARCHAR(50),
IN P_A_RH_EMPLEADO VARCHAR (10),
IN P_A_TEL_EMPLEADO BIGINT,
IN P_A_EMAIL_EMPLEADO VARCHAR(50),
IN P_A_ID_CARGO_FK_EMPLEADO INT,
IN P_A_ID_USUARIO_FK_EMPLEADO INT,
IN P_A_ESTADO_EMPLEADO BOOLEAN
)		
BEGIN
UPDATE EMPLEADO 
SET CC_EMPLEADO=P_A_CC_EMPLEADO,NOMBRE_EMPLEADO=P_A_NOMBRE_EMPLEADO,RH_EMPLEADO=P_A_RH_EMPLEADO,TEL_EMPLEADO=P_A_TEL_EMPLEADO,
EMAIL_EMPLEADO=P_A_EMAIL_EMPLEADO,ID_CARGO_FK_EMPLEADO=P_A_ID_CARGO_FK_EMPLEADO,ID_USUARIO_FK_EMPLEADO=P_A_ID_USUARIO_FK_EMPLEADO,ESTADO_EMPLEADO=P_A_ESTADO_EMPLEADO
WHERE ID_EMPLEADO=P_A_ID_EMPLEADO;
END $	

CALL ACTUALIZAR_EMPLEADO(5,1005005005,'Sebastian Pinto','O+',3015202833,'juanpintow@gmaiol.com',5,9,0);

SELECT*FROM EMPLEADO;	

														/*👦PROCEDIMIENTO ACTUALIZAR CLIENTE👦
_____________________________________________________________________________________________________________________________________________________*/	
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_CLIENTE
(
IN P_A_ID_CLIENTE INT,
IN P_A_NUM_DOCUMENTO_CLIENTE BIGINT,
IN P_A_TIPO_DOCUMENTO_CLIENTE ENUM ('TI','CC','CE'),
IN P_A_NOMBRE_CLIENTE VARCHAR(50),
IN P_A_TEL_CLIENTE BIGINT,
IN P_A_EMAIL_CLIENTE VARCHAR(50),
IN P_A_ID_EMPLEADO_FK_CLIENTE INT,
IN P_A_ID_USUARIO_FK_CLIENTE INT,
IN P_A_ESTADO_CLIENTE BOOLEAN
)   
BEGIN
UPDATE CLIENTE
SET NUM_DOCUMENTO_CLIENTE=P_A_NUM_DOCUMENTO_CLIENTE,TIPO_DOCUMENTO_CLIENTE=P_A_TIPO_DOCUMENTO_CLIENTE,NOMBRE_CLIENTE=P_A_NOMBRE_CLIENTE,TEL_CLIENTE=P_A_TEL_CLIENTE,
EMAIL_CLIENTE=P_A_EMAIL_CLIENTE,ID_EMPLEADO_FK_CLIENTE=P_A_ID_EMPLEADO_FK_CLIENTE,ID_USUARIO_FK_CLIENTE=P_A_ID_USUARIO_FK_CLIENTE,ESTADO_CLIENTE=P_A_ESTADO_CLIENTE
WHERE ID_CLIENTE=P_A_ID_CLIENTE;
END $   

CALL ACTUALIZAR_CLIENTE (5,1002001002,'TI','Andrea Florian',3132563434,'hurtadoyerik@gmail.com',5,10,0);

SELECT*FROM CLIENTE; 

														/*🍰PROCEDIMIENTO ACTUALIZAR PEDIDO🍰
_____________________________________________________________________________________________________________________________________________________*/
													
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PEDIDO
(
IN P_A_ID_PEDIDO BIGINT,
IN P_A_FECHA_HORA_PEDIDO DATETIME,
IN P_A_NUMERO_MESA INT,
IN P_A_ID_EMPLEADO_FK_PEDIDO INT,
IN P_A_ID_CLIENTE_FK_PEDIDO INT,
IN ESTADO_PEDIDO ENUM('PENDIENTE','EN PREPARACION','ENTREGADO','CANCELADO')
)
BEGIN
UPDATE PEDIDO
SET FECHA_HORA_PEDIDO=P_A_FECHA_HORA_PEDIDO,NUMERO_MESA=P_A_NUMERO_MESA,ID_EMPLEADO_FK_PEDIDO=P_A_ID_EMPLEADO_FK_PEDIDO,
ID_CLIENTE_FK_PEDIDO=P_A_ID_CLIENTE_FK_PEDIDO,ESTADO_PEDIDO=ESTADO_PEDIDO
WHERE ID_PEDIDO=P_A_ID_PEDIDO;
END $

CALL ACTUALIZAR_PEDIDO( 5, NOW(), 3,5,5, 'CANCELADO');

SELECT*FROM PEDIDO;

														/*🥐PROCEDIMIENTO ACTUALIZAR PRODUCTO🥐
_____________________________________________________________________________________________________________________________________________________*/
									
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PRODUCTO
(
IN P_A_ID_PRODUCTO BIGINT,
IN P_A_NOMBRE_PRODUCTO VARCHAR(50),
IN P_A_VALOR_UNITARIO_PRODUCTO BIGINT,
IN P_A_CANT_EXIST_PRODUCTO BIGINT,
IN P_A_FECHA_VENCIMIENTO_PRODUCTO DATE,
IN P_A_TIPO_PRODUCTO_GENERAL ENUM('PANADERIA','PASTELERIA','VIBERES'),
IN P_A_TIPO_PRODUCTO_ESPECIFICO VARCHAR(50),
IN P_A_MARCA_PRODUCTO VARCHAR(50),
IN P_A_ID_EMPLEADO_FK_PRODUCTO INT,
IN P_A_ESTADO_PRODUCTO BOOLEAN
)	
BEGIN
UPDATE PRODUCTO
SET NOMBRE_PRODUCTO=P_A_NOMBRE_PRODUCTO,VALOR_UNITARIO_PRODUCTO=P_A_VALOR_UNITARIO_PRODUCTO,CANT_EXIST_PRODUCTO=P_A_CANT_EXIST_PRODUCTO,FECHA_VENCIMIENTO_PRODUCTO=P_A_FECHA_VENCIMIENTO_PRODUCTO,
TIPO_PRODUCTO_GENERAL=P_A_TIPO_PRODUCTO_GENERAL,TIPO_PRODUCTO_ESPECIFICO=P_A_TIPO_PRODUCTO_ESPECIFICO,MARCA_PRODUCTO=P_A_MARCA_PRODUCTO,
ID_EMPLEADO_FK_PRODUCTO=P_A_ID_EMPLEADO_FK_PRODUCTO,ESTADO_PRODUCTO=P_A_ESTADO_PRODUCTO
WHERE ID_PRODUCTO=P_A_ID_PRODUCTO;
END $	

CALL ACTUALIZAR_PRODUCTO(7700055,'PEDIDO CALLDO PARA LA MESA 5',30,12,'2025-07-15','PANADERIA','CALDO','Wyk Pan',5,0);

SELECT*FROM PRODUCTO;

														/*🚲PROCEDIMIENTO ACTUALIZAR DETALLE PEDIDO🚲
_____________________________________________________________________________________________________________________________________________________*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_PEDIDO
(
IN P_A_ID_DETALLE_PEDIDO INT,
IN P_A_DESCRIPCION_DETALLE_PEDIDO VARCHAR(200),
IN P_A_ID_PEDIDO_FK_DETALLE_PEDIDO BIGINT,
IN P_A_ID_PRODUCTO_FK_DETALLE_PEDIDO BIGINT,
IN P_A_ESTADO_DETALLE_PEDIDO_PRODUCTO BOOLEAN
)													
BEGIN
UPDATE DETALLE_PEDIDO
SET DESCRIPCION_DETALLE_PEDIDO=P_A_DESCRIPCION_DETALLE_PEDIDO,ID_PEDIDO_FK_DETALLE_PEDIDO=P_A_ID_PEDIDO_FK_DETALLE_PEDIDO,
ID_PRODUCTO_FK_DETALLE_PEDIDO=P_A_ID_PRODUCTO_FK_DETALLE_PEDIDO,ESTADO_DETALLE_PEDIDO_PRODUCTO=P_A_ESTADO_DETALLE_PEDIDO_PRODUCTO
WHERE ID_DETALLE_PEDIDO=P_A_ID_DETALLE_PEDIDO;
END $

CALL ACTUALIZAR_DETALLE_PEDIDO(5,'PEDIDO CALLDO PARA LA MESA 5',5,7700055,0);

SELECT*FROM DETALLE_PEDIDO;

														/*📄PROCEDIMIENTO ACTUALIZAR FACTURA VENTA📄
_____________________________________________________________________________________________________________________________________________________*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_FACTURA_VENTA 
(
  IN P_A_ID_FACTURA_VENTA INT,
  IN P_A_TOTAL_FACTURA_VENTA BIGINT,
  IN P_A_FECHA_HORA_FACTURA_VENTA DATETIME,
  IN P_A_DESCRIPCION_FACTURA_VENTA VARCHAR(200),
  IN P_A_ID_EMPLEADO_FK_FACTURA_VENTA INT,
  IN P_A_ID_PEDIDO_FK_FACTURA_VENTA BIGINT,
  IN P_A_ID_CLIENTE_FK_FACTURA_VENTA INT,
  IN P_A_ESTADO_FACTURA_VENTA ENUM('PENDIENTE','PAGADA','CANCELADA') 
)
BEGIN
UPDATE FACTURA_VENTA
SET 
TOTAL_FACTURA_VENTA=P_A_TOTAL_FACTURA_VENTA,FECHA_HORA_FACTURA_VENTA=P_A_FECHA_HORA_FACTURA_VENTA,
DESCRIPCION_FACTURA_VENTA=P_A_DESCRIPCION_FACTURA_VENTA,ID_EMPLEADO_FK_FACTURA_VENTA=P_A_ID_EMPLEADO_FK_FACTURA_VENTA,
ID_PEDIDO_FK_FACTURA_VENTA=P_A_ID_PEDIDO_FK_FACTURA_VENTA,ID_CLIENTE_FK_FACTURA_VENTA=P_A_ID_CLIENTE_FK_FACTURA_VENTA,
ESTADO_FACTURA_VENTA=P_A_ESTADO_FACTURA_VENTA
  WHERE ID_FACTURA_VENTA=P_A_ID_FACTURA_VENTA;
END $    

CALL ACTUALIZAR_FACTURA_VENTA (5,12000, NOW(), 'VENTA 1 CALDO', 5,5,5,'CANCELADA');        

SELECT*FROM FACTURA_VENTA;          

														/*🔖PROCEDIMIENTO ACTUALIZAR DETALLE_VENTA_PRODUCTO🔖
_____________________________________________________________________________________________________________________________________________________*/ 
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_VENTA_PRODUCTO
(
IN P_A_ID_DETALLE_VENTA_PRODUCTO INT,
IN P_A_CANTIDAD_PRODUCTO_VENDIDO BIGINT,
IN P_A_SUB_TOTAL_PRODUCTO_VENDIDO BIGINT,
IN P_A_ID_FACTURA_VENTA_FK_DET_VENTA_PRODUCTO BIGINT,
IN P_A_ID_PRODUCTO_FK_DET_FACTURA_VENTA BIGINT,
IN P_A_ESTADO_DETALLE_VENTA_PRODUCTO BOOLEAN
)
BEGIN
UPDATE DETALLE_VENTA_PRODUCTO
SET CANTIDAD_PRODUCTO_VENDIDO=P_A_CANTIDAD_PRODUCTO_VENDIDO,SUB_TOTAL_PRODUCTO_VENDIDO=P_A_SUB_TOTAL_PRODUCTO_VENDIDO,
ID_FACTURA_VENTA_FK_DET_VENTA_PRODUCTO=P_A_ID_FACTURA_VENTA_FK_DET_VENTA_PRODUCTO,
ID_PRODUCTO_FK_DET_FACTURA_VENTA=P_A_ID_PRODUCTO_FK_DET_FACTURA_VENTA,ESTADO_DETALLE_VENTA_PRODUCTO=P_A_ESTADO_DETALLE_VENTA_PRODUCTO
WHERE ID_DETALLE_VENTA_PRODUCTO=P_A_ID_DETALLE_VENTA_PRODUCTO;
END $

CALL ACTUALIZAR_DETALLE_VENTA_PRODUCTO(5,1,4000,5,7700055,0);

SELECT*FROM DETALLE_VENTA_PRODUCTO;

														/*👩‍💼PROCEDIMIENTO ACTUALIZAR PROVEEDOR👨‍💼
_____________________________________________________________________________________________________________________________________________________*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PROVEEDOR
(
IN P_A_ID_PROVEEDOR INT,
IN P_A_CC_PROVEEDOR BIGINT,
IN P_A_NOMBRE_PROVEEDOR VARCHAR(50),
IN P_A_TEL_PROVEEDOR BIGINT,
IN P_A_EMAIL_PROVEEDOR VARCHAR(50),
IN P_A_ID_EMPLEADO_FK_PROVEEDOR INT,
IN P_A_ESTADO_PROVEEDOR BOOLEAN
)     
BEGIN
UPDATE PROVEEDOR
SET CC_PROVEEDOR=P_A_CC_PROVEEDOR,NOMBRE_PROVEEDOR=P_A_NOMBRE_PROVEEDOR,TEL_PROVEEDOR=P_A_TEL_PROVEEDOR,EMAIL_PROVEEDOR=P_A_EMAIL_PROVEEDOR,
ID_EMPLEADO_FK_PROVEEDOR=P_A_ID_EMPLEADO_FK_PROVEEDOR,ESTADO_PROVEEDOR=P_A_ESTADO_PROVEEDOR
WHERE ID_PROVEEDOR=P_A_ID_PROVEEDOR;
END $      

CALL ACTUALIZAR_PROVEEDOR(5,800500600,'BRANNDON SUAREZ', 3125687,'si@gmail.com',5,0);   

SELECT*FROM PROVEEDOR;    

														/*🥣PROCEDIMIENTO ACTUALIZAR MATERIA PRIMA🥣
_____________________________________________________________________________________________________________________________________________________*/                            
									
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_MATERIA_PRIMA
(
IN P_A_ID_MATERIA_PRIMA INT,
IN P_A_NOMBRE_MATERIA_PRIMA VARCHAR (50),
IN P_A_FECHA_VENCIMIENTO_MATERIA_PRIMA DATE,
IN P_A_TIPO_DE_MEDIDA VARCHAR(50),
IN P_A_CANTIDAD_EXIST_MATERIA_PRIMA BIGINT,
IN P_A_MARCA_MATERIA_PRIMA VARCHAR(50),
IN P_A_PRESENTACION_MATERIA_PRIMA VARCHAR(50),
IN P_A_DESCRIPCION_MATERIA_PRIMA VARCHAR(200),
IN P_A_ID_EMPLEADO_FK_MATERIA_PRIMA INT,
IN P_A_ESTADO_MATERIA_PRIMA BOOLEAN
)        
BEGIN
UPDATE MATERIA_PRIMA
SET NOMBRE_MATERIA_PRIMA=P_A_NOMBRE_MATERIA_PRIMA,FECHA_VENCIMIENTO_MATERIA_PRIMA=P_A_FECHA_VENCIMIENTO_MATERIA_PRIMA,TIPO_DE_MEDIDA=P_A_TIPO_DE_MEDIDA,
CANTIDAD_EXIST_MATERIA_PRIMA=P_A_CANTIDAD_EXIST_MATERIA_PRIMA,MARCA_MATERIA_PRIMA=P_A_MARCA_MATERIA_PRIMA,
PRESENTACION_MATERIA_PRIMA=P_A_PRESENTACION_MATERIA_PRIMA,DESCRIPCION_MATERIA_PRIMA=P_A_DESCRIPCION_MATERIA_PRIMA,
ID_EMPLEADO_FK_MATERIA_PRIMA=P_A_ID_EMPLEADO_FK_MATERIA_PRIMA,ESTADO_MATERIA_PRIMA=P_A_ESTADO_MATERIA_PRIMA
WHERE ID_MATERIA_PRIMA=P_A_ID_MATERIA_PRIMA;
END $    

CALL ACTUALIZAR_MATERIA_PRIMA (5,'HARINA', '2026-01-15', 'GRAMOS', 300,'HARINAS DEL VALLE','BULTO 50KG','HARINA PARA PANADERIA',5,0);

SELECT*FROM MATERIA_PRIMA;   

														/*📜PROCEDIMIENTO ACTUALIZAR FACTURA COMPRA📜
_____________________________________________________________________________________________________________________________________________________*/ 
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_FACTURA_COMPRA
(
IN P_A_ID_FACTURA_COMPRA BIGINT ,
IN P_A_TOTAL_FACTURA_COMPRA BIGINT,
IN P_A_FECHA_HORA_FACTURA_COMPRA DATETIME,
IN P_A_DESCRIPCION_FACTURA_COMPRA VARCHAR(200),
IN P_A_ID_EMPLEADO_FK_FACTURA_COMPRA INT,
IN P_A_ID_PROVEEDOR_FK_FACTURA_COMPRA INT,
IN P_A_ESTADO_FACTURA_COMPRA ENUM('PENDIENTE','PAGADA','CANCELADA')
)  
BEGIN
UPDATE FACTURA_COMPRA
SET  TOTAL_FACTURA_COMPRA=P_A_TOTAL_FACTURA_COMPRA,FECHA_HORA_FACTURA_COMPRA=P_A_FECHA_HORA_FACTURA_COMPRA,DESCRIPCION_FACTURA_COMPRA=P_A_DESCRIPCION_FACTURA_COMPRA,
ID_EMPLEADO_FK_FACTURA_COMPRA=P_A_ID_EMPLEADO_FK_FACTURA_COMPRA,ID_PROVEEDOR_FK_FACTURA_COMPRA=P_A_ID_PROVEEDOR_FK_FACTURA_COMPRA,
ESTADO_FACTURA_COMPRA=P_A_ESTADO_FACTURA_COMPRA
WHERE ID_FACTURA_COMPRA=P_A_ID_FACTURA_COMPRA;
END $        

CALL  ACTUALIZAR_FACTURA_COMPRA(9,100000, NOW(), 'COMPRA HARINA', 5, 5 , 'CANCELADA');

SELECT*FROM FACTURA_COMPRA;

														/*📰PROCEDIMIENTO ACTUALIZAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA📰
_____________________________________________________________________________________________________________________________________________________*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA
(
IN P_A_ID_DETALLE_FAC_MAT_PRIM INT,
IN P_A_CANTIDAD_MATERIA_PRIMA_COMPRADA BIGINT,
IN P_A_SUB_TOTAL_MATERIA_PRIMA_COMPRADA BIGINT,
IN P_A_ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA BIGINT,
IN P_A_ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA BIGINT,
IN P_A_ESTADO_DETAllE_COMPRA_MATERIA_PRIMA BOOLEAN
)
BEGIN
UPDATE DETALLE_FACTURA_COMPRA_MATERIA_PRIMA
SET CANTIDAD_MATERIA_PRIMA_COMPRADA=P_A_CANTIDAD_MATERIA_PRIMA_COMPRADA,SUB_TOTAL_MATERIA_PRIMA_COMPRADA=P_A_SUB_TOTAL_MATERIA_PRIMA_COMPRADA,
ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA=P_A_ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA,
ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA=P_A_ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA,
ESTADO_DETALLE_COMPRA_MATERIA_PRIMA=P_A_ESTADO_DETAllE_COMPRA_MATERIA_PRIMA
WHERE ID_DETALLE_FAC_MAT_PRIM=P_A_ID_DETALLE_FAC_MAT_PRIM;
END $    

CALL ACTUALIZAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA(5,300,50000,5,5,0);

SELECT*FROM DETALLE_FACTURA_COMPRA_MATERIA_PRIMA;

														/*🍮PROCEDIMIENTO ACTUALIZAR_DETALLE_COMPRA_PRODUCTO🍮
_____________________________________________________________________________________________________________________________________________________*/
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_DETALLE_COMPRA_PRODUCTO
(
IN P_A_ID_DETALLE_COMPRA_PRODUCTO INT,
IN P_A_CANTIDAD_PRODUCTO_COMPRADO BIGINT,
IN P_A_SUB_TOTAL_PRODUCTO_COMPRADO BIGINT,
IN P_A_ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO BIGINT,
IN P_A_ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO BIGINT,
IN P_A_ESTADO_DETALLE_COMPRA_PRODUCTO BOOLEAN
)                                                        
BEGIN
UPDATE DETALLE_COMPRA_PRODUCTO
SET CANTIDAD_PRODUCTO_COMPRADO=P_A_CANTIDAD_PRODUCTO_COMPRADO,SUB_TOTAL_PRODUCTO_COMPRADO=P_A_SUB_TOTAL_PRODUCTO_COMPRADO,
ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO=P_A_ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO,
ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO=P_A_ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO,ESTADO_DETALLE_COMPRA_PRODUCTO=P_A_ESTADO_DETALLE_COMPRA_PRODUCTO
WHERE ID_DETALLE_COMPRA_PRODUCTO=P_A_ID_DETALLE_COMPRA_PRODUCTO;
END $
        
CALL ACTUALIZAR_DETALLE_COMPRA_PRODUCTO(5,300,50000,5,7700055,0);

SELECT*FROM DETALLE_COMPRA_PRODUCTO;

														/*🍲PRECEDIMIENTO ACTUALIZAR PRODUCCION🍲
_____________________________________________________________________________________________________________________________________________________*/ 
                                                        
DELIMITER $
CREATE PROCEDURE ACTUALIZAR_PRODUCCION
(
IN P_A_ID_PRODUCCION INT,
IN P_A_NOMBRE_PRODUCCION VARCHAR(50),
IN P_A_CANT_PRODUCCION BIGINT,
IN P_A_DESCRIPCION_PRODUCCION VARCHAR(200),
IN P_A_MATERIA_PRIMA_GASTADA BIGINT,
IN P_A_ID_MATERIA_PRIMA_FK_PRODUCCION BIGINT,
IN P_A_ID_PRODUCTO_FK_MATERIA_PRIMA BIGINT,
IN P_A_ID_EMPLEADO_FK_PRODUCCION INT,
IN P_A_ESTADO_PRODUCCION BOOLEAN
)   
BEGIN
UPDATE PRODUCCION
SET NOMBRE_PRODUCCION=P_A_NOMBRE_PRODUCCION,CANT_PRODUCCION=P_A_CANT_PRODUCCION,DESCRIPCION_PRODUCCION=P_A_DESCRIPCION_PRODUCCION,
MATERIA_PRIMA_GASTADA=P_A_MATERIA_PRIMA_GASTADA,ID_MATERIA_PRIMA_FK_PRODUCCION=P_A_ID_MATERIA_PRIMA_FK_PRODUCCION,
ID_PRODUCTO_FK_MATERIA_PRIMA=P_A_ID_PRODUCTO_FK_MATERIA_PRIMA,ID_EMPLEADO_FK_PRODUCCION=P_A_ID_EMPLEADO_FK_PRODUCCION,
ESTADO_PRODUCCION=P_A_ESTADO_PRODUCCION
WHERE ID_PRODUCCION=P_A_ID_PRODUCCION;
END $    

CALL ACTUALIZAR_PRODUCCION(5,'PRUEBA',20,'PRODU',10,5,7700055,5,0);

SELECT*FROM PRODUCCION;