USE PROYECTO_WYK;

														   /*PROCEDIMIENTOS DE INSERTAR*/

														/*👮‍PROCEDIMIENTO INSERTAR CARGO👮‍
____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_CARGO
(
    IN P_I_NOMBRE_CARGO VARCHAR(50),
    IN P_I_ESTADO_CARGO BOOLEAN
)
BEGIN
    INSERT INTO CARGO (NOMBRE_CARGO,ESTADO_CARGO)
    VALUES (P_I_NOMBRE_CARGO,P_I_ESTADO_CARGO);
END $

CALL INSERTAR_CARGO ('Pastelero',1); 
SELECT * FROM CARGO;

/*🤴PROCEDIMIENTO INSERTAR USUARIO👸
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_USUARIO
(
    IN P_I_NOMBRE_USUARIO VARCHAR(50),
    IN P_I_PASSWORD_USUARIO VARCHAR(150),
    IN P_I_FECHA_REGISTRO DATETIME,
    IN P_I_FECHA_ULTIMA_SESION DATETIME,
    IN P_I_ROL VARCHAR(20),
    IN P_I_ESTADO_USUARIO BOOLEAN
)
BEGIN
    INSERT INTO USUARIO (NOMBRE_USUARIO,PASSWORD_USUARIO,FECHA_REGISTRO,FECHA_ULTIMA_SESION,ROL,ESTADO_USUARIO)
    VALUES (P_I_NOMBRE_USUARIO,P_I_PASSWORD_USUARIO,P_I_FECHA_REGISTRO,P_I_FECHA_ULTIMA_SESION,P_I_ROL,P_I_ESTADO_USUARIO);
END $

/*Usuario Empleado*/
CALL INSERTAR_USUARIO('sebas.cajero', '$2y$10$J4yHz0w4Sr9y6gnW8gwJmeYI0k680onW.uDkT/gNlmiQayjlPMQOm', NOW(), NOW(),'EMPLEADO', 1);
/*Usuario Cliente*/
CALL INSERTAR_USUARIO('andre.cliente', '$2y$10$5iFPC0X7qx3l7JV0013foOIFMnlmqdNI7mcVyt.Nl2rQl1IHK1doK', NOW(), NOW(),'CLIENTE', 1);

SELECT * FROM USUARIO;

/*👩‍🍳PROCEDIMIENTO INSERTAR EMPLEADO👨‍🍳
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_EMPLEADO
(
    IN P_I_CC_EMPLEADO BIGINT,
    IN P_I_NOMBRE_EMPLEADO VARCHAR(50),
    IN P_I_RH_EMPLEADO VARCHAR(10),
    IN P_I_TEL_EMPLEADO BIGINT,
    IN P_I_EMAIL_EMPLEADO VARCHAR(50),
    IN P_I_ID_CARGO_FK_EMPLEADO INT,
    IN P_I_ID_USUARIO_FK_EMPLEADO INT,
    IN P_I_ESTADO_EMPLEADO BOOLEAN
)
BEGIN 
    INSERT INTO EMPLEADO (CC_EMPLEADO,NOMBRE_EMPLEADO,RH_EMPLEADO,TEL_EMPLEADO,EMAIL_EMPLEADO,ID_CARGO_FK_EMPLEADO,ID_USUARIO_FK_EMPLEADO,ESTADO_EMPLEADO)
    VALUES (P_I_CC_EMPLEADO,P_I_NOMBRE_EMPLEADO,P_I_RH_EMPLEADO,P_I_TEL_EMPLEADO,P_I_EMAIL_EMPLEADO,P_I_ID_CARGO_FK_EMPLEADO,P_I_ID_USUARIO_FK_EMPLEADO,P_I_ESTADO_EMPLEADO);
END $

CALL INSERTAR_EMPLEADO (1005005005,'Sebastian Pinto','O+',3015202833,'juanpintow@gmail.com',5,9,1);
SELECT * FROM EMPLEADO;

/*👦PROCEDIMIENTO INSERTAR CLIENTE👦
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_CLIENTE
(
    IN P_I_NUM_DOCUMENTO_CLIENTE BIGINT,
    IN P_I_TIPO_DOCUMENTO_CLIENTE VARCHAR(5),
    IN P_I_NOMBRE_CLIENTE VARCHAR(50),
    IN P_I_TEL_CLIENTE BIGINT,
    IN P_I_EMAIL_CLIENTE VARCHAR(50),
    IN P_I_ID_EMPLEADO_FK_CLIENTE INT,
    IN P_I_ID_USUARIO_FK_CLIENTE INT,
    IN P_I_ESTADO_CLIENTE BOOLEAN
)
BEGIN 
    INSERT INTO CLIENTE (NUM_DOCUMENTO_CLIENTE,TIPO_DOCUMENTO_CLIENTE,NOMBRE_CLIENTE,TEL_CLIENTE,EMAIL_CLIENTE,ID_EMPLEADO_FK_CLIENTE,ID_USUARIO_FK_CLIENTE,ESTADO_CLIENTE)
    VALUES (P_I_NUM_DOCUMENTO_CLIENTE,P_I_TIPO_DOCUMENTO_CLIENTE,P_I_NOMBRE_CLIENTE,P_I_TEL_CLIENTE,P_I_EMAIL_CLIENTE,P_I_ID_EMPLEADO_FK_CLIENTE,P_I_ID_USUARIO_FK_CLIENTE,P_I_ESTADO_CLIENTE);
END $

CALL INSERTAR_CLIENTE(1002001002,'TI','Andrea Florian',3132563434,'hurtadoyerik@gmail.com',5,10,1);
SELECT * FROM CLIENTE;

/*🍰PROCEDIMIENTO INSERTAR PEDIDO🍰
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_PEDIDO
(
    IN P_I_FECHA_HORA_PEDIDO DATETIME,
    IN P_I_NUMERO_MESA INT,
    IN P_I_ID_EMPLEADO_FK_PEDIDO INT,
    IN P_I_ID_CLIENTE_FK_PEDIDO INT,
    IN P_I_ESTADO_PEDIDO VARCHAR(20)
)
BEGIN
    INSERT INTO PEDIDO (FECHA_HORA_PEDIDO,NUMERO_MESA,ID_EMPLEADO_FK_PEDIDO,ID_CLIENTE_FK_PEDIDO,ESTADO_PEDIDO)
    VALUES (P_I_FECHA_HORA_PEDIDO,P_I_NUMERO_MESA,P_I_ID_EMPLEADO_FK_PEDIDO,P_I_ID_CLIENTE_FK_PEDIDO,P_I_ESTADO_PEDIDO);
END $

CALL INSERTAR_PEDIDO(NOW(), 3,5,5, 'PENDIENTE');
SELECT * FROM PEDIDO;

/*🥐PROCEDIMIENTO INSERTAR PRODUCTO🥐
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_PRODUCTO
(
    IN P_I_ID_PRODUCTO BIGINT,
    IN P_I_NOMBRE_PRODUCTO VARCHAR(50),
    IN P_I_VALOR_UNITARIO_PRODUCTO BIGINT,
    IN P_I_CANT_EXIST_PRODUCTO BIGINT,
    IN P_I_FECHA_VENCIMIENTO_PRODUCTO DATE,
    IN P_I_TIPO_PRODUCTO_GENERAL VARCHAR(20),
    IN P_I_TIPO_PRODUCTO_ESPECIFICO VARCHAR(50),
    IN P_I_MARCA_PRODUCTO VARCHAR (50),
    IN P_I_ID_EMPLEADO_FK_PRODUCTO INT,
    IN P_I_ESTADO_PRODUCTO BOOLEAN
)
BEGIN 
    INSERT INTO PRODUCTO (ID_PRODUCTO,NOMBRE_PRODUCTO,VALOR_UNITARIO_PRODUCTO,CANT_EXIST_PRODUCTO,
    FECHA_VENCIMIENTO_PRODUCTO,TIPO_PRODUCTO_GENERAL,TIPO_PRODUCTO_ESPECIFICO,MARCA_PRODUCTO,ID_EMPLEADO_FK_PRODUCTO,ESTADO_PRODUCTO)
    VALUES (P_I_ID_PRODUCTO,P_I_NOMBRE_PRODUCTO,P_I_VALOR_UNITARIO_PRODUCTO,P_I_CANT_EXIST_PRODUCTO,P_I_FECHA_VENCIMIENTO_PRODUCTO,
    P_I_TIPO_PRODUCTO_GENERAL,P_I_TIPO_PRODUCTO_ESPECIFICO,P_I_MARCA_PRODUCTO,P_I_ID_EMPLEADO_FK_PRODUCTO,P_I_ESTADO_PRODUCTO);
END $

CALL INSERTAR_PRODUCTO(7700055,'PEDIDO CALDO PARA LA MESA 5',12000,12,'2025-07-15','PANADERIA','CALDO','Wyk Pan',5,1);
SELECT * FROM PRODUCTO;

/*🚲PROCEDIMIENTO INSERTAR DETALLE PEDIDO🚲
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_PEDIDO
(
    IN P_I_ID_DETALLE_PEDIDO INT,
    IN P_I_DESCRIPCION_DETALLE_PEDIDO VARCHAR(200),
    IN P_I_ID_PEDIDO_FK_DETALLE_PEDIDO BIGINT,
    IN P_I_ID_PRODUCTO_FK_DETALLE_PEDIDO BIGINT,
    IN P_I_ESTADO_DETALLE_PEDIDO_PRODUCTO BOOLEAN
)
BEGIN 
    INSERT INTO DETALLE_PEDIDO (ID_DETALLE_PEDIDO,DESCRIPCION_DETALLE_PEDIDO,ID_PEDIDO_FK_DETALLE_PEDIDO,ID_PRODUCTO_FK_DETALLE_PEDIDO,ESTADO_DETALLE_PEDIDO_PRODUCTO)
    VALUES (P_I_ID_DETALLE_PEDIDO,P_I_DESCRIPCION_DETALLE_PEDIDO,P_I_ID_PEDIDO_FK_DETALLE_PEDIDO,P_I_ID_PRODUCTO_FK_DETALLE_PEDIDO,P_I_ESTADO_DETALLE_PEDIDO_PRODUCTO);
END $

CALL INSERTAR_DETALLE_PEDIDO(5,'PEDIDO CALDO PARA LA MESA 5',5,7700055,1);
SELECT * FROM DETALLE_PEDIDO;

/*📄PROCEDIMIENTO INSERTAR FACTURA VENTA📄
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_FACTURA_VENTA
(
    IN P_I_TOTAL_FACTURA_VENTA BIGINT,
    IN P_I_FECHA_HORA_FACTURA_VENTA DATETIME,
    IN P_I_DESCRIPCION_FACTURA_VENTA VARCHAR(200),
    IN P_I_ID_EMPLEADO_FK_FACTURA_VENTA INT,
    IN P_I_ID_PEDIDO_FK_FACTURA_VENTA BIGINT,
    IN P_I_ID_CLIENTE_FK_FACTURA_VENTA INT,
    IN P_I_ESTADO_FACTURA_VENTA VARCHAR(20)
)
BEGIN
    INSERT INTO FACTURA_VENTA (TOTAL_FACTURA_VENTA,FECHA_HORA_FACTURA_VENTA,DESCRIPCION_FACTURA_VENTA,ID_EMPLEADO_FK_FACTURA_VENTA,
    ID_PEDIDO_FK_FACTURA_VENTA,ID_CLIENTE_FK_FACTURA_VENTA,ESTADO_FACTURA_VENTA)
    VALUES (P_I_TOTAL_FACTURA_VENTA,P_I_FECHA_HORA_FACTURA_VENTA,P_I_DESCRIPCION_FACTURA_VENTA,P_I_ID_EMPLEADO_FK_FACTURA_VENTA,
    P_I_ID_PEDIDO_FK_FACTURA_VENTA,P_I_ID_CLIENTE_FK_FACTURA_VENTA,P_I_ESTADO_FACTURA_VENTA);
END $

CALL INSERTAR_FACTURA_VENTA(12000, NOW(), 'VENTA 1 CALDO', 5,5,5,'PAGADA');
SELECT * FROM FACTURA_VENTA;

/*🔖PROCEDIMIENTO INSERTAR DETALLE_VENTA_PRODUCTO🔖
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_VENTA_PRODUCTO
(
    IN P_I_ID_DETALLE_VENTA_PRODUCTO INT,
    IN P_I_CANTIDAD_PRODUCTO_VENDIDO BIGINT,
    IN P_I_SUB_TOTAL_PRODUCTO_VENDIDO BIGINT,
    IN P_I_ID_FACTURA_VENTA_FK_DET_VENTA_PRODUCTO BIGINT,
    IN P_I_ID_PRODUCTO_FK_DET_FACTURA_VENTA BIGINT,
    IN P_I_ESTADO_DETALLE_VENTA_PRODUCTO BOOLEAN
)
BEGIN
    INSERT INTO DETALLE_VENTA_PRODUCTO(ID_DETALLE_VENTA_PRODUCTO,CANTIDAD_PRODUCTO_VENDIDO,SUB_TOTAL_PRODUCTO_VENDIDO,
    ID_FACTURA_VENTA_FK_DET_VENTA_PRODUCTO,ID_PRODUCTO_FK_DET_FACTURA_VENTA,ESTADO_DETALLE_VENTA_PRODUCTO)
    VALUES (P_I_ID_DETALLE_VENTA_PRODUCTO,P_I_CANTIDAD_PRODUCTO_VENDIDO,P_I_SUB_TOTAL_PRODUCTO_VENDIDO,P_I_ID_FACTURA_VENTA_FK_DET_VENTA_PRODUCTO,
    P_I_ID_PRODUCTO_FK_DET_FACTURA_VENTA,P_I_ESTADO_DETALLE_VENTA_PRODUCTO);
END $

CALL INSERTAR_DETALLE_VENTA_PRODUCTO (5,1,4000,5,7700055,1);
SELECT * FROM DETALLE_VENTA_PRODUCTO;

/*👩‍💼PROCEDIMIENTO INSERTAR PROVEEDOR👨‍💼
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_PROVEEDOR
(
    IN P_I_CC_PROVEEDOR BIGINT,
    IN P_I_NOMBRE_PROVEEDOR VARCHAR(50),
    IN P_I_TEL_PROVEEDOR BIGINT,
    IN P_I_EMAIL_PROVEEDOR VARCHAR (50),
    IN P_I_ID_EMPLEADO_FK_PROVEEDOR INT,
    IN P_I_ESTADO_PROVEEDOR BOOLEAN
)
BEGIN
    INSERT INTO PROVEEDOR(CC_PROVEEDOR,NOMBRE_PROVEEDOR,TEL_PROVEEDOR,EMAIL_PROVEEDOR,ID_EMPLEADO_FK_PROVEEDOR,ESTADO_PROVEEDOR)
    VALUES (P_I_CC_PROVEEDOR,P_I_NOMBRE_PROVEEDOR,P_I_TEL_PROVEEDOR,P_I_EMAIL_PROVEEDOR,P_I_ID_EMPLEADO_FK_PROVEEDOR,P_I_ESTADO_PROVEEDOR);
END $

CALL INSERTAR_PROVEEDOR (800500600,'BRANNDON SUAREZ', 3125687,'si@gmail.com',5,1);
SELECT * FROM PROVEEDOR;

/*🥣PROCEDIMIENTO INSERTAR MATERIA PRIMA🥣
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_MATERIA_PRIMA
(
    IN P_I_NOMBRE_MATERIA_PRIMA VARCHAR (50),
    IN P_I_FECHA_VENCIMIENTO_MATERIA_PRIMA DATE,
    IN P_I_TIPO_DE_MEDIDA VARCHAR(50),
    IN P_I_CANTIDAD_EXIST_MATERIA_PRIMA BIGINT,
    IN P_I_MARCA_MATERIA_PRIMA VARCHAR (50),
    IN P_I_PRESENTACION_MATERIA_PRIMA VARCHAR(50),
    IN P_I_DESCRIPCION_MATERIA_PRIMA VARCHAR (200),
    IN P_I_ID_EMPLEADO_FK_MATERIA_PRIMA INT,
    IN P_I_ESTADO_MATERIA_PRIMA BOOLEAN
)
BEGIN
    INSERT INTO MATERIA_PRIMA(NOMBRE_MATERIA_PRIMA,FECHA_VENCIMIENTO_MATERIA_PRIMA,TIPO_DE_MEDIDA,CANTIDAD_EXIST_MATERIA_PRIMA,MARCA_MATERIA_PRIMA,
    PRESENTACION_MATERIA_PRIMA,DESCRIPCION_MATERIA_PRIMA,ID_EMPLEADO_FK_MATERIA_PRIMA,ESTADO_MATERIA_PRIMA)
    VALUES(P_I_NOMBRE_MATERIA_PRIMA,P_I_FECHA_VENCIMIENTO_MATERIA_PRIMA,P_I_TIPO_DE_MEDIDA,P_I_CANTIDAD_EXIST_MATERIA_PRIMA,P_I_MARCA_MATERIA_PRIMA,
    P_I_PRESENTACION_MATERIA_PRIMA,P_I_DESCRIPCION_MATERIA_PRIMA,P_I_ID_EMPLEADO_FK_MATERIA_PRIMA,P_I_ESTADO_MATERIA_PRIMA);
END $

CALL INSERTAR_MATERIA_PRIMA('HARINA', '2026-01-15', 'GRAMOS', 300,'HARINAS DEL VALLE','BULTO 50KG','HARINA PARA PANADERIA',5,1);
SELECT * FROM MATERIA_PRIMA;

/*📜PROCEDIMIENTO INSERTAR FACTURA COMPRA📜
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_FACTURA_COMPRA
(
    IN P_I_TOTAL_FACTURA_COMPRA BIGINT,
    IN P_I_FECHA_HORA_FACTURA_COMPRA DATETIME,
    IN P_I_DESCRIPCION_FACTURA_COMPRA VARCHAR (200),
    IN P_I_ID_EMPLEADO_FK_FACTURA_COMPRA INT,
    IN P_I_ID_PROVEEDOR_FK_FACTURA_COMPRA INT,
    IN P_I_ESTADO_FACTURA_COMPRA VARCHAR(20)
)
BEGIN
    INSERT INTO FACTURA_COMPRA (TOTAL_FACTURA_COMPRA,FECHA_HORA_FACTURA_COMPRA,DESCRIPCION_FACTURA_COMPRA,ID_EMPLEADO_FK_FACTURA_COMPRA,
    ID_PROVEEDOR_FK_FACTURA_COMPRA,ESTADO_FACTURA_COMPRA)
    VALUES(P_I_TOTAL_FACTURA_COMPRA,P_I_FECHA_HORA_FACTURA_COMPRA,P_I_DESCRIPCION_FACTURA_COMPRA,P_I_ID_EMPLEADO_FK_FACTURA_COMPRA,
    P_I_ID_PROVEEDOR_FK_FACTURA_COMPRA,P_I_ESTADO_FACTURA_COMPRA);
END $

CALL INSERTAR_FACTURA_COMPRA(100000, NOW(), 'COMPRA HARINA', 5, 5 , 'PAGADA');
SELECT * FROM FACTURA_COMPRA;

/*📰PROCEDIMIENTO INSERTAR DETALLE_FACTURA_COMPRA_MATERIA_PRIMA📰
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA
(
    IN P_I_ID_DETALLE_FAC_MAT_PRIM INT,
    IN P_I_CANTIDAD_MATERIA_PRIMA_COMPRADA BIGINT,
    IN P_I_SUB_TOTAL_MATERIA_PRIMA_COMPRADA BIGINT,
    IN P_I_ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA BIGINT,
    IN P_I_ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA BIGINT,
    IN P_I_ESTADO_DETALLE_COMPRA_MATERIA_PRIMA BOOLEAN
)
BEGIN
    INSERT INTO DETALLE_FACTURA_COMPRA_MATERIA_PRIMA
    (ID_DETALLE_FAC_MAT_PRIM,CANTIDAD_MATERIA_PRIMA_COMPRADA,SUB_TOTAL_MATERIA_PRIMA_COMPRADA,
     ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA,ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA,ESTADO_DETALLE_COMPRA_MATERIA_PRIMA)
    VALUES 
    (P_I_ID_DETALLE_FAC_MAT_PRIM,P_I_CANTIDAD_MATERIA_PRIMA_COMPRADA,P_I_SUB_TOTAL_MATERIA_PRIMA_COMPRADA,
     P_I_ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA,P_I_ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA,P_I_ESTADO_DETALLE_COMPRA_MATERIA_PRIMA);
END $

CALL INSERTAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA(5,300,50000,5,5,1);
SELECT * FROM DETALLE_FACTURA_COMPRA_MATERIA_PRIMA;

/*🍮PROCEDIMIENTO INSERTAR DETALLE_COMPRA_PRODUCTO🍮
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_COMPRA_PRODUCTO
(
    IN P_I_ID_DETALLE_COMPRA_PRODUCTO INT,
    IN P_I_CANTIDAD_PRODUCTO_COMPRADO BIGINT,
    IN P_I_SUB_TOTAL_PRODUCTO_COMPRADO BIGINT,
    IN P_I_ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO BIGINT,
    IN P_I_ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO BIGINT,
    IN P_I_ESTADO_DETALLE_COMPRA_PRODUCTO BOOLEAN
)
BEGIN
    INSERT INTO DETALLE_COMPRA_PRODUCTO 
    (ID_DETALLE_COMPRA_PRODUCTO,CANTIDAD_PRODUCTO_COMPRADO,SUB_TOTAL_PRODUCTO_COMPRADO,
     ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO,ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO,ESTADO_DETALLE_COMPRA_PRODUCTO)
    VALUES 
    (P_I_ID_DETALLE_COMPRA_PRODUCTO,P_I_CANTIDAD_PRODUCTO_COMPRADO,P_I_SUB_TOTAL_PRODUCTO_COMPRADO,
     P_I_ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO,P_I_ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO,P_I_ESTADO_DETALLE_COMPRA_PRODUCTO);
END $

CALL INSERTAR_DETALLE_COMPRA_PRODUCTO(5,300,50000,5,7700055,1);
SELECT * FROM DETALLE_COMPRA_PRODUCTO;

/*🍲PROCEDIMIENTO INSERTAR PRODUCCION🍲
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE INSERTAR_PRODUCCION
(
    IN P_I_NOMBRE_PRODUCCION VARCHAR(50),
    IN P_I_CANT_PRODUCCION BIGINT,
    IN P_I_DESCRIPCION_PRODUCCION VARCHAR(200),
    IN P_I_MATERIA_PRIMA_GASTADA BIGINT,
    IN P_I_ID_MATERIA_PRIMA_FK_PRODUCCION BIGINT,
    IN P_I_ID_PRODUCTO_FK_MATERIA_PRIMA BIGINT,
    IN P_I_ID_EMPLEADO_FK_PRODUCCION INT,
    IN P_I_ESTADO_PRODUCCION BOOLEAN
)       
BEGIN 
    INSERT INTO PRODUCCION 
    (NOMBRE_PRODUCCION,CANT_PRODUCCION,DESCRIPCION_PRODUCCION,MATERIA_PRIMA_GASTADA,ID_MATERIA_PRIMA_FK_PRODUCCION,
     ID_PRODUCTO_FK_MATERIA_PRIMA,ID_EMPLEADO_FK_PRODUCCION,ESTADO_PRODUCCION)
    VALUES 
    (P_I_NOMBRE_PRODUCCION,P_I_CANT_PRODUCCION,P_I_DESCRIPCION_PRODUCCION,P_I_MATERIA_PRIMA_GASTADA,P_I_ID_MATERIA_PRIMA_FK_PRODUCCION,
     P_I_ID_PRODUCTO_FK_MATERIA_PRIMA,P_I_ID_EMPLEADO_FK_PRODUCCION,P_I_ESTADO_PRODUCCION);
END $

CALL INSERTAR_PRODUCCION('PRUEBA',20,'PRODU',10,5,7700055,5,1);
SELECT * FROM PRODUCCION;
