USE PROYECTO_WYK;
														/*PROCEDIMINETOS DE CONSULTAR*/
                                                        
                                                        /*👮‍PROCEDIMIENTO CONSULTAR CARGO👮‍
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE CONSULTAR_CARGO()
BEGIN
	SELECT*FROM CARGO;
END	$

														/*🤴PROCEDIMIENTO CONSULTAR USUARIO👸
_____________________________________________________________________________________________________________________________________________________*/	
DELIMITER $
CREATE PROCEDURE CONSULTAR_USUARIO()
BEGIN
	SELECT*FROM USUARIO;
END	$

														/*👩‍🍳PROCEDIMIENTO CONSULTAR EMPLEADO👨‍🍳
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE CONSULTAR_EMPLEADO()
BEGIN
	SELECT
		E.ID_EMPLEADO,
		E.CC_EMPLEADO,
        E.NOMBRE_EMPLEADO,
        E.RH_EMPLEADO,
        E.TEL_EMPLEADO,
        E.EMAIL_EMPLEADO,
        E.ID_CARGO_FK_EMPLEADO,
        C.NOMBRE_CARGO,
        E.ID_USUARIO_FK_EMPLEADO,
        US.NOMBRE_USUARIO,
        E.ESTADO_EMPLEADO
    FROM EMPLEADO E
    INNER JOIN CARGO C ON E.ID_CARGO_FK_EMPLEADO = C.ID_CARGO
    INNER JOIN USUARIO US ON E.ID_USUARIO_FK_EMPLEADO = US.ID_USUARIO;
END	$

														/*👦PROCEDIMIENTO CONSULTAR CLIENTE👦
_____________________________________________________________________________________________________________________________________________________*/                                                      
DELIMITER $
CREATE PROCEDURE CONSULTAR_CLIENTE()
BEGIN
	SELECT
		C.ID_CLIENTE,
		C.NUM_DOCUMENTO_CLIENTE,
		C.TIPO_DOCUMENTO_CLIENTE,
		C.NOMBRE_CLIENTE,
		C.TEL_CLIENTE,
		C.EMAIL_CLIENTE,
		C.ID_USUARIO_FK_CLIENTE,
		US.NOMBRE_USUARIO,
		C.ESTADO_CLIENTE
	FROM CLIENTE C
	INNER JOIN USUARIO US ON C.ID_USUARIO_FK_CLIENTE = US.ID_USUARIO;
END $

													/*🥐PROCEDIMIENTO CONSULTAR PRODUCTO🥐
_____________________________________________________________________________________________________________________________________________________*/    
CREATE PROCEDURE CONSULTAR_PRODUCTO()
BEGIN
	SELECT
		P.ID_PRODUCTO,
		P.NOMBRE_PRODUCTO,
		P.VALOR_UNITARIO_PRODUCTO,
		P.CANT_EXIST_PRODUCTO,
		P.FECHA_VENCIMIENTO_PRODUCTO,
		P.TIPO_PRODUCTO_GENERAL,
		P.TIPO_PRODUCTO_ESPECIFICO,
		P.MARCA_PRODUCTO,
		P.ID_EMPLEADO_FK_PRODUCTO,
		E.NOMBRE_EMPLEADO,
		P.ESTADO_PRODUCTO
	FROM PRODUCTO P
	INNER JOIN EMPLEADO E ON P.ID_EMPLEADO_FK_PRODUCTO = E.ID_EMPLEADO;
END $

														/*🚲PROCEDIMIENTO CONSULTAR VENTA🚲
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE CONSULTAR_VENTA()
BEGIN
	SELECT
		V.ID_VENTA,
		V.FECHA_HORA_VENTA,
		V.TOTAL_VENTA,
		V.NUMERO_MESA,
		V.DESCRIPCION,
		V.ESTADO_VENTA,
		V.ID_EMPLEADO_FK,
		E.NOMBRE_EMPLEADO AS NOMBRE_EMPLEADO_VENTA,
		V.ID_CLIENTE_FK,
		CL.NOMBRE_CLIENTE
	FROM VENTA V
	INNER JOIN EMPLEADO E ON V.ID_EMPLEADO_FK = E.ID_EMPLEADO
	LEFT JOIN CLIENTE CL ON V.ID_CLIENTE_FK = CL.ID_CLIENTE;
END $

														/*👩‍💼PROCEDIMIENTO CONSULTAR DETALLE_VENTA👨‍💼
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE CONSULTAR_DETALLE_VENTA()
BEGIN
	SELECT
		DV.ID_DETALLE_VENTA,
		DV.CANTIDAD,
		DV.SUB_TOTAL,
		DV.ID_VENTA_FK,
		V.TOTAL_VENTA,
		DV.ID_PRODUCTO_FK,
		P.NOMBRE_PRODUCTO
	FROM DETALLE_VENTA DV
	INNER JOIN VENTA V ON DV.ID_VENTA_FK = V.ID_VENTA
	INNER JOIN PRODUCTO P ON DV.ID_PRODUCTO_FK = P.ID_PRODUCTO;
END $

														/*👩‍💼PROCEDIMIENTO CONSULTAR AJUSTE_INVENTARIO👨‍💼
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE CONSULTAR_AJUSTE_INVENTARIO()
BEGIN
	SELECT
		AI.ID_AJUSTE,
		AI.ID_PRODUCTO_FK,
		P.NOMBRE_PRODUCTO,
		AI.TIPO_AJUSTE,
		AI.CANTIDAD_AJUSTADA,
		AI.FECHA_AJUSTE,
		AI.DESCRIPCION,
		AI.ID_EMPLEADO_FK,
		E.NOMBRE_EMPLEADO AS NOMBRE_EMPLEADO_AJUSTE
	FROM AJUSTE_INVENTARIO AI
	INNER JOIN PRODUCTO P ON AI.ID_PRODUCTO_FK = P.ID_PRODUCTO
	INNER JOIN EMPLEADO E ON AI.ID_EMPLEADO_FK = E.ID_EMPLEADO;
END $

														/*👩‍💼PROCEDIMIENTO CONSULTAR CONSULTAR_PROVEEDOR👨‍💼
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE CONSULTAR_PROVEEDOR()
BEGIN
	SELECT
		PR.ID_PROVEEDOR,
		PR.CC_PROVEEDOR,
		PR.NOMBRE_PROVEEDOR,
		PR.TEL_PROVEEDOR,
		PR.EMAIL_PROVEEDOR,
		PR.ID_EMPLEADO_FK_PROVEEDOR,
		E.NOMBRE_EMPLEADO,
		PR.ESTADO_PROVEEDOR
	FROM PROVEEDOR PR
	INNER JOIN EMPLEADO E ON PR.ID_EMPLEADO_FK_PROVEEDOR = E.ID_EMPLEADO;
END $

														/*🥣PROCEDIMIENTO CONSULTAR MATERIA PRIMA🥣
_____________________________________________________________________________________________________________________________________________________*/
DELIMITER $
CREATE PROCEDURE CONSULTAR_MATERIA_PRIMA()
BEGIN
	SELECT
		MP.ID_MATERIA_PRIMA,
		MP.NOMBRE_MATERIA_PRIMA,
		MP.FECHA_VENCIMIENTO_MATERIA_PRIMA,
		MP.TIPO_DE_MEDIDA,
		MP.CANTIDAD_EXIST_MATERIA_PRIMA,
		MP.MARCA_MATERIA_PRIMA,
		MP.PRESENTACION_MATERIA_PRIMA,
		MP.DESCRIPCION_MATERIA_PRIMA,
		MP.ID_EMPLEADO_FK_MATERIA_PRIMA,
		E.NOMBRE_EMPLEADO,
		MP.ESTADO_MATERIA_PRIMA
	FROM MATERIA_PRIMA MP
	INNER JOIN EMPLEADO E ON MP.ID_EMPLEADO_FK_MATERIA_PRIMA = E.ID_EMPLEADO;
END $

														/*📜PROCEDIMIENTO CONSULTAR FACTURA COMPRA📜
_____________________________________________________________________________________________________________________________________________________*/ 
DELIMITER $
CREATE PROCEDURE CONSULTAR_FACTURA_COMPRA()
BEGIN
	SELECT
		FC.ID_FACTURA_COMPRA,
		FC.TOTAL_FACTURA_COMPRA,
		FC.FECHA_HORA_FACTURA_COMPRA,
		FC.DESCRIPCION_FACTURA_COMPRA,
		FC.ID_EMPLEADO_FK_FACTURA_COMPRA,
		E.NOMBRE_EMPLEADO,
		FC.ID_PROVEEDOR_FK_FACTURA_COMPRA,
		PR.NOMBRE_PROVEEDOR,
		FC.ESTADO_FACTURA_COMPRA
	FROM FACTURA_COMPRA FC
	INNER JOIN EMPLEADO E ON FC.ID_EMPLEADO_FK_FACTURA_COMPRA = E.ID_EMPLEADO
	INNER JOIN PROVEEDOR PR ON FC.ID_PROVEEDOR_FK_FACTURA_COMPRA = PR.ID_PROVEEDOR;
END $

														/*📰PROCEDIMIENTO CONSULTAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA📰
_____________________________________________________________________________________________________________________________________________________*/  
DELIMITER $
CREATE PROCEDURE CONSULTAR_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA()
BEGIN
	SELECT
		DFCMP.ID_DETALLE_FAC_MAT_PRIM,
		DFCMP.CANTIDAD_MATERIA_PRIMA_COMPRADA,
		DFCMP.SUB_TOTAL_MATERIA_PRIMA_COMPRADA,
		DFCMP.ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA,
		FC.TOTAL_FACTURA_COMPRA,
		DFCMP.ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA,
		MP.NOMBRE_MATERIA_PRIMA,
		DFCMP.ESTADO_DETALLE_COMPRA_MATERIA_PRIMA
	FROM DETALLE_FACTURA_COMPRA_MATERIA_PRIMA DFCMP
	INNER JOIN FACTURA_COMPRA FC ON DFCMP.ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA = FC.ID_FACTURA_COMPRA
	INNER JOIN MATERIA_PRIMA MP ON DFCMP.ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA = MP.ID_MATERIA_PRIMA;
END $
														/*🍮PROCEDIMIENTO CONSULTAR_DETALLE_COMPRA_PRODUCTO🍮
_____________________________________________________________________________________________________________________________________________________*/    
DELIMITER $
CREATE PROCEDURE CONSULTAR_DETALLE_COMPRA_PRODUCTO()
BEGIN
	SELECT
		DCP.ID_DETALLE_COMPRA_PRODUCTO,
		DCP.CANTIDAD_PRODUCTO_COMPRADO,
		DCP.SUB_TOTAL_PRODUCTO_COMPRADO,
		DCP.ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO,
		FC.TOTAL_FACTURA_COMPRA,
		DCP.ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO,
		P.NOMBRE_PRODUCTO,
		DCP.ESTADO_DETALLE_COMPRA_PRODUCTO
	FROM DETALLE_COMPRA_PRODUCTO DCP
	INNER JOIN FACTURA_COMPRA FC ON DCP.ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO = FC.ID_FACTURA_COMPRA
	INNER JOIN PRODUCTO P ON DCP.ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO = P.ID_PRODUCTO;
END $

														/*🍲PRECEDIMIENTO CONSULTAR PRODUCCION🍲
_____________________________________________________________________________________________________________________________________________________*/  
DELIMITER $
CREATE PROCEDURE CONSULTAR_PRODUCCION()
BEGIN
	SELECT
		PR.ID_PRODUCCION,
		PR.NOMBRE_PRODUCCION,
		PR.CANT_PRODUCCION,
		PR.DESCRIPCION_PRODUCCION,
		PR.MATERIA_PRIMA_GASTADA,
		PR.ID_MATERIA_PRIMA_FK_PRODUCCION,
		MP.NOMBRE_MATERIA_PRIMA,
		PR.ID_PRODUCTO_FK_MATERIA_PRIMA,
		P.NOMBRE_PRODUCTO,
		PR.ID_EMPLEADO_FK_PRODUCCION,
		E.NOMBRE_EMPLEADO,
		PR.ESTADO_PRODUCCION
	FROM PRODUCCION PR
	INNER JOIN MATERIA_PRIMA MP ON PR.ID_MATERIA_PRIMA_FK_PRODUCCION = MP.ID_MATERIA_PRIMA
	INNER JOIN PRODUCTO P ON PR.ID_PRODUCTO_FK_MATERIA_PRIMA = P.ID_PRODUCTO
	INNER JOIN EMPLEADO E ON PR.ID_EMPLEADO_FK_PRODUCCION = E.ID_EMPLEADO;
END $

DELIMITER ;
