CREATE DATABASE PROYECTO_WYK;
USE PROYECTO_WYK;

CREATE TABLE CARGO
(
    ID_CARGO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE_CARGO VARCHAR(50) NOT NULL,
    ESTADO_CARGO BOOLEAN NOT NULL
);

CREATE TABLE USUARIO 
(
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE_USUARIO VARCHAR (50) UNIQUE NOT NULL,
    PASSWORD_USUARIO VARCHAR (150) NOT NULL,
    FECHA_REGISTRO DATETIME NOT NULL,
    FECHA_ULTIMA_SESION DATETIME NOT NULL,
    ROL ENUM('EMPLEADO','ADMINISTRADOR','CLIENTE') NOT NULL,
    ESTADO_USUARIO BOOLEAN NOT NULL
);

CREATE TABLE EMPLEADO
(
    ID_EMPLEADO  INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CC_EMPLEADO BIGINT UNIQUE NOT NULL,
    NOMBRE_EMPLEADO VARCHAR(50) NOT NULL,
    RH_EMPLEADO VARCHAR(10) NOT NULL,
    TEL_EMPLEADO BIGINT NOT NULL,
    EMAIL_EMPLEADO VARCHAR(50) NOT NULL,
    ID_CARGO_FK_EMPLEADO INT NOT NULL,
    CONSTRAINT ID_CARGO_FK_EMPLEADO FOREIGN KEY (ID_CARGO_FK_EMPLEADO) REFERENCES CARGO (ID_CARGO),
    ID_USUARIO_FK_EMPLEADO INT NOT NULL,
    CONSTRAINT ID_USUARIO_FK_EMPLEADO FOREIGN KEY (ID_USUARIO_FK_EMPLEADO) REFERENCES USUARIO (ID_USUARIO),
    ESTADO_EMPLEADO BOOLEAN NOT NULL
);

CREATE TABLE CLIENTE 
(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NUM_DOCUMENTO_CLIENTE BIGINT UNIQUE NOT NULL,
    TIPO_DOCUMENTO_CLIENTE ENUM ('TI','CC','CE') NOT NULL,
    NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
    TEL_CLIENTE BIGINT NOT NULL,
    EMAIL_CLIENTE VARCHAR(50) NOT NULL,
    ID_USUARIO_FK_CLIENTE INT NOT NULL,
    CONSTRAINT ID_USUARIO_FK_CLIENTE FOREIGN KEY (ID_USUARIO_FK_CLIENTE) REFERENCES USUARIO (ID_USUARIO),
    ESTADO_CLIENTE BOOLEAN NOT NULL
);

CREATE TABLE PRODUCTO
(
	ID_PRODUCTO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(50) UNIQUE NOT NULL,
	VALOR_UNITARIO_PRODUCTO BIGINT NOT NULL,
	CANT_EXIST_PRODUCTO BIGINT NOT NULL,
	FECHA_VENCIMIENTO_PRODUCTO DATE NOT NULL,
	TIPO_PRODUCTO_GENERAL ENUM('PANADERIA','PASTELERIA','VIBERES') NOT NULL,
	TIPO_PRODUCTO_ESPECIFICO VARCHAR(50) NOT NULL,
	MARCA_PRODUCTO VARCHAR(50) NOT NULL,
	ID_EMPLEADO_FK_PRODUCTO INT NOT NULL,
	FOREIGN KEY (ID_EMPLEADO_FK_PRODUCTO) REFERENCES EMPLEADO (ID_EMPLEADO),
	ESTADO_PRODUCTO BOOLEAN NOT NULL
);

CREATE TABLE VENTA (
    ID_VENTA BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FECHA_HORA_VENTA DATETIME NOT NULL,
    TOTAL_VENTA BIGINT NOT NULL,
    NUMERO_MESA INT,
    DESCRIPCION VARCHAR(200) NULL,
    ESTADO_VENTA ENUM('PENDIENTE', 'PAGADA', 'CANCELADA') NOT NULL,
    ID_EMPLEADO_FK INT NOT NULL,
    FOREIGN KEY (ID_EMPLEADO_FK) REFERENCES EMPLEADO (ID_EMPLEADO),
    ID_CLIENTE_FK INT,
    FOREIGN KEY (ID_CLIENTE_FK) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE DETALLE_VENTA (
    ID_DETALLE_VENTA INT PRIMARY KEY AUTO_INCREMENT,
    CANTIDAD BIGINT NOT NULL,
    SUB_TOTAL BIGINT NOT NULL,
    ID_VENTA_FK BIGINT NOT NULL,
    FOREIGN KEY (ID_VENTA_FK) REFERENCES VENTA (ID_VENTA),
    ID_PRODUCTO_FK BIGINT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE AJUSTE_INVENTARIO (
    ID_AJUSTE INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCTO_FK BIGINT NOT NULL,
    TIPO_AJUSTE ENUM('DAÑADO', 'ROBO', 'PERDIDA', 'CADUCADO', 'MUESTRA') NOT NULL,
    CANTIDAD_AJUSTADA INT NOT NULL,
    FECHA_AJUSTE DATETIME NOT NULL,
    DESCRIPCION VARCHAR(255),
    ID_EMPLEADO_FK INT NOT NULL,
    FOREIGN KEY (ID_PRODUCTO_FK) REFERENCES PRODUCTO (ID_PRODUCTO),
    FOREIGN KEY (ID_EMPLEADO_FK) REFERENCES EMPLEADO (ID_EMPLEADO)
);

CREATE TABLE PROVEEDOR 
(
	ID_PROVEEDOR INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CC_PROVEEDOR BIGINT UNIQUE NOT NULL,
	NOMBRE_PROVEEDOR VARCHAR (50) NOT NULL,
	TEL_PROVEEDOR BIGINT NOT NULL,
	EMAIL_PROVEEDOR VARCHAR (50) NOT NULL,
	ID_EMPLEADO_FK_PROVEEDOR INT NOT NULL,
	FOREIGN KEY (ID_EMPLEADO_FK_PROVEEDOR) REFERENCES EMPLEADO (ID_EMPLEADO),
	ESTADO_PROVEEDOR BOOLEAN NOT NULL
);

CREATE TABLE MATERIA_PRIMA
(
	ID_MATERIA_PRIMA BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_MATERIA_PRIMA VARCHAR (50) NOT NULL,
	FECHA_VENCIMIENTO_MATERIA_PRIMA DATE NOT NULL,
	TIPO_DE_MEDIDA VARCHAR(50) NOT NULL,
	CANTIDAD_EXIST_MATERIA_PRIMA BIGINT NOT NULL,
	MARCA_MATERIA_PRIMA VARCHAR(50) NOT NULL,
	PRESENTACION_MATERIA_PRIMA VARCHAR (50) NOT NULL,
	DESCRIPCION_MATERIA_PRIMA VARCHAR(200) NOT NULL,
	ID_EMPLEADO_FK_MATERIA_PRIMA INT NOT NULL,
	FOREIGN KEY (ID_EMPLEADO_FK_MATERIA_PRIMA) REFERENCES EMPLEADO (ID_EMPLEADO),
	ESTADO_MATERIA_PRIMA BOOLEAN NOT NULL
);

CREATE TABLE FACTURA_COMPRA
(
	ID_FACTURA_COMPRA BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	TOTAL_FACTURA_COMPRA BIGINT NOT NULL,
	FECHA_HORA_FACTURA_COMPRA DATETIME NOT NULL,
	DESCRIPCION_FACTURA_COMPRA VARCHAR (200) NOT NULL,
	ID_EMPLEADO_FK_FACTURA_COMPRA INT NOT NULL,
	FOREIGN KEY (ID_EMPLEADO_FK_FACTURA_COMPRA) REFERENCES EMPLEADO (ID_EMPLEADO),
	ID_PROVEEDOR_FK_FACTURA_COMPRA INT NOT NULL,
	FOREIGN KEY (ID_PROVEEDOR_FK_FACTURA_COMPRA) REFERENCES PROVEEDOR (ID_PROVEEDOR),
	ESTADO_FACTURA_COMPRA ENUM('PENDIENTE','PAGADA','CANCELADA') NOT NULL
);

CREATE TABLE DETALLE_FACTURA_COMPRA_MATERIA_PRIMA
(
	ID_DETALLE_FAC_MAT_PRIM INT PRIMARY KEY NOT NULL,
	CANTIDAD_MATERIA_PRIMA_COMPRADA BIGINT NOT NULL,
	SUB_TOTAL_MATERIA_PRIMA_COMPRADA BIGINT NOT NULL,
	ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA BIGINT NOT NULL,
	FOREIGN KEY (ID_FACTURA_COMPRA_FK_DET_FACT_COMPRA_MATERIA_PRIMA) REFERENCES FACTURA_COMPRA (ID_FACTURA_COMPRA),
	ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA BIGINT NOT NULL,
	FOREIGN KEY (ID_MATERIA_PRIMA_FK_DET_FACT_COMPRA_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA),
	ESTADO_DETALLE_COMPRA_MATERIA_PRIMA BOOLEAN NOT NULL
);

CREATE TABLE DETALLE_COMPRA_PRODUCTO
(
	ID_DETALLE_COMPRA_PRODUCTO INT PRIMARY KEY NOT NULL,
	CANTIDAD_PRODUCTO_COMPRADO BIGINT NOT NULL,
	SUB_TOTAL_PRODUCTO_COMPRADO BIGINT NOT NULL,
	ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO BIGINT NOT NULL,
	FOREIGN KEY (ID_FACTURA_COMPRA_FK_DET_COMPRA_PRODUCTO) REFERENCES FACTURA_COMPRA (ID_FACTURA_COMPRA),
	ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO BIGINT NOT NULL,
	FOREIGN KEY (ID_PRODUCTO_FK_DET_COMPRA_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
	ESTADO_DETALLE_COMPRA_PRODUCTO BOOLEAN NOT NULL
);

CREATE TABLE PRODUCCION
(
	ID_PRODUCCION BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_PRODUCCION VARCHAR (50) NOT NULL,
	CANT_PRODUCCION BIGINT NOT NULL,
	DESCRIPCION_PRODUCCION VARCHAR(200) NOT NULL,
	MATERIA_PRIMA_GASTADA BIGINT NOT NULL,
	ID_MATERIA_PRIMA_FK_PRODUCCION BIGINT NOT NULL,
	FOREIGN KEY (ID_MATERIA_PRIMA_FK_PRODUCCION) REFERENCES MATERIA_PRIMA (ID_MATERIA_PRIMA),
	ID_PRODUCTO_FK_MATERIA_PRIMA BIGINT NOT NULL,
	FOREIGN KEY (ID_PRODUCTO_FK_MATERIA_PRIMA) REFERENCES PRODUCTO (ID_PRODUCTO),
	ID_EMPLEADO_FK_PRODUCCION INT NOT NULL,
	FOREIGN KEY (ID_EMPLEADO_FK_PRODUCCION) REFERENCES EMPLEADO (ID_EMPLEADO),
	ESTADO_PRODUCCION BOOLEAN NOT NULL
);