USE PROYECTO_WYK;
DELIMITER $

-- PROCEDIMIENTO ACTUALIZAR ROL
CREATE PROCEDURE ACTUALIZAR_ROL (
    IN P_A_ID_ROL INT,
    IN P_A_ROL VARCHAR(50),
    IN P_A_CLASIFICACION VARCHAR(20),
    IN P_A_ESTADO_ROL BOOLEAN
)
BEGIN
    UPDATE ROL
    SET ROL = P_A_ROL,
        CLASIFICACION = P_A_CLASIFICACION,
        ESTADO_ROL = P_A_ESTADO_ROL
    WHERE ID_ROL = P_A_ID_ROL;
END $

-- PROCEDIMIENTO ACTUALIZAR USUARIO
CREATE PROCEDURE ACTUALIZAR_USUARIO (
    IN P_A_ID_USUARIO INT,
    IN P_A_NUM_DOC BIGINT,
    IN P_A_NOMBRE VARCHAR(50),
    IN P_A_PASSWORD_USUARIO VARCHAR(150),
    IN P_A_TEL_USUARIO BIGINT,
    IN P_A_EMAIL_USUARIO VARCHAR(50),
    IN P_A_FECHA_REGISTRO DATETIME,
    IN P_A_ROL_FK_USUARIO INT,
    IN P_A_ESTADO_USUARIO BOOLEAN
)
BEGIN
    UPDATE USUARIO
    SET NUM_DOC = P_A_NUM_DOC,
        NOMBRE = P_A_NOMBRE,
        PASSWORD_USUARIO = IF(P_A_PASSWORD_USUARIO IS NULL, PASSWORD_USUARIO, P_A_PASSWORD_USUARIO),
        TEL_USUARIO = P_A_TEL_USUARIO,
        EMAIL_USUARIO = P_A_EMAIL_USUARIO,
        FECHA_REGISTRO = IF(P_A_FECHA_REGISTRO IS NULL, FECHA_REGISTRO, P_A_FECHA_REGISTRO),
        ROL_FK_USUARIO = P_A_ROL_FK_USUARIO,
        ESTADO_USUARIO = P_A_ESTADO_USUARIO
    WHERE ID_USUARIO = P_A_ID_USUARIO;
END $

-- PROCEDIMIENTO ACTUALIZAR TAREA
CREATE PROCEDURE ACTUALIZAR_TAREA (
    IN P_A_ID_TAREA INT,
    IN P_A_TAREA VARCHAR(100),
    IN P_A_CATEGORIA VARCHAR(80),
    IN P_A_DESCRIPCION VARCHAR(250),
    IN P_A_TIEMPO_ESTIMADO_HORAS FLOAT,
    IN P_A_PRIORIDAD VARCHAR(10),
    IN P_A_ESTADO_TAREA VARCHAR(20),
    IN P_A_USUARIO_ASIGNADO_FK INT,
    IN P_A_USUARIO_CREADOR_FK INT
)
BEGIN
    UPDATE TAREA
    SET TAREA = P_A_TAREA,
        CATEGORIA = P_A_CATEGORIA,
        DESCRIPCION = P_A_DESCRIPCION,
        TIEMPO_ESTIMADO_HORAS = P_A_TIEMPO_ESTIMADO_HORAS,
        PRIORIDAD = P_A_PRIORIDAD,
        ESTADO_TAREA = P_A_ESTADO_TAREA,
        USUARIO_ASIGNADO_FK = P_A_USUARIO_ASIGNADO_FK,
        USUARIO_CREADOR_FK = P_A_USUARIO_CREADOR_FK
    WHERE ID_TAREA = P_A_ID_TAREA;
END $

-- PROCEDIMIENTO ACTUALIZAR PRODUCTO
CREATE PROCEDURE ACTUALIZAR_PRODUCTO (
    IN P_A_ID_PRODUCTO BIGINT,
    IN P_A_NOMBRE_PRODUCTO VARCHAR(50),
    IN P_A_VALOR_UNITARIO_PRODUCTO BIGINT,
    IN P_A_CANT_EXIST_PRODUCTO BIGINT,
    IN P_A_FECHA_VENCIMIENTO_PRODUCTO DATE,
    IN P_A_TIPO_PRODUCTO VARCHAR(20),
    IN P_A_ID_USUARIO_FK_PRODUCTO INT,
    IN P_A_ESTADO_PRODUCTO BOOLEAN
)
BEGIN
    UPDATE PRODUCTO
    SET NOMBRE_PRODUCTO = P_A_NOMBRE_PRODUCTO,
        VALOR_UNITARIO_PRODUCTO = P_A_VALOR_UNITARIO_PRODUCTO,
        CANT_EXIST_PRODUCTO = P_A_CANT_EXIST_PRODUCTO,
        FECHA_VENCIMIENTO_PRODUCTO = P_A_FECHA_VENCIMIENTO_PRODUCTO,
        TIPO_PRODUCTO = P_A_TIPO_PRODUCTO,
        ID_USUARIO_FK_PRODUCTO = P_A_ID_USUARIO_FK_PRODUCTO,
        ESTADO_PRODUCTO = P_A_ESTADO_PRODUCTO
    WHERE ID_PRODUCTO = P_A_ID_PRODUCTO;
END $

-- PROCEDIMIENTO ACTUALIZAR VENTA
CREATE PROCEDURE ACTUALIZAR_VENTA (
    IN P_A_ID_VENTA BIGINT,
    IN P_A_FECHA_HORA_VENTA DATETIME,
    IN P_A_TOTAL_VENTA BIGINT,
    IN P_A_NUMERO_MESA INT,
    IN P_A_DESCRIPCION VARCHAR(200),
    IN P_A_ESTADO_PEDIDO VARCHAR(15),
    IN P_A_ESTADO_PAGO VARCHAR(15)
)
BEGIN
    UPDATE VENTA
    SET FECHA_HORA_VENTA = P_A_FECHA_HORA_VENTA,
        TOTAL_VENTA = P_A_TOTAL_VENTA,
        NUMERO_MESA = P_A_NUMERO_MESA,
        DESCRIPCION = P_A_DESCRIPCION,
        ESTADO_PEDIDO = P_A_ESTADO_PEDIDO,
        ESTADO_PAGO = P_A_ESTADO_PAGO
    WHERE ID_VENTA = P_A_ID_VENTA;
END $

-- PROCEDIMIENTO ACTUALIZAR DETALLE_VENTA
CREATE PROCEDURE ACTUALIZAR_DETALLE_VENTA (
    IN P_A_ID_DETALLE_VENTA INT,
    IN P_A_CANTIDAD BIGINT,
    IN P_A_SUB_TOTAL BIGINT,
    IN P_A_ID_VENTA_FK_DET_VENTA BIGINT,
    IN P_A_ID_PRODUCTO_FK_DET_VENTA BIGINT
)
BEGIN
    UPDATE DETALLE_VENTA
    SET CANTIDAD = P_A_CANTIDAD,
        SUB_TOTAL = P_A_SUB_TOTAL,
        ID_VENTA_FK_DET_VENTA = P_A_ID_VENTA_FK_DET_VENTA,
        ID_PRODUCTO_FK_DET_VENTA = P_A_ID_PRODUCTO_FK_DET_VENTA
    WHERE ID_DETALLE_VENTA = P_A_ID_DETALLE_VENTA;
END $

-- PROCEDIMIENTO ACTUALIZAR AJUSTE_INVENTARIO
CREATE PROCEDURE ACTUALIZAR_AJUSTE_INVENTARIO (
    IN P_A_ID_AJUSTE INT,
    IN P_A_FECHA_AJUSTE DATETIME,
    IN P_A_TIPO_AJUSTE VARCHAR(20),
    IN P_A_CANTIDAD_AJUSTADA INT,
    IN P_A_DESCRIPCION VARCHAR(200),
    IN P_A_ID_PROD_FK_AJUSTE_INVENTARIO BIGINT,
    IN P_A_ID_USUARIO_FK_AJUSTE_INVENTARIO INT
)
BEGIN
    UPDATE AJUSTE_INVENTARIO
    SET FECHA_AJUSTE = P_A_FECHA_AJUSTE,
        TIPO_AJUSTE = P_A_TIPO_AJUSTE,
        CANTIDAD_AJUSTADA = P_A_CANTIDAD_AJUSTADA,
        DESCRIPCION = P_A_DESCRIPCION,
        ID_PROD_FK_AJUSTE_INVENTARIO = P_A_ID_PROD_FK_AJUSTE_INVENTARIO,
        ID_USUARIO_FK_AJUSTE_INVENTARIO = P_A_ID_USUARIO_FK_AJUSTE_INVENTARIO
    WHERE ID_AJUSTE = P_A_ID_AJUSTE;
END $

-- PROCEDIMIENTO ACTUALIZAR MATERIA_PRIMA
CREATE PROCEDURE ACTUALIZAR_MATERIA_PRIMA (
    IN P_A_ID_MATERIA_PRIMA BIGINT,
    IN P_A_NOMBRE_MATERIA_PRIMA VARCHAR(50),
    IN P_A_VALOR_UNITARIO_MAT_PRIMA BIGINT,
    IN P_A_FECHA_VENCIMIENTO_MATERIA_PRIMA DATE,
    IN P_A_CANTIDAD_EXIST_MATERIA_PRIMA BIGINT,
    IN P_A_PRESENTACION_MATERIA_PRIMA VARCHAR(50),
    IN P_A_DESCRIPCION_MATERIA_PRIMA VARCHAR(200),
    IN P_A_ID_USUARIO_FK_MATERIA_PRIMA INT,
    IN P_A_ESTADO_MATERIA_PRIMA BOOLEAN
)
BEGIN
    UPDATE MATERIA_PRIMA
    SET NOMBRE_MATERIA_PRIMA = P_A_NOMBRE_MATERIA_PRIMA,
		VALOR_UNITARIO_MAT_PRIMA = P_A_VALOR_UNITARIO_MAT_PRIMA,
        FECHA_VENCIMIENTO_MATERIA_PRIMA = P_A_FECHA_VENCIMIENTO_MATERIA_PRIMA,
        CANTIDAD_EXIST_MATERIA_PRIMA = P_A_CANTIDAD_EXIST_MATERIA_PRIMA,
        PRESENTACION_MATERIA_PRIMA = P_A_PRESENTACION_MATERIA_PRIMA,
        DESCRIPCION_MATERIA_PRIMA = P_A_DESCRIPCION_MATERIA_PRIMA,
        ID_USUARIO_FK_MATERIA_PRIMA = P_A_ID_USUARIO_FK_MATERIA_PRIMA,
        ESTADO_MATERIA_PRIMA = P_A_ESTADO_MATERIA_PRIMA
    WHERE ID_MATERIA_PRIMA = P_A_ID_MATERIA_PRIMA;
END $

-- PROCEDIMIENTO ACTUALIZAR COMPRA
CREATE PROCEDURE ACTUALIZAR_COMPRA (
    IN P_A_ID_COMPRA BIGINT,
    IN P_A_FECHA_HORA_COMPRA DATETIME,
    IN P_A_TIPO VARCHAR(20),
    IN P_A_TOTAL_COMPRA BIGINT,
    IN P_A_NOMBRE_PROVEEDOR VARCHAR(50),
    IN P_A_MARCA VARCHAR(50),
    IN P_A_TEL_PROVEEDOR BIGINT,
    IN P_A_EMAIL_PROVEEDOR VARCHAR(50),
    IN P_A_DESCRIPCION_COMPRA VARCHAR(200),
    IN P_A_ID_USUARIO_FK_COMPRA INT,
    IN P_A_ESTADO_FACTURA_COMPRA VARCHAR(20)
)
BEGIN
    UPDATE COMPRA
    SET FECHA_HORA_COMPRA = P_A_FECHA_HORA_COMPRA,
        TIPO = P_A_TIPO,
        TOTAL_COMPRA = P_A_TOTAL_COMPRA,
        NOMBRE_PROVEEDOR = P_A_NOMBRE_PROVEEDOR,
        MARCA = P_A_MARCA,
        TEL_PROVEEDOR = P_A_TEL_PROVEEDOR,
        EMAIL_PROVEEDOR = P_A_EMAIL_PROVEEDOR,
        DESCRIPCION_COMPRA = P_A_DESCRIPCION_COMPRA,
        ID_USUARIO_FK_COMPRA = P_A_ID_USUARIO_FK_COMPRA,
        ESTADO_FACTURA_COMPRA = P_A_ESTADO_FACTURA_COMPRA
    WHERE ID_COMPRA = P_A_ID_COMPRA;
END $

-- PROCEDIMIENTO ACTUALIZAR DETALLE_COMPRA_MATERIA_PRIMA
CREATE PROCEDURE ACTUALIZAR_DETALLE_COMPRA_MATERIA_PRIMA (
    IN P_A_ID_DET_COMPRA_MAT_PRIM INT,
    IN P_A_CANTIDAD_MAT_PRIMA_COMPRADA BIGINT,
    IN P_A_SUB_TOTAL_MAT_PRIMA_COMPRADA BIGINT,
    IN P_A_ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA BIGINT,
    IN P_A_ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA BIGINT,
    IN P_A_ESTADO_DET_COMPRA_MAT_PRIMA BOOLEAN
)
BEGIN
    UPDATE DETALLE_COMPRA_MATERIA_PRIMA
    SET CANTIDAD_MAT_PRIMA_COMPRADA = P_A_CANTIDAD_MAT_PRIMA_COMPRADA,
        SUB_TOTAL_MAT_PRIMA_COMPRADA = P_A_SUB_TOTAL_MAT_PRIMA_COMPRADA,
        ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA = P_A_ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA,
        ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA = P_A_ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA,
        ESTADO_DET_COMPRA_MAT_PRIMA = P_A_ESTADO_DET_COMPRA_MAT_PRIMA
    WHERE ID_DET_COMPRA_MAT_PRIM = P_A_ID_DET_COMPRA_MAT_PRIM;
END $

-- PROCEDIMIENTO ACTUALIZAR DETALLE_COMPRA_PRODUCTO
CREATE PROCEDURE ACTUALIZAR_DETALLE_COMPRA_PRODUCTO (
    IN P_A_ID_DET_COMPRA_PROD INT,
    IN P_A_CANTIDAD_PROD_COMPRADO BIGINT,
    IN P_A_SUB_TOTAL_PROD_COMPRADO BIGINT,
    IN P_A_ID_COMPRA_FK_DET_COMPRA_PROD BIGINT,
    IN P_A_ID_PROD_FK_DET_COMPRA_PROD BIGINT,
    IN P_A_ESTADO_DET_COMPRA_PROD BOOLEAN
)
BEGIN
    UPDATE DETALLE_COMPRA_PRODUCTO
    SET CANTIDAD_PROD_COMPRADO = P_A_CANTIDAD_PROD_COMPRADO,
        SUB_TOTAL_PROD_COMPRADO = P_A_SUB_TOTAL_PROD_COMPRADO,
        ID_COMPRA_FK_DET_COMPRA_PROD = P_A_ID_COMPRA_FK_DET_COMPRA_PROD,
        ID_PROD_FK_DET_COMPRA_PROD = P_A_ID_PROD_FK_DET_COMPRA_PROD,
        ESTADO_DET_COMPRA_PROD = P_A_ESTADO_DET_COMPRA_PROD
    WHERE ID_DET_COMPRA_PROD = P_A_ID_DET_COMPRA_PROD;
END $

-- PROCEDIMIENTO ACTUALIZAR PRODUCCION
CREATE PROCEDURE ACTUALIZAR_PRODUCCION (
    IN P_A_ID_PRODUCCION BIGINT,
    IN P_A_NOMBRE_PRODUCCION VARCHAR(50),
    IN P_A_CANT_PRODUCCION BIGINT,
    IN P_A_DESCRIPCION_PRODUCCION VARCHAR(200),
    IN P_A_ID_PRODUCTO_FK_PRODUCCION BIGINT,
    IN P_A_ID_USUARIO_FK_PRODUCCION INT,
    IN P_A_ESTADO_PRODUCCION VARCHAR(15)
)
BEGIN
    UPDATE PRODUCCION
    SET NOMBRE_PRODUCCION = P_A_NOMBRE_PRODUCCION,
        CANT_PRODUCCION = P_A_CANT_PRODUCCION,
        DESCRIPCION_PRODUCCION = P_A_DESCRIPCION_PRODUCCION,
        ID_PRODUCTO_FK_PRODUCCION = P_A_ID_PRODUCTO_FK_PRODUCCION,
        ID_USUARIO_FK_PRODUCCION = P_A_ID_USUARIO_FK_PRODUCCION,
        ESTADO_PRODUCCION = P_A_ESTADO_PRODUCCION
    WHERE ID_PRODUCCION = P_A_ID_PRODUCCION;
END $

-- PROCEDIMIENTO ACTUALIZAR DETALLE_PRODUCCION
CREATE PROCEDURE ACTUALIZAR_DETALLE_PRODUCCION (
    IN P_A_ID_DETALLE_PRODUCCION BIGINT,
    IN P_A_ID_PRODUCCION BIGINT,
    IN P_A_ID_MATERIA_PRIMA BIGINT,
    IN P_A_CANTIDAD_REQUERIDA DECIMAL(10,2)
)
BEGIN
    UPDATE DETALLE_PRODUCCION
    SET ID_PRODUCCION = P_A_ID_PRODUCCION,
        ID_MATERIA_PRIMA = P_A_ID_MATERIA_PRIMA,
        CANTIDAD_REQUERIDA = P_A_CANTIDAD_REQUERIDA
    WHERE ID_DETALLE_PRODUCCION = P_A_ID_DETALLE_PRODUCCION;
END $
