USE PROYECTO_WYK;
DELIMITER $

-- PROCEDIMIENTO CONSULTAR ROL
CREATE PROCEDURE CONSULTAR_ROL()
BEGIN
    SELECT 
        ID_ROL,
        ROL,
        CLASIFICACION,
        ESTADO_ROL
    FROM ROL;
END $

-- PROCEDIMIENTO CONSULTAR USUARIO
CREATE PROCEDURE CONSULTAR_USUARIO()
BEGIN
    SELECT 
        U.ID_USUARIO,
        U.NUM_DOC,
        U.NOMBRE,
        U.PASSWORD_USUARIO,
        U.TEL_USUARIO,
        U.EMAIL_USUARIO,
        U.FECHA_REGISTRO,
        U.ROL_FK_USUARIO,
        R.ROL AS NOMBRE_ROL,
        U.ESTADO_USUARIO
    FROM USUARIO U
    INNER JOIN ROL R ON U.ROL_FK_USUARIO = R.ID_ROL;
END $

-- PROCEDIMIENTO CONSULTAR TAREA
CREATE PROCEDURE CONSULTAR_TAREA()
BEGIN
    SELECT
        T.ID_TAREA,
        T.TAREA,
        T.CATEGORIA,
        T.DESCRIPCION,
        T.TIEMPO_ESTIMADO_HORAS,
        T.PRIORIDAD,
        T.ESTADO_TAREA,
        T.USUARIO_ASIGNADO_FK,
        UA.NOMBRE AS USUARIO_ASIGNADO,
        T.USUARIO_CREADOR_FK,
        UC.NOMBRE AS USUARIO_CREADOR
    FROM TAREA T
    INNER JOIN USUARIO UA ON T.USUARIO_ASIGNADO_FK = UA.ID_USUARIO
    INNER JOIN USUARIO UC ON T.USUARIO_CREADOR_FK = UC.ID_USUARIO;
END $

-- PROCEDIMIENTO CONSULTAR PRODUCTO
CREATE PROCEDURE CONSULTAR_PRODUCTO()
BEGIN
    SELECT 
        P.ID_PRODUCTO,
        P.NOMBRE_PRODUCTO,
        P.VALOR_UNITARIO_PRODUCTO,
        P.CANT_EXIST_PRODUCTO,
        P.FECHA_VENCIMIENTO_PRODUCTO,
        P.TIPO_PRODUCTO,
        P.ID_USUARIO_FK_PRODUCTO,
        U.NOMBRE AS USUARIO_REGISTRO,
        P.ESTADO_PRODUCTO
    FROM PRODUCTO P
    INNER JOIN USUARIO U ON P.ID_USUARIO_FK_PRODUCTO = U.ID_USUARIO;
END $

-- PROCEDIMIENTO CONSULTAR VENTA
CREATE PROCEDURE CONSULTAR_VENTA()
BEGIN
    SELECT 
        V.ID_VENTA,
        V.FECHA_HORA_VENTA,
        V.TOTAL_VENTA,
        V.NUMERO_MESA,
        V.DESCRIPCION,
        V.ID_USUARIO_FK_VENTA,
        U.NOMBRE AS USUARIO_VENTA,
        V.ESTADO_VENTA
    FROM VENTA V
    INNER JOIN USUARIO U ON V.ID_USUARIO_FK_VENTA = U.ID_USUARIO;
END $

-- PROCEDIMIENTO CONSULTAR DETALLE_VENTA
CREATE PROCEDURE CONSULTAR_DETALLE_VENTA()
BEGIN
    SELECT
        DV.ID_DETALLE_VENTA,
        DV.CANTIDAD,
        DV.SUB_TOTAL,
        DV.ID_VENTA_FK_DET_VENTA,
        V.ID_VENTA,
        DV.ID_PRODUCTO_FK_DET_VENTA,
        P.NOMBRE_PRODUCTO
    FROM DETALLE_VENTA DV
    INNER JOIN VENTA V ON DV.ID_VENTA_FK_DET_VENTA = V.ID_VENTA
    INNER JOIN PRODUCTO P ON DV.ID_PRODUCTO_FK_DET_VENTA = P.ID_PRODUCTO;
END $

-- PROCEDIMIENTO CONSULTAR AJUSTE_INVENTARIO
CREATE PROCEDURE CONSULTAR_AJUSTE_INVENTARIO()
BEGIN
    SELECT
        A.ID_AJUSTE,
        A.FECHA_AJUSTE,
        A.TIPO_AJUSTE,
        A.CANTIDAD_AJUSTADA,
        A.DESCRIPCION,
        A.ID_PROD_FK_AJUSTE_INVENTARIO,
        P.NOMBRE_PRODUCTO,
        A.ID_USUARIO_FK_AJUSTE_INVENTARIO,
        U.NOMBRE AS USUARIO_REGISTRO
    FROM AJUSTE_INVENTARIO A
    INNER JOIN PRODUCTO P ON A.ID_PROD_FK_AJUSTE_INVENTARIO = P.ID_PRODUCTO
    INNER JOIN USUARIO U ON A.ID_USUARIO_FK_AJUSTE_INVENTARIO = U.ID_USUARIO;
END $

-- PROCEDIMIENTO CONSULTAR MATERIA_PRIMA
CREATE PROCEDURE CONSULTAR_MATERIA_PRIMA()
BEGIN
    SELECT 
        M.ID_MATERIA_PRIMA,
        M.NOMBRE_MATERIA_PRIMA,
        M.FECHA_VENCIMIENTO_MATERIA_PRIMA,
        M.CANTIDAD_EXIST_MATERIA_PRIMA,
        M.PRESENTACION_MATERIA_PRIMA,
        M.DESCRIPCION_MATERIA_PRIMA,
        M.ID_USUARIO_FK_MATERIA_PRIMA,
        U.NOMBRE AS USUARIO_REGISTRO,
        M.ESTADO_MATERIA_PRIMA
    FROM MATERIA_PRIMA M
    INNER JOIN USUARIO U ON M.ID_USUARIO_FK_MATERIA_PRIMA = U.ID_USUARIO;
END $

-- PROCEDIMIENTO CONSULTAR COMPRA
CREATE PROCEDURE CONSULTAR_COMPRA()
BEGIN
    SELECT
        C.ID_COMPRA,
        C.FECHA_HORA_COMPRA,
        C.TIPO,
        C.TOTAL_COMPRA,
        C.NOMBRE_PROVEEDOR,
        C.MARCA,
        C.TEL_PROVEEDOR,
        C.EMAIL_PROVEEDOR,
        C.DESCRIPCION_COMPRA,
        C.ID_USUARIO_FK_COMPRA,
        U.NOMBRE AS USUARIO_REGISTRO,
        C.ESTADO_FACTURA_COMPRA
    FROM COMPRA C
    INNER JOIN USUARIO U ON C.ID_USUARIO_FK_COMPRA = U.ID_USUARIO;
END $

-- PROCEDIMIENTO CONSULTAR DETALLE_COMPRA_MATERIA_PRIMA
CREATE PROCEDURE CONSULTAR_DETALLE_COMPRA_MATERIA_PRIMA()
BEGIN
    SELECT
        D.ID_DET_COMPRA_MAT_PRIM,
        D.CANTIDAD_MAT_PRIMA_COMPRADA,
        D.SUB_TOTAL_MAT_PRIMA_COMPRADA,
        D.ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA,
        C.NOMBRE_PROVEEDOR,
        D.ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA,
        M.NOMBRE_MATERIA_PRIMA,
        D.ESTADO_DET_COMPRA_MAT_PRIMA
    FROM DETALLE_COMPRA_MATERIA_PRIMA D
    INNER JOIN COMPRA C ON D.ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA = C.ID_COMPRA
    INNER JOIN MATERIA_PRIMA M ON D.ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA = M.ID_MATERIA_PRIMA;
END $

-- PROCEDIMIENTO CONSULTAR DETALLE_COMPRA_PRODUCTO
CREATE PROCEDURE CONSULTAR_DETALLE_COMPRA_PRODUCTO()
BEGIN
    SELECT
        D.ID_DET_COMPRA_PROD,
        D.CANTIDAD_PROD_COMPRADO,
        D.SUB_TOTAL_PROD_COMPRADO,
        D.ID_COMPRA_FK_DET_COMPRA_PROD,
        C.NOMBRE_PROVEEDOR,
        D.ID_PROD_FK_DET_COMPRA_PROD,
        P.NOMBRE_PRODUCTO,
        D.ESTADO_DET_COMPRA_PROD
    FROM DETALLE_COMPRA_PRODUCTO D
    INNER JOIN COMPRA C ON D.ID_COMPRA_FK_DET_COMPRA_PROD = C.ID_COMPRA
    INNER JOIN PRODUCTO P ON D.ID_PROD_FK_DET_COMPRA_PROD = P.ID_PRODUCTO;
END $

-- PROCEDIMIENTO CONSULTAR RECETA
CREATE PROCEDURE CONSULTAR_RECETA()
BEGIN
    SELECT
        R.ID_RECETA,
        R.ID_PRODUCTO_FK_RECETA,
        P.NOMBRE_PRODUCTO,
        R.ID_MATERIA_PRIMA_FK_RECETA,
        M.NOMBRE_MATERIA_PRIMA,
        R.CANTIDAD_REQUERIDA,
        R.UNIDAD_RECETA
    FROM RECETA R
    INNER JOIN PRODUCTO P ON R.ID_PRODUCTO_FK_RECETA = P.ID_PRODUCTO
    INNER JOIN MATERIA_PRIMA M ON R.ID_MATERIA_PRIMA_FK_RECETA = M.ID_MATERIA_PRIMA;
END $

-- PROCEDIMIENTO CONSULTAR PRODUCCION
CREATE PROCEDURE CONSULTAR_PRODUCCION()
BEGIN
    SELECT
        P.ID_PRODUCCION,
        P.NOMBRE_PRODUCCION,
        P.CANT_PRODUCCION,
        P.DESCRIPCION_PRODUCCION,
        P.ID_PRODUCTO_FK_PRODUCCION,
        PR.NOMBRE_PRODUCTO,
        P.ID_USUARIO_FK_PRODUCCION,
        U.NOMBRE AS USUARIO_REGISTRO,
        P.ESTADO_PRODUCCION
    FROM PRODUCCION P
    INNER JOIN PRODUCTO PR ON P.ID_PRODUCTO_FK_PRODUCCION = PR.ID_PRODUCTO
    INNER JOIN USUARIO U ON P.ID_USUARIO_FK_PRODUCCION = U.ID_USUARIO;
END $

-- PROCEDIMIENTO CONSULTAR DETALLE_PRODUCCION
CREATE PROCEDURE CONSULTAR_DETALLE_PRODUCCION()
BEGIN
    SELECT
        D.ID_DETALLE_PRODUCCION,
        D.ID_PRODUCCION,
        PR.NOMBRE_PRODUCCION,
        D.ID_MATERIA_PRIMA,
        M.NOMBRE_MATERIA_PRIMA,
        D.CANTIDAD_REQUERIDA,
        D.CANTIDAD_USADA
    FROM DETALLE_PRODUCCION D
    INNER JOIN PRODUCCION PR ON D.ID_PRODUCCION = PR.ID_PRODUCCION
    INNER JOIN MATERIA_PRIMA M ON D.ID_MATERIA_PRIMA = M.ID_MATERIA_PRIMA;
END $
