USE PROYECTO_WYK;
DELIMITER $

-- PROCEDIMIENTO ELIMINAR ROL
CREATE PROCEDURE ELIMINAR_ROL (
    IN P_E_ID_ROL INT
)
BEGIN
    DELETE FROM ROL
    WHERE ID_ROL = P_E_ID_ROL;
END $

-- PROCEDIMIENTO ELIMINAR USUARIO
CREATE PROCEDURE ELIMINAR_USUARIO (
    IN P_E_ID_USUARIO INT
)
BEGIN
    DELETE FROM USUARIO
    WHERE ID_USUARIO = P_E_ID_USUARIO;
END $

-- PROCEDIMIENTO ELIMINAR TAREA
CREATE PROCEDURE ELIMINAR_TAREA (
    IN P_E_ID_TAREA INT
)
BEGIN
    DELETE FROM TAREA
    WHERE ID_TAREA = P_E_ID_TAREA;
END $

-- PROCEDIMIENTO ELIMINAR PRODUCTO
CREATE PROCEDURE ELIMINAR_PRODUCTO (
    IN P_E_ID_PRODUCTO BIGINT
)
BEGIN
    DELETE FROM PRODUCTO
    WHERE ID_PRODUCTO = P_E_ID_PRODUCTO;
END $

-- PROCEDIMIENTO ELIMINAR VENTA
CREATE PROCEDURE ELIMINAR_VENTA (
    IN P_E_ID_VENTA BIGINT
)
BEGIN
    DELETE FROM VENTA
    WHERE ID_VENTA = P_E_ID_VENTA;
END $

-- PROCEDIMIENTO ELIMINAR DETALLE_VENTA
CREATE PROCEDURE ELIMINAR_DETALLE_VENTA (
    IN P_E_ID_DETALLE_VENTA INT
)
BEGIN
    DELETE FROM DETALLE_VENTA
    WHERE ID_DETALLE_VENTA = P_E_ID_DETALLE_VENTA;
END $

-- PROCEDIMIENTO ELIMINAR AJUSTE_INVENTARIO
CREATE PROCEDURE ELIMINAR_AJUSTE_INVENTARIO (
    IN P_E_ID_AJUSTE INT
)
BEGIN
    DELETE FROM AJUSTE_INVENTARIO
    WHERE ID_AJUSTE = P_E_ID_AJUSTE;
END $

-- PROCEDIMIENTO ELIMINAR MATERIA_PRIMA
CREATE PROCEDURE ELIMINAR_MATERIA_PRIMA (
    IN P_E_ID_MATERIA_PRIMA BIGINT
)
BEGIN
    DELETE FROM MATERIA_PRIMA
    WHERE ID_MATERIA_PRIMA = P_E_ID_MATERIA_PRIMA;
END $

-- PROCEDIMIENTO ELIMINAR COMPRA
CREATE PROCEDURE ELIMINAR_COMPRA (
    IN P_E_ID_COMPRA BIGINT
)
BEGIN
    DELETE FROM COMPRA
    WHERE ID_COMPRA = P_E_ID_COMPRA;
END $

-- PROCEDIMIENTO ELIMINAR DETALLE_COMPRA_MATERIA_PRIMA
CREATE PROCEDURE ELIMINAR_DETALLE_COMPRA_MATERIA_PRIMA (
    IN P_E_ID_DET_COMPRA_MAT_PRIM INT
)
BEGIN
    DELETE FROM DETALLE_COMPRA_MATERIA_PRIMA
    WHERE ID_DET_COMPRA_MAT_PRIM = P_E_ID_DET_COMPRA_MAT_PRIM;
END $

-- PROCEDIMIENTO ELIMINAR DETALLE_COMPRA_PRODUCTO
CREATE PROCEDURE ELIMINAR_DETALLE_COMPRA_PRODUCTO (
    IN P_E_ID_DET_COMPRA_PROD INT
)
BEGIN
    DELETE FROM DETALLE_COMPRA_PRODUCTO
    WHERE ID_DET_COMPRA_PROD = P_E_ID_DET_COMPRA_PROD;
END $

-- PROCEDIMIENTO ELIMINAR PRODUCCION
CREATE PROCEDURE ELIMINAR_PRODUCCION (
    IN P_E_ID_PRODUCCION BIGINT
)
BEGIN
    DELETE FROM PRODUCCION
    WHERE ID_PRODUCCION = P_E_ID_PRODUCCION;
END $

-- PROCEDIMIENTO ELIMINAR DETALLE_PRODUCCION
CREATE PROCEDURE ELIMINAR_DETALLE_PRODUCCION (
    IN P_E_ID_DETALLE_PRODUCCION BIGINT
)
BEGIN
    DELETE FROM DETALLE_PRODUCCION
    WHERE ID_DETALLE_PRODUCCION = P_E_ID_DETALLE_PRODUCCION;
END $
