USE PROYECTO_WYK;

-- PROCEDIMIENTO INSERTAR ROL
DELIMITER $ 
CREATE PROCEDURE INSERTAR_ROL
(
    IN P_I_ROL VARCHAR(50),
    IN P_I_CLASIFICACION VARCHAR(20),
    IN P_I_ESTADO_ROL BOOLEAN
)
BEGIN
    INSERT INTO ROL (ROL, CLASIFICACION, ESTADO_ROL)
    VALUES (P_I_ROL, P_I_CLASIFICACION, P_I_ESTADO_ROL);
END $

-- PROCEDIMIENTO INSERTAR USUARIO
DELIMITER $
CREATE PROCEDURE INSERTAR_USUARIO
(
    IN P_I_NUM_DOC BIGINT,
    IN P_I_NOMBRE VARCHAR(50),
    IN P_I_PASSWORD_USUARIO VARCHAR(150),
    IN P_I_TEL_USUARIO BIGINT,
    IN P_I_EMAIL_USUARIO VARCHAR(50),
    IN P_I_FECHA_REGISTRO DATETIME,
    IN P_I_ROL_FK_USUARIO INT,
    IN P_I_ESTADO_USUARIO BOOLEAN
)
BEGIN
    INSERT INTO USUARIO (NUM_DOC, NOMBRE, PASSWORD_USUARIO, TEL_USUARIO, EMAIL_USUARIO, FECHA_REGISTRO, ROL_FK_USUARIO, ESTADO_USUARIO)
    VALUES (P_I_NUM_DOC, P_I_NOMBRE, P_I_PASSWORD_USUARIO, P_I_TEL_USUARIO, P_I_EMAIL_USUARIO, P_I_FECHA_REGISTRO, P_I_ROL_FK_USUARIO, P_I_ESTADO_USUARIO);
END $

-- PROCEDIMIENTO INSERTAR TAREA
DELIMITER $
CREATE PROCEDURE INSERTAR_TAREA
(
    IN P_I_TAREA VARCHAR(100),
    IN P_I_CATEGORIA VARCHAR(80),
    IN P_I_DESCRIPCION VARCHAR(250),
    IN P_I_TIEMPO_ESTIMADO_HORAS FLOAT,
    IN P_I_PRIORIDAD VARCHAR(10),
    IN P_I_ESTADO_TAREA VARCHAR(15),
    IN P_I_USUARIO_ASIGNADO_FK INT,
    IN P_I_USUARIO_CREADOR_FK INT
)
BEGIN
    INSERT INTO TAREA (TAREA, CATEGORIA, DESCRIPCION, TIEMPO_ESTIMADO_HORAS, PRIORIDAD, ESTADO_TAREA, USUARIO_ASIGNADO_FK, USUARIO_CREADOR_FK)
    VALUES (P_I_TAREA, P_I_CATEGORIA, P_I_DESCRIPCION, P_I_TIEMPO_ESTIMADO_HORAS, P_I_PRIORIDAD, P_I_ESTADO_TAREA, P_I_USUARIO_ASIGNADO_FK, P_I_USUARIO_CREADOR_FK);
END $

-- PROCEDIMIENTO INSERTAR PRODUCTO
DELIMITER $
CREATE PROCEDURE INSERTAR_PRODUCTO
(
    IN P_I_ID_PRODUCTO BIGINT,
    IN P_I_NOMBRE_PRODUCTO VARCHAR(50),
    IN P_I_VALOR_UNITARIO_PRODUCTO BIGINT,
    IN P_I_CANT_EXIST_PRODUCTO BIGINT,
    IN P_I_FECHA_VENCIMIENTO DATE,
    IN P_I_TIPO_PRODUCTO VARCHAR(20),
    IN P_I_ID_USUARIO_FK INT,
    IN P_I_ESTADO_PRODUCTO BOOLEAN
)
BEGIN
    INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE_PRODUCTO, VALOR_UNITARIO_PRODUCTO, CANT_EXIST_PRODUCTO, FECHA_VENCIMIENTO_PRODUCTO, TIPO_PRODUCTO, ID_USUARIO_FK_PRODUCTO, ESTADO_PRODUCTO)
    VALUES (P_I_ID_PRODUCTO, P_I_NOMBRE_PRODUCTO, P_I_VALOR_UNITARIO_PRODUCTO, P_I_CANT_EXIST_PRODUCTO, P_I_FECHA_VENCIMIENTO, P_I_TIPO_PRODUCTO, P_I_ID_USUARIO_FK, P_I_ESTADO_PRODUCTO);
END $

-- PROCEDIMIENTO INSERTAR VENTA
DELIMITER $
CREATE PROCEDURE INSERTAR_VENTA
(
    IN P_I_FECHA_HORA DATETIME,
    IN P_I_TOTAL BIGINT,
    IN P_I_NUMERO_MESA INT,
    IN P_I_DESCRIPCION VARCHAR(200),
    IN P_I_ID_USUARIO_FK INT,
    IN P_I_ESTADO_PEDIDO VARCHAR(15),
    IN P_I_ESTADO_PAGO VARCHAR(15)
)
BEGIN
    INSERT INTO VENTA (FECHA_HORA_VENTA, TOTAL_VENTA, NUMERO_MESA, DESCRIPCION, ID_USUARIO_FK_VENTA, ESTADO_PEDIDO, ESTADO_PAGO)
    VALUES (P_I_FECHA_HORA, P_I_TOTAL, P_I_NUMERO_MESA, P_I_DESCRIPCION, P_I_ID_USUARIO_FK, P_I_ESTADO_PEDIDO, P_I_ESTADO_PAGO);
END $

-- PROCEDIMIENTO INSERTAR DETALLE_VENTA
DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_VENTA
(
    IN P_I_CANTIDAD BIGINT,
    IN P_I_SUB_TOTAL BIGINT,
    IN P_I_ID_VENTA BIGINT,
    IN P_I_ID_PRODUCTO BIGINT
)
BEGIN
    INSERT INTO DETALLE_VENTA (CANTIDAD, SUB_TOTAL, ID_VENTA_FK_DET_VENTA, ID_PRODUCTO_FK_DET_VENTA)
    VALUES (P_I_CANTIDAD, P_I_SUB_TOTAL, P_I_ID_VENTA, P_I_ID_PRODUCTO);
END $

-- PROCEDIMIENTO INSERTAR AJUSTE_INVENTARIO
DELIMITER $
CREATE PROCEDURE INSERTAR_AJUSTE_INVENTARIO
(
    IN P_I_FECHA DATETIME,
    IN P_I_TIPO VARCHAR(15),
    IN P_I_CANTIDAD INT,
    IN P_I_DESCRIPCION VARCHAR(200),
    IN P_I_ID_PRODUCTO BIGINT,
    IN P_I_ID_USUARIO INT
)
BEGIN
    INSERT INTO AJUSTE_INVENTARIO (FECHA_AJUSTE, TIPO_AJUSTE, CANTIDAD_AJUSTADA, DESCRIPCION, ID_PROD_FK_AJUSTE_INVENTARIO, ID_USUARIO_FK_AJUSTE_INVENTARIO)
    VALUES (P_I_FECHA, P_I_TIPO, P_I_CANTIDAD, P_I_DESCRIPCION, P_I_ID_PRODUCTO, P_I_ID_USUARIO);
END $

-- PROCEDIMIENTO INSERTAR MATERIA_PRIMA
DELIMITER $
CREATE PROCEDURE INSERTAR_MATERIA_PRIMA
(
    IN P_I_NOMBRE VARCHAR(50),
    IN P_I_VALOR_UNITARIO_MAT_PRIMA BIGINT,
    IN P_I_FECHA_VENCIMIENTO DATE,
    IN P_I_CANTIDAD BIGINT,
    IN P_I_PRESENTACION VARCHAR(50),
    IN P_I_DESCRIPCION VARCHAR(200),
    IN P_I_ID_USUARIO INT,
    IN P_I_ESTADO BOOLEAN
)
BEGIN
    INSERT INTO MATERIA_PRIMA (NOMBRE_MATERIA_PRIMA, VALOR_UNITARIO_MAT_PRIMA, FECHA_VENCIMIENTO_MATERIA_PRIMA, CANTIDAD_EXIST_MATERIA_PRIMA, PRESENTACION_MATERIA_PRIMA, DESCRIPCION_MATERIA_PRIMA, ID_USUARIO_FK_MATERIA_PRIMA, ESTADO_MATERIA_PRIMA)
    VALUES (P_I_NOMBRE, P_I_VALOR_UNITARIO_MAT_PRIMA, P_I_FECHA_VENCIMIENTO, P_I_CANTIDAD, P_I_PRESENTACION, P_I_DESCRIPCION, P_I_ID_USUARIO, P_I_ESTADO);
END $

-- PROCEDIMIENTO INSERTAR COMPRA
DELIMITER $
CREATE PROCEDURE INSERTAR_COMPRA
(
    IN P_I_FECHA_HORA DATETIME,
    IN P_I_TIPO VARCHAR(20),
    IN P_I_TOTAL BIGINT,
    IN P_I_NOMBRE_PROVEEDOR VARCHAR(50),
    IN P_I_MARCA VARCHAR(50),
    IN P_I_TEL BIGINT,
    IN P_I_EMAIL VARCHAR(50),
    IN P_I_DESCRIPCION VARCHAR(200),
    IN P_I_ID_USUARIO INT,
    IN P_I_ESTADO VARCHAR(15)
)
BEGIN
    INSERT INTO COMPRA (FECHA_HORA_COMPRA, TIPO, TOTAL_COMPRA, NOMBRE_PROVEEDOR, MARCA, TEL_PROVEEDOR, EMAIL_PROVEEDOR, DESCRIPCION_COMPRA, ID_USUARIO_FK_COMPRA, ESTADO_FACTURA_COMPRA)
    VALUES (P_I_FECHA_HORA, P_I_TIPO, P_I_TOTAL, P_I_NOMBRE_PROVEEDOR, P_I_MARCA, P_I_TEL, P_I_EMAIL, P_I_DESCRIPCION, P_I_ID_USUARIO, P_I_ESTADO);
END $

-- PROCEDIMIENTO INSERTAR DETALLE_COMPRA_MATERIA_PRIMA
DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_COMPRA_MAT_PRIMA
(
    IN P_I_ID_DET INT,
    IN P_I_CANTIDAD BIGINT,
    IN P_I_SUB_TOTAL BIGINT,
    IN P_I_ID_COMPRA BIGINT,
    IN P_I_ID_MAT_PRIMA BIGINT,
    IN P_I_ESTADO BOOLEAN
)
BEGIN
    INSERT INTO DETALLE_COMPRA_MATERIA_PRIMA (ID_DET_COMPRA_MAT_PRIM, CANTIDAD_MAT_PRIMA_COMPRADA, SUB_TOTAL_MAT_PRIMA_COMPRADA, ID_COMPRA_FK_DET_COMPRA_MAT_PRIMA, ID_MAT_PRIMA_FK_DET_COMPRA_MAT_PRIMA, ESTADO_DET_COMPRA_MAT_PRIMA)
    VALUES (P_I_ID_DET, P_I_CANTIDAD, P_I_SUB_TOTAL, P_I_ID_COMPRA, P_I_ID_MAT_PRIMA, P_I_ESTADO);
END $

-- PROCEDIMIENTO INSERTAR DETALLE_COMPRA_PRODUCTO
DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_COMPRA_PRODUCTO
(
    IN P_I_ID_DET INT,
    IN P_I_CANTIDAD BIGINT,
    IN P_I_SUB_TOTAL BIGINT,
    IN P_I_ID_COMPRA BIGINT,
    IN P_I_ID_PRODUCTO BIGINT,
    IN P_I_ESTADO BOOLEAN
)
BEGIN
    INSERT INTO DETALLE_COMPRA_PRODUCTO (ID_DET_COMPRA_PROD, CANTIDAD_PROD_COMPRADO, SUB_TOTAL_PROD_COMPRADO, ID_COMPRA_FK_DET_COMPRA_PROD, ID_PROD_FK_DET_COMPRA_PROD, ESTADO_DET_COMPRA_PROD)
    VALUES (P_I_ID_DET, P_I_CANTIDAD, P_I_SUB_TOTAL, P_I_ID_COMPRA, P_I_ID_PRODUCTO, P_I_ESTADO);
END $

-- PROCEDIMIENTO INSERTAR RECETA
DELIMITER $
CREATE PROCEDURE INSERTAR_RECETA
(
    IN P_I_ID_PRODUCTO BIGINT,
    IN P_I_ID_MATERIA_PRIMA BIGINT,
    IN P_I_CANTIDAD DECIMAL(10,2),
    IN P_I_UNIDAD VARCHAR(10)
)
BEGIN
    INSERT INTO RECETA (ID_PRODUCTO_FK_RECETA, ID_MATERIA_PRIMA_FK_RECETA, CANTIDAD_REQUERIDA, UNIDAD_RECETA)
    VALUES (P_I_ID_PRODUCTO, P_I_ID_MATERIA_PRIMA, P_I_CANTIDAD, P_I_UNIDAD);
END $

-- PROCEDIMIENTO INSERTAR PRODUCCION
DELIMITER $
CREATE PROCEDURE INSERTAR_PRODUCCION
(
    IN P_I_NOMBRE VARCHAR(50),
    IN P_I_CANT BIGINT,
    IN P_I_DESCRIPCION VARCHAR(200),
    IN P_I_ID_PRODUCTO BIGINT,
    IN P_I_ID_USUARIO INT,
    IN P_I_ESTADO BOOLEAN
)
BEGIN
    INSERT INTO PRODUCCION (NOMBRE_PRODUCCION, CANT_PRODUCCION, DESCRIPCION_PRODUCCION, ID_PRODUCTO_FK_PRODUCCION, ID_USUARIO_FK_PRODUCCION, ESTADO_PRODUCCION)
    VALUES (P_I_NOMBRE, P_I_CANT, P_I_DESCRIPCION, P_I_ID_PRODUCTO, P_I_ID_USUARIO, P_I_ESTADO);
END $

-- PROCEDIMIENTO INSERTAR DETALLE_PRODUCCION
DELIMITER $
CREATE PROCEDURE INSERTAR_DETALLE_PRODUCCION
(
    IN P_I_ID_PRODUCCION BIGINT,
    IN P_I_ID_MATERIA_PRIMA BIGINT,
    IN P_I_CANTIDAD_REQUERIDA DECIMAL(10,2),
    IN P_I_CANTIDAD_USADA DECIMAL(10,2)
)
BEGIN
    INSERT INTO DETALLE_PRODUCCION (ID_PRODUCCION, ID_MATERIA_PRIMA, CANTIDAD_REQUERIDA, CANTIDAD_USADA)
    VALUES (P_I_ID_PRODUCCION, P_I_ID_MATERIA_PRIMA, P_I_CANTIDAD_REQUERIDA, P_I_CANTIDAD_USADA);
END $
