USE PROYECTO_WYK;

-- PROCEDIMIENTO CONSULTAR ROL
CALL CONSULTAR_ROL();

-- PROCEDIMIENTO CONSULTAR USUARIO
CALL CONSULTAR_USUARIO();

-- PROCEDIMIENTO CONSULTAR TAREA
CALL CONSULTAR_TAREA();

-- PROCEDIMIENTO CONSULTAR PRODUCTO
CALL CONSULTAR_PRODUCTO();

-- PROCEDIMIENTO CONSULTAR VENTA
CALL CONSULTAR_VENTA();
CALL CONSULTAR_VENTA_MESERO(1);

-- PROCEDIMIENTO CONSULTAR DETALLE_VENTA
CALL CONSULTAR_DETALLE_VENTA();

-- PROCEDIMIENTO CONSULTAR AJUSTE_INVENTARIO
CALL CONSULTAR_AJUSTE_INVENTARIO();

-- PROCEDIMIENTO CONSULTAR MATERIA_PRIMA
CALL CONSULTAR_MATERIA_PRIMA();

-- PROCEDIMIENTO CONSULTAR COMPRA
CALL CONSULTAR_COMPRA();

-- PROCEDIMIENTO CONSULTAR DETALLE_COMPRA_MATERIA_PRIMA
CALL CONSULTAR_DETALLE_COMPRA_MATERIA_PRIMA();

-- PROCEDIMIENTO CONSULTAR DETALLE_COMPRA_PRODUCTO
CALL CONSULTAR_DETALLE_COMPRA_PRODUCTO();

-- PROCEDIMIENTO CONSULTAR RECETA
CALL CONSULTAR_RECETA();

-- PROCEDIMIENTO CONSULTAR PRODUCCION
CALL CONSULTAR_PRODUCCION();

-- PROCEDIMIENTO CONSULTAR DETALLE_PRODUCCION
CALL CONSULTAR_DETALLE_PRODUCCION();
