USE PROYECTO_WYK;

START TRANSACTION;
-- Se comenta esto porque se va a ejecutar desde spring boot solo ROLES y USUARIOS
-- PROCEDIMIENTO INSERTAR ROL
-- CALL INSERTAR_ROL('ADMINISTRADOR', 'ADMINISTRADOR', 1);
-- CALL INSERTAR_ROL('MESERO', 'EMPLEADO', 1);
-- CALL INSERTAR_ROL('CAJERO', 'EMPLEADO', 1);
-- CALL INSERTAR_ROL('COCINERO', 'EMPLEADO', 1);

-- PROCEDIMIENTO INSERTAR USUARIO
-- CALL INSERTAR_USUARIO(1001, 'Juan Perez', 'pass123', 3101234567, 'juan@correo.com', NOW(), 1, 1);
-- CALL INSERTAR_USUARIO(1002, 'Maria Lopez', 'pass456', 3112345678, 'maria@correo.com', NOW(), 2, 1);
-- CALL INSERTAR_USUARIO(1003, 'Carlos Ruiz', 'pass789', 3123456789, 'carlos@correo.com', NOW(), 3, 1);
-- CALL INSERTAR_USUARIO(1004, 'Ana Torres', 'pass000', 3134567890, 'ana@correo.com', NOW(), 4, 1);

-- PROCEDIMIENTO INSERTAR TAREA
CALL INSERTAR_TAREA('Revisar inventario', 'Inventario', 'Control de materias primas', 2, 'ALTA', 'PENDIENTE', 2, 1);
CALL INSERTAR_TAREA('Atender mostrador', 'Ventas', 'Atención al cliente y caja', 5, 'MEDIA', 'PENDIENTE', 3, 1);
CALL INSERTAR_TAREA('Limpieza horno', 'Mantenimiento', 'Limpieza diaria', 1, 'BAJA', 'COMPLETADA', 4, 1);
CALL INSERTAR_TAREA('Elaborar pan', 'Producción', 'Producción pan de trigo', 3, 'ALTA', 'PENDIENTE', 2, 1);

-- PROCEDIMIENTO INSERTAR PRODUCTO
CALL INSERTAR_PRODUCTO(101, 'Pan de Trigo', 1500, 200, '2025-12-31', 'PANADERIA', 2, 1);
CALL INSERTAR_PRODUCTO(102, 'Pastel Chocolate', 5000, 50, '2025-10-15', 'PASTELERIA', 2, 1);
CALL INSERTAR_PRODUCTO(103, 'Jabón Liquido', 3000, 40, '2026-05-10', 'ASEO', 2, 1);
CALL INSERTAR_PRODUCTO(104, 'Pan Integral', 2000, 100, '2025-12-20', 'PANADERIA', 2, 1);

-- PROCEDIMIENTO INSERTAR VENTA
CALL INSERTAR_VENTA(NOW(), 0, 1, 'Venta mostrador', 1, 'PREPARANDO', 'PENDIENTE');
CALL INSERTAR_VENTA(NOW(), 0, 2, 'Producto entregado. Falta por pagar', 2, 'ENTREGADO', 'PENDIENTE');
CALL INSERTAR_VENTA(NOW(), 0, NULL, 'Venta rapida', 3, 'ENTREGADO', 'PAGADA');
CALL INSERTAR_VENTA(NOW(), 0, NULL, 'El cliente se arrepintio y se fue.', 4, 'CANCELADO', 'CANCELADA');

-- PROCEDIMIENTO INSERTAR DETALLE_VENTA
CALL INSERTAR_DETALLE_VENTA(2, 3000, 1, 101);  -- 2 panes de trigo
CALL INSERTAR_DETALLE_VENTA(1, 5000, 2, 102);  -- 1 pastel
CALL INSERTAR_DETALLE_VENTA(3, 6000, 3, 101);  -- 3 panes
CALL INSERTAR_DETALLE_VENTA(2, 4000, 4, 104);  -- 2 integrales

-- PROCEDIMIENTO INSERTAR AJUSTE_INVENTARIO
CALL INSERTAR_AJUSTE_INVENTARIO(NOW(), 'DAÑADO', 5, 'Producto dañado en transporte', 101, 2);
CALL INSERTAR_AJUSTE_INVENTARIO(NOW(), 'PERDIDA', 2, 'Pérdida en bodega', 102, 2);
CALL INSERTAR_AJUSTE_INVENTARIO(NOW(), 'CADUCADO', 10, 'Producto vencido', 103, 2);
CALL INSERTAR_AJUSTE_INVENTARIO(NOW(), 'MUESTRA', 1, 'Muestra a cliente', 104, 2);

-- PROCEDIMIENTO INSERTAR MATERIA_PRIMA
CALL INSERTAR_MATERIA_PRIMA('Harina Trigo', 20000, '2026-01-01', 500, 'Kg', 'Harina de alta calidad', 2, 1);
CALL INSERTAR_MATERIA_PRIMA('Azúcar', 15000, '2026-02-01', 300, 'Kg', 'Azúcar blanca refinada', 2, 1);
CALL INSERTAR_MATERIA_PRIMA('Levadura', 18000, '2025-11-15', 100, 'Kg', 'Levadura fresca', 2, 1);
CALL INSERTAR_MATERIA_PRIMA('Chocolate', 30000, '2026-03-10', 200, 'Kg', 'Cacao puro', 2, 1);

-- PROCEDIMIENTO INSERTAR COMPRA
CALL INSERTAR_COMPRA(NOW(), 'MATERIA PRIMA', 0, 'Proveedor Harinas', 'Harinas', 3201234567, 'proveedor1@correo.com', 'Compra mensual harina', 2, 'PAGADA');
CALL INSERTAR_COMPRA(NOW(), 'MATERIA PRIMA', 0, 'Proveedor Azúcar', 'Incauca', 3202345678, 'proveedor2@correo.com', 'Compra mensual azúcar', 2, 'PAGADA');
CALL INSERTAR_COMPRA(NOW(), 'PRODUCTO TERMINADO', 0, 'Proveedor Aseo', 'Familia', 3203456789, 'proveedor3@correo.com', 'Compra jabón líquido', 2, 'PENDIENTE');
CALL INSERTAR_COMPRA(NOW(), 'MATERIA PRIMA', 0, 'Proveedor Levadura', 'Levapan', 3204567890, 'proveedor4@correo.com', 'Compra semanal levadura', 2, 'PAGADA');

-- PROCEDIMIENTO INSERTAR DETALLE_COMPRA_MATERIA_PRIMA
CALL INSERTAR_DETALLE_COMPRA_MAT_PRIMA(1, 100, 100000, 1, 1, 1);
CALL INSERTAR_DETALLE_COMPRA_MAT_PRIMA(2, 50, 50000, 2, 2, 1);
CALL INSERTAR_DETALLE_COMPRA_MAT_PRIMA(3, 30, 30000, 4, 3, 1);
CALL INSERTAR_DETALLE_COMPRA_MAT_PRIMA(4, 20, 20000, 1, 4, 1);

-- PROCEDIMIENTO INSERTAR DETALLE_COMPRA_PRODUCTO
CALL INSERTAR_DETALLE_COMPRA_PRODUCTO(1, 10, 30000, 1, 101, 1);
CALL INSERTAR_DETALLE_COMPRA_PRODUCTO(2, 15, 45000, 2, 102, 1);
CALL INSERTAR_DETALLE_COMPRA_PRODUCTO(3, 8, 24000, 3, 103, 1);
CALL INSERTAR_DETALLE_COMPRA_PRODUCTO(4, 20, 60000, 4, 104, 1);

-- PROCEDIMIENTO INSERTAR PRODUCCION
CALL INSERTAR_PRODUCCION('Producción Pan Trigo', 100, 'Elaboración diaria pan', 101, 2, 'PENDIENTE');
CALL INSERTAR_PRODUCCION('Producción Pastel Chocolate', 50, 'Elaboración semanal pastel', 102, 2, 'EN_PROCESO');
CALL INSERTAR_PRODUCCION('Producción Pan Integral', 80, 'Producción alterna', 104, 2, 'FINALIZADA');
CALL INSERTAR_PRODUCCION('Producción Jabón Liquido', 20, 'Producción especial', 103, 2, 'CANCELADA');

-- PROCEDIMIENTO INSERTAR DETALLE_PRODUCCION
CALL INSERTAR_DETALLE_PRODUCCION(1, 1, 50);   -- Harina pan trigo
CALL INSERTAR_DETALLE_PRODUCCION(1, 2, 20);   -- Azúcar pan trigo
CALL INSERTAR_DETALLE_PRODUCCION(1, 3, 10);   -- Levadura pan trigo
CALL INSERTAR_DETALLE_PRODUCCION(1, 4, 5);     -- Chocolate pan trigo

CALL INSERTAR_DETALLE_PRODUCCION(2, 1, 30);   -- Harina pastel
CALL INSERTAR_DETALLE_PRODUCCION(2, 2, 15);   -- Azúcar pastel
CALL INSERTAR_DETALLE_PRODUCCION(2, 3, 5);     -- Levadura pastel
CALL INSERTAR_DETALLE_PRODUCCION(2, 4, 20);   -- Chocolate pastel

CALL INSERTAR_DETALLE_PRODUCCION(3, 1, 40);   -- Harina integral
CALL INSERTAR_DETALLE_PRODUCCION(3, 2, 10);   -- Azúcar integral
CALL INSERTAR_DETALLE_PRODUCCION(3, 3, 8);     -- Levadura integral
CALL INSERTAR_DETALLE_PRODUCCION(3, 4, 2);     -- Chocolate integral

CALL INSERTAR_DETALLE_PRODUCCION(4, 1, 20);   -- Harina jabón (ejemplo)
CALL INSERTAR_DETALLE_PRODUCCION(4, 2, 5);     -- Azúcar jabón
CALL INSERTAR_DETALLE_PRODUCCION(4, 3, 3);     -- Levadura jabón
CALL INSERTAR_DETALLE_PRODUCCION(4, 4, 1);     -- Chocolate jabón

COMMIT;
SELECT 'Todos los CALL INSERTAR ejecutados correctamente. COMMIT realizado.' AS Mensaje;

/*ROLLBACK; ejecutar en caso de error.*/
