USE PROYECTO_WYK;

CREATE VIEW VISTA_CARGO AS
SELECT ID_CARGO, NOMBRE_CARGO, ESTADO_CARGO
FROM CARGO;

CREATE VIEW VISTA_EMPLEADO AS
SELECT E.ID_EMPLEADO, E.CC_EMPLEADO, E.NOMBRE_EMPLEADO, E.RH_EMPLEADO,
       E.TEL_EMPLEADO, E.EMAIL_EMPLEADO, C.NOMBRE_CARGO, E.ESTADO_EMPLEADO
FROM EMPLEADO E
JOIN CARGO C ON E.ID_CARGO_FK_EMPLEADO = C.ID_CARGO;

CREATE VIEW VISTA_CLIENTE AS
SELECT C.ID_CLIENTE, C.NUM_DOCUMENTO_CLIENTE, C.TIPO_DOCUMENTO_CLIENTE,
       C.NOMBRE_CLIENTE, C.TEL_CLIENTE, C.EMAIL_CLIENTE,
       E.NOMBRE_ENPLEADO AS ASESOR, C.ESTADO_CLIENTE
FROM CLIENTE C
JOIN EMPLEADO E ON C.ID_EMPLEADO_FK_CLIENTE = E.ID_EMPLEADO;

CREATE VIEW VISTA_USUARIO AS
SELECT U.ID_USUARIO, U.NOMBRE_USUARIO, U.FECHA_REGISTRO, U.FECHA_ULTIMA_SESION, 
       U.ESTADO_USUARIO,
       COALESCE(UE.TIPO_ACCESO, 'CLIENTE') AS TIPO_USUARIO
FROM USUARIO U
LEFT JOIN USUARIO_EMPLEADO UE ON U.ID_USUARIO = UE.ID_USUARIO;

CREATE VIEW VISTA_PEDIDO AS
SELECT P.ID_PEDIDO, P.FECHA_HORA_PEDIDO, P.NUMERO_MESA, 
       E.NOMBRE_ENPLEADO AS ATENDIDO_POR, 
       C.NOMBRE_CLIENTE AS CLIENTE,
       P.ESTADO_PEDIDO
FROM PEDIDO P
JOIN EMPLEADO E ON P.ID_EMPLEADO_FK_PEDIDO = E.ID_EMPLEADO
JOIN CLIENTE C ON P.ID_CLIENTE_FK_PEDIDO = C.ID_CLIENTE;

CREATE VIEW VISTA_PRODUCTO AS
SELECT ID_PRODUCTO, NOMBRE_PRODUCTO, VALOR_UNITARIO_PRODUCTO, 
       CANT_MINI_PRODUCTO, CANT_MAX_PRODUCTO, CANT_EXIST_PRODUCTO,
       FECHA_VENCIMIENTO_PRODUCTO, TIPO_PRODUCTO_GERENERAL, TIPO_PRODUCTO_ESPECIFICO,
       MARCA_PRODUCTO, ESTADO_PRODUCTO
FROM PRODUCTO;

CREATE VIEW VISTA_DETALLE_PEDIDO AS
SELECT D.ID_DETALLE_PEDIDO, D.DESCRIPCION_DETALLE_PEDIDO,
       P.NOMBRE_PRODUCTO, DP.FECHA_HORA_PEDIDO, D.DETALLE_PEDIDO_PRODUCTO
FROM DETALLE_PEDIDO D
JOIN PRODUCTO P ON D.ID_PRODUCTO_FK_DETALLE_PEDIDO = P.ID_PRODUCTO
JOIN PEDIDO DP ON D.ID_PEDIDO_FK_DETALLE_PEDIDO = DP.ID_PEDIDO;

CREATE VIEW VISTA_FACTURA_VENTA AS
SELECT F.ID_FACTURA_VENTA, F.TOTAL_FACTURA_VENTA, F.FECHA_HORA_FACTURA_VENTA,
       F.DESCRIPCION_FACTURA_VENTA, E.NOMBRE_ENPLEADO AS VENDEDOR,
       C.NOMBRE_CLIENTE AS CLIENTE, P.ID_PEDIDO,
       F.ESTADO_FACTURA_VENTA
FROM FACTURA_VENTA F
JOIN EMPLEADO E ON F.ID_EMPLEADO_FK_FACTURA_VENTA = E.ID_EMPLEADO
JOIN CLIENTE C ON F.ID_CLIENTE_FK_FACTURA_VENTA = C.ID_CLIENTE
JOIN PEDIDO P ON F.ID_PEDIDO_FK_FACTURA_VENTA = P.ID_PEDIDO;

CREATE VIEW VISTA_MATERIA_PRIMA AS
SELECT ID_MATERIA_PRIMA, NOMBRE_MATERIA_PRIMA, FECHA_VENCIMIENTO_MATERIA_PRIMA,
       TIPO_DE_MEDIDA, CANTIDAD_MINI_MATERIA_PRIMA, CANTIDAD_MAX_MATERIA_PRIMA,
       CANTIDAD_EXIST_MATERIA_PRIMA, MARCA_MATERIA_PRIMA, PRESENTACION_MATERIA_PRIMA,
       DESCRIPCION_MATERIA_PRIMA, ESTADO_MATERIA_PRIMA
FROM MATERIA_PRIMA;

CREATE VIEW VISTA_FACTURA_COMPRA AS
SELECT F.ID_FACTURA_COMPRA,
       F.TOTAL_FACTURA_COMPRA,
       F.FECHA_HORA_FACTURA_COMPRA,
       F.DESCRIPCION_FACTURA_COMPRA,
       E.NOMBRE_ENPLEADO AS RESPONSABLE,
       P.NOMBRE_PROVEEDOR,
       F.ESTADO_FACTURA_COMPRA
FROM FACTURA_COMPRA F
JOIN EMPLEADO E ON F.ID_EMPLEADO_FK_FACTURA_COMPRA = E.ID_EMPLEADO
JOIN PROVEEDOR P ON F.ID_PROOVEEDOR_FK_FACTURA_COMPRA = P.ID_PROVEEDOR;

CREATE VIEW VISTA_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA AS
SELECT D.ID_DETALLE_FAC_MAT_PRIM,
       MP.NOMBRE_MATERIA_PRIMA,
       D.CANTIDAD_MATERIA_PRIMA_COMPRADA,
       D.SUB_TOTAL_MATERI_PRIMA_COMPRADA,
       FC.ID_FACTURA_COMPRA,
       FC.FECHA_HORA_FACTURA_COMPRA,
       D.ESTADO_DETALLE_COMPRA_MATERIA_PRIMA
FROM DETALLE_FACTURA_COMPRA_MATERIA_PRIMA D
JOIN MATERIA_PRIMA MP ON D.ID_MATERIA_PRIMA_FK_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA = MP.ID_MATERIA_PRIMA
JOIN FACTURA_COMPRA FC ON D.ID_FACTURA_COMPRA_FK_DETALLE_FACTURA_COMPRA_MATERIA_PRIMA = FC.ID_FACTURA_COMPRA;

CREATE VIEW VISTA_DETALLE_COMPRA_PRODUCTO AS
SELECT D.ID_DETALLE_COMPRA_PRODUCTO,
       P.NOMBRE_PRODUCTO,
       D.CANTIDAD_PRODUCTO_COMPRADO,
       D.SUB_TOTAL_PRODUCTO_COMPRADO,
       FC.ID_FACTURA_COMPRA,
       FC.FECHA_HORA_FACTURA_COMPRA,
       D.ESTADO_DETALLE_COMPRA_PRODUCTO
FROM DETALLE_COMPRA_PRODUCTO D
JOIN PRODUCTO P ON D.ID_PRODUCTO_FK_DETALLE_COMPRA_PRODUCTO = P.ID_PRODUCTO
JOIN FACTURA_COMPRA FC ON D.ID_FACTURA_COMPRA_FK_DETALLE_COMPRA_PRODUCTO = FC.ID_FACTURA_COMPRA;

CREATE VIEW VISTA_DETALLE_VENTA_PRODUCTO AS
SELECT D.ID_DETALLE_VENTA_PRODUCTO,
       P.NOMBRE_PRODUCTO,
       D.CANTIDAD_PRODUCTO_VENDIDO,
       D.SUB_TOTAL_PRODUCTO_VENDIDO,
       F.ID_FACTURA_VENTA,
       F.FECHA_HORA_FACTURA_VENTA,
       D.ESTADO_DETALLE_VENTA_PRODUCTO
FROM DETALLE_VENTA_PRODUCTO D
JOIN PRODUCTO P ON D.ID_PRODUCTO_FK_DETALLE_FACTURA_VENTA = P.ID_PRODUCTO
JOIN FACTURA_VENTA F ON D.ID_FACTURA_VENTA_FK_DETALLE_VENTA_PRODUCTO = F.ID_FACTURA_VENTA;

CREATE VIEW VISTA_PRODUCCION AS
SELECT PR.ID_PRODUCCION,
       PR.NOMBRE_PRODUCCION,
       PR.CANT_PRODUCCION,
       PR.DESCRIPCION_PRODUCCION,
       PR.MATERIA_PRIMA_GASTADA,
       MP.NOMBRE_MATERIA_PRIMA,
       PD.NOMBRE_PRODUCTO,
       E.NOMBRE_ENPLEADO AS RESPONSABLE,
       PR.ESTADO_PRODUCCION
FROM PRODUCCION PR
JOIN MATERIA_PRIMA MP ON PR.ID_MATERIA_PRIMA_FK_PRODUCCION = MP.ID_MATERIA_PRIMA
JOIN PRODUCTO PD ON PR.ID_PRODUCTO_FK_MATERIA_PRIMA = PD.ID_PRODUCTO
JOIN EMPLEADO E ON PR.ID_EMPLEADO_FK_PRODUCCION = E.ID_EMPLEADO;

CREATE VIEW VISTA_FACTURACION_GENERAL AS
SELECT 
  FV.ID_FACTURA_VENTA,
  FV.FECHA_HORA_FACTURA_VENTA,
  FV.TOTAL_FACTURA_VENTA,
  FV.ESTADO_FACTURA_VENTA,
  CL.NOMBRE_CLIENTE,
  E.NOMBRE_ENPLEADO AS VENDEDOR,
  P.ID_PEDIDO,
  P.FECHA_HORA_PEDIDO
FROM FACTURA_VENTA FV
JOIN CLIENTE CL ON FV.ID_CLIENTE_FK_FACTURA_VENTA = CL.ID_CLIENTE
JOIN EMPLEADO E ON FV.ID_EMPLEADO_FK_FACTURA_VENTA = E.ID_EMPLEADO
JOIN PEDIDO P ON FV.ID_PEDIDO_FK_FACTURA_VENTA = P.ID_PEDIDO;

CREATE VIEW VISTA_STOCK_PRODUCTOS_CRITICO AS
SELECT 
  ID_PRODUCTO,
  NOMBRE_PRODUCTO,
  CANT_EXIST_PRODUCTO,
  CANT_MINI_PRODUCTO,
  ESTADO_PRODUCTO
FROM PRODUCTO
WHERE CANT_EXIST_PRODUCTO < CANT_MINI_PRODUCTO;

CREATE VIEW VISTA_MATERIA_PRIMA_CRITICO AS
SELECT 
  ID_MATERIA_PRIMA,
  NOMBRE_MATERIA_PRIMA,
  CANTIDAD_EXIST_MATERIA_PRIMA,
  CANTIDAD_MINI_MATERIA_PRIMA,
  ESTADO_MATERIA_PRIMA
FROM MATERIA_PRIMA
WHERE CANTIDAD_EXIST_MATERIA_PRIMA < CANTIDAD_MINI_MATERIA_PRIMA;

SELECT 
    DATE(FECHA_HORA_FACTURA_VENTA) AS FECHA,
    SUM(TOTAL_FACTURA_VENTA) AS TOTAL_VENDIDO
FROM FACTURA_VENTA
WHERE ESTADO_FACTURA_VENTA = 'PAGADA'
GROUP BY DATE(FECHA_HORA_FACTURA_VENTA)
ORDER BY FECHA DESC;

SELECT 
    P.NOMBRE_PRODUCTO,
    SUM(DVP.CANTIDAD_PRODUCTO_VENDIDO) AS TOTAL_VENDIDO
FROM DETALLE_VENTA_PRODUCTO DVP
JOIN PRODUCTO P ON DVP.ID_PRODUCTO_FK_DETALLE_FACTURA_VENTA = P.ID_PRODUCTO
JOIN FACTURA_VENTA F ON DVP.ID_FACTURA_VENTA_FK_DETALLE_VENTA_PRODUCTO = F.ID_FACTURA_VENTA
WHERE F.ESTADO_FACTURA_VENTA = 'PAGADA'
GROUP BY P.NOMBRE_PRODUCTO
ORDER BY TOTAL_VENDIDO DESC
LIMIT 5;

SELECT 
    F.ID_FACTURA_VENTA,
    F.FECHA_HORA_FACTURA_VENTA,
    F.TOTAL_FACTURA_VENTA,
    F.ESTADO_FACTURA_VENTA
FROM FACTURA_VENTA F
JOIN CLIENTE C ON F.ID_CLIENTE_FK_FACTURA_VENTA = C.ID_CLIENTE
WHERE C.NUM_DOCUMENTO_CLIENTE = 123456789; -- Reemplazar por el documento real


SELECT 
    P.NOMBRE_PRODUCTO,
    DVP.CANTIDAD_PRODUCTO_VENDIDO,
    DVP.SUB_TOTAL_PRODUCTO_VENDIDO
FROM DETALLE_VENTA_PRODUCTO DVP
JOIN PRODUCTO P ON DVP.ID_PRODUCTO_FK_DETALLE_FACTURA_VENTA = P.ID_PRODUCTO
WHERE DVP.ID_FACTURA_VENTA_FK_DETALLE_VENTA_PRODUCTO = 1; -- Reemplazar por ID real


SELECT 
  U.ID_USUARIO,
  U.NOMBRE_USUARIO,
  COALESCE(UE.TIPO_ACCESO, 'CLIENTE') AS TIPO_USUARIO,
  U.FECHA_REGISTRO,
  U.FECHA_ULTIMA_SESION,
  U.ESTADO_USUARIO
FROM USUARIO U
LEFT JOIN USUARIO_EMPLEADO UE ON U.ID_USUARIO = UE.ID_USUARIO;

SELECT 
  U.ID_USUARIO,
  U.NOMBRE_USUARIO,
  UE.TIPO_ACCESO,
  U.FECHA_REGISTRO,
  U.FECHA_ULTIMA_SESION,
  U.ESTADO_USUARIO,
  E.NOMBRE_ENPLEADO,
  E.CC_ENPLEADO,
  E.TEL_EMPLEADO,
  E.RH_EMPLEADO,
  C.NOMBRE_CARGO
FROM USUARIO U
JOIN USUARIO_EMPLEADO UE ON U.ID_USUARIO = UE.ID_USUARIO
JOIN EMPLEADO E ON UE.ID_EMPLEADO = E.ID_EMPLEADO
JOIN CARGO C ON E.ID_CARGO_FK_EMPLEADO = C.ID_CARGO;








